### ISSUE TITLE
Will notEmpty() do a trim before hand?

### ISSUE THREAD

**Issue by panzhangwang** [ctavan/express-validator#100]
I have to sanitize an input if it contains whitespaces only.
```javascript
req.sanitize("title").trim();
req.checkBody('title', 'Title cannot be blank').notEmpty();
```

**Comment by rustybailey** [comment]
`notEmpty()` does not do a trim beforehand. So you need to sanitize your input if you expect something like `"    "` to come through as a "title" as it would pass the `notEmpty()` test.
