### ISSUE TITLE
validationErrors(true) only map the last error

### ISSUE THREAD

**Issue by kyfr59** [ctavan/express-validator#102]
Hi,

With this code :

```
req.assert('email', 'empty e-mail').notEmpty();    
req.assert('email', 'invalid e-mail').isEmail();    
var errors = req.validationErrors();  
console.dir(errors);
```

the console returns :

```
[ { param: 'email',
    msg: 'empty e-mail',
    value: '' },
  { param: 'email',
    msg: 'invalid e-mail',
    value: '' } ]
```

With this code :       

```
req.assert('email', 'empty e-mail').notEmpty();    
req.assert('email', 'invalid e-mail').isEmail();    
var errors = req.validationErrors(true);  
console.dir(errors);
```

it returns only the last error :  

```
{ email: 
{ param: 'email',
msg: 'invalid e-mail',
value: '' } }
```

An idea ?

**Comment by ssbb** [comment]
Yes, thats sad. In fact because of this I wrote a helper for getting all errors, but as an object - https://github.com/evilrobts/express-validator-helper

**Comment by slier81** [comment]
still not resolve?

**Comment by superclarkk** [comment]
The solution to this issue is to use normal errors rather than mappedErrors. However, I've raised issue #161 to clarify mappedErrors in the docs.

**Comment by gustavohenke** [comment]
So, this has been explicitly documented, thanks to the request of @superclarkk.

Changing this behavior is likely to require the release of a major version. If more people require such change, I can make it happen in an eventual v3.0.0.

As usual, PRs are welcome.
