### ISSUE TITLE
add OR operator 

### ISSUE THREAD

**Issue by gkorland** [ctavan/express-validator#108]
We need a way to define an OR operator e.g. 

req.checkBody('phones', 'Invalid postparam').isInt().or.isArray();

**Comment by Skryabind** [comment]
OR is needing for me too. My use case: I receive a hostname, witch might be an IP address. Construction like isIP().or().isFQDN() will be perfect

**Comment by samuelfine** [comment]
Disclaimer: I'm new to this library, haven't dug in too much so forgive me if I miss something obvious. :)

In lieu of a `or()` operator, I _think_ a custom validator might do the trick? Something like:

```
app.use(expressValidator({
 customValidators: {
    isIPorFQDN: function(address) {
        return(validator.isIP(address) || validator.isFQDN(address));
    }
 }
}));
```

**Comment by rustybailey** [comment]
Using a custom validator like that is definitely what you want to do. Let me know if you have any issues with it.

**Comment by gkorland** [comment]
Yes, we can write custom validator which might solve this case but we need a more generic solution.

**Comment by tuananh** [comment]
chaining OR would be difficult.

**Comment by SeanDunford** [comment]
What if there was an entirely separate check for mutual exclusion. 

`function exlude([Array of String Params])`

That ensured the mutual exclusion of the the params in the array. 

```
function handler(req, res) { 
 req.excludeBody(['paramA', 'paramB']); 
 req.excludeParams(['paramA', 'paramB']); 
 req.excludeQuery(['paramA', 'paramB']); 
```

then you could add custom validation to 
```
req.excludeBody(['phone', 'phones']); 
req.checkBody('phone', 'Invalid postparam').isInt(); 
req.checkBody('phones', 'Invalid postparam').isArray(); 
```


A good use case for me is performing actions by either "email" or "accountId". I want to check that one or the other exists but I don't necessarily want/need both to be in the request.

**Comment by gustavohenke** [comment]
Hi @SeanDunford, that would be yet another issue.
This one asks for a complex, chainable OR operator between two checks.

**Comment by SeanDunford** [comment]
@gustavohenke agreed. Was just wondering if it was a pattern that you would even consider. Admittedly, it's bit of a weird api. So I thought it made more sense to ask here as an alternative. Rather than submit a new issue/request.

**Comment by gustavohenke** [comment]
Yes, I would definitely consider it. I'm trying to figure out a cool API for a possible v4, but when you have no computers while at home, it gets difficult to try stuff 😄

**Comment by gustavohenke** [comment]
Hello folks! [v4.0.0 has finally been released](https://github.com/ctavan/express-validator/releases/tag/v4.0.0)!

You can now check if at least one of the validator chains is valid by using the new `oneOf` function in the `check` API collection:

```js
const { check, oneOf, validationResult } = require('express-validator/check');
app.get('/', oneOf([
  check('a').exists(),
  check('b').exists(),
  check('c').exists()
], 'you must provide at least a, b or c'), (req, res, next) => {
  const result = validationResult(req);
  // do something with the validation result!
});
```

Please check the README for complete docs, and also check the [upgrade guide](https://github.com/ctavan/express-validator/blob/v4.0.0/UPGRADE_GUIDE.md).
