### ISSUE TITLE
req.validationErrors returns null

### ISSUE THREAD

**Issue by mrpmorris** [ctavan/express-validator#111]
If my validations pass then req.validationErrors returns null.  As I pass these errors to the view it means that I have to check 

if (errors && errors['email'])
  span #{errors['email'].msg}

Instead of returning null could it instead return an empty array?  My other workaround is to use the following code in my controller.

var errors = req.validationErrors(true) || [];

The code in express-validator that causes the null return value is in express_validator.js line 210

    req.validationErrors = function(mapped) {
      if (req._validationErrors === undefined) {
        return null;
      }

**Comment by rustybailey** [comment]
I would say to continue adding `var errors = req.validationErrors(true) || [];` in your code for now. Currently, everyone relies on it being `null` so they can go straight into `if (errors) {`, so changing it to `[]` would be an unnecessary breaking change.
