### ISSUE TITLE
4.11 deprecates req.param()

### ISSUE THREAD

**Issue by analytically** [ctavan/express-validator#112]
https://github.com/strongloop/express/commit/591e89ed1890c3f519c9a732e164e64e758f6dbb

**Comment by olivierkaisin** [comment]
+1

**Comment by soomtong** [comment]
for just don't want that deprecated message.

```javascript
    req.checkBody('email', 'Email is not valid').isEmail();
    req.checkBody('password', 'Password cannot be blank').notEmpty();

    var errors = req.validationErrors();

    if (errors) {
        req.flash('errors', errors);
        return res.redirect('/login');
    }
```
i think, we should use like that just now, coz redesigned express 4.x, they will not want implicit expression.

**Comment by satblip** [comment]
@soomtong I don't get your point, sorry. It doesn't remove the deprecated message

**Comment by soomtong** [comment]
hi @satblip 
i think express 4 wants explicit expression for params, query, body. previous req.param() just return any of this 3 parameters, but now day that is a deprecated feature u know.

to solve this problem, we need to rebind `req.param()` for 3 types by our self. yes it's very convenience, but it drives to implicit code a little. we need to code for own req.param().

- https://github.com/ctavan/express-validator/blob/master/lib/express_validator.js#L175
- https://github.com/ctavan/express-validator/blob/master/lib/express_validator.js#L230

my opinion is that express 4.x design wants a explicit expression, and we can follow that's way.

change your `req.assert()` to `req.checkBody()`, `req.checkParams()`,  `req.checkQuery()`... 
just works no warning message.

this is not right way you think absolutely, but i think this is explicit one.

**Comment by satblip** [comment]
thx @soomtong, it's indeed working perfect.

But what about `req.sanitize = req.filter;` then? 

I don't see a workaround for this one :-/

**Comment by soomtong** [comment]
was nice to hear u well, @satblip 
this `express-validator` is extended wrapper for express and is based on [validator.js](https://github.com/chriso/validator.js)

- https://github.com/ctavan/express-validator/blob/master/lib/express_validator.js#L23

it's a dependency. can find in `package.json`
so, sanitize module can be found there.

**Comment by satblip** [comment]
thanks!

**Comment by kpi6com** [comment]
+1

**Comment by SamVerschueren** [comment]
Maybe it's possible to create a sanitizeBody, sanitizeParams and sanitizeQuery as well? Then keep the sanitize method in the code for backwards compatibility and throw an error like ```req.sanitize(name) is deprecated: Use req.sanitizeParams, req.sanitizeBody, or req.sanitizeQuery instead```.

Will make a pull request for this.

**Comment by kt3k** [comment]
+1
