### ISSUE TITLE
has no method checkBody

### ISSUE THREAD

**Issue by anbublacky** [ctavan/express-validator#114]
I am using express 4.11.1 and express-validator 2.8.0.

here is the code i used above post action:

    var util = require('util');
    var express = require('express');
    var bodyParser = require('body-parser');
    var expressValidator = require('express-validator');
    var app = express();

and inside post action i gave

  req.checkBody('postparam', 'Invalid postparam').notEmpty().isInt();

i am getting has no method checkBody error, don know whether version is the problem so mentioned the versions above.

**Comment by EyEdealist** [comment]
Looks like you forgot to register the bodyParser and expressValidator middleware with the app (which will add the validation methods to the request object).

Try:
```
var util = require('util');
var express = require('express');
var bodyParser = require('body-parser');
var expressValidator = require('express-validator');
var app = express();

// parse application/x-www-form-urlencoded
app.use(bodyParser.urlencoded({ extended: false }))

// parse application/json
app.use(bodyParser.json())

// add validation methods to request
app.use(expressValidator());

// now the methods are available
app.post('/', function(req, res, next) {
    req.checkBody('postparam', 'Invalid postparam').notEmpty().isInt();
});
```

**Comment by anbublacky** [comment]
I'm not using app.post, i'm exporting the function like 

    exports.postRide = function (req, res) {
      req.checkBody('postparam', 'Invalid postparam').notEmpty().isInt();

so here i'm unable to access the CheckBody method. How can i get access inside exports.postRide?

**Comment by MarkRabey** [comment]
I too am using exports for my routes, and by adding the middleware as mentioned by @EyEdealist, I have access to `checkBody()` without issue:

```
var express = require('express'),
    path = require('path'),
    favicon = require('serve-favicon'),
    logger = require('morgan'),
    cookieParser = require('cookie-parser'),
    bodyParser = require('body-parser'),
    expressValidator = require('express-validator'),
    app = express();

app.use(bodyParser.json());
app.use(bodyParser.urlencoded({ extended: false }));
app.use(expressValidator());

```

**Comment by rustybailey** [comment]
@anbublacky Did this help? If so, please close.

**Comment by resurge** [comment]
Just a clarifying comment on this issue: make sure you "use" your router's *after* you add expressValidator. (Which makes sense but I had too look for this for a while)

```
var bodyParser = require('body-parser');
var expressValidator = require('express-validator');

app.use(bodyParser.urlencoded());
app.use(expressValidator());

// Now we can start adding routers to our app
app.use('/example', exampleRouter);
```
