### ISSUE TITLE
No license file

### ISSUE THREAD

**Issue by becausehama** [ctavan/express-validator#115]
Hi.

I looked at this issue and the Copyright notice, but there is no LICENSE file. 
https://github.com/ctavan/express-validator/issues/92

> ## License
> 
> Copyright (c) 2010 Chris O'Hara <cohara87@gmail.com>, MIT License

I think this is incomplete license notation.

Could you please add a full LICENSE file like this?
http://opensource.org/licenses/MIT

**Comment by ctavan** [comment]
Feel free to provide a pull request :).

**Comment by becausehama** [comment]
Thank you!
I submitted a pull request :-).  #116
