### ISSUE TITLE
Allow "optional" to test for truthy

### ISSUE THREAD

**Issue by mklaber** [ctavan/express-validator#120]
Currently `optional()` tests whether the expected parameter is defined or not. I'd be great if, even when defined, it be classified as optional if it evaluates to falsey. In other words, these tests should actually `pass`:

https://github.com/ctavan/express-validator/blob/master/test/optional.js#L39-L40

I suspect it'd be a more general resolution to #113 as well.

While I can create a custom validator that tests whether a value is truthy or falsey, it won't short-circuit the remaining validation declarations. So:

```javascript
isReallyOptional: function(value) {
    return !value;
  }
```

Being used like:

```javascript
req.checkQuery('addr', 'if specified, must be three or more characters')
    .isReallyOptional().len(3);
```

Passes my `isReallyOptional` check but then, of course, fails the `len` check.

Current work around is to make a single custom validator that does all of my checks (rather than chaining them):

```javascript
'use strict';
var validator = require('validator');

var Validators = {
  optionalOrLen: function(value, minLength) {
    return !value || validator.isLength(value, minLength);
  }
};

module.exports = Validators;
```

**Comment by jinwyp** [comment]
I really need this feature, " isReallyOptional"

**Comment by vijayviji** [comment]
Is there any update on this?

**Comment by rustybailey** [comment]
No, not yet. I just haven't had time yet. However, we are open to PRs.

**Comment by jamesaspence** [comment]
I ended up writing a custom sanitizer that would remove empty strings and change them to undefined instead. That way, empty strings would be ignored as optional and therefore wouldn't trigger the rest of the validation.

**Comment by rustybailey** [comment]
This feature was added in v2.18.0. See docs (https://github.com/ctavan/express-validator#optional-input)
