### ISSUE TITLE
Calling an async method from a custom validator

### ISSUE THREAD

**Issue by stonebraker** [ctavan/express-validator#122]
I'm attempting to write an isUnique custom validator which requires an async call to mongo. However, custom validators are implemented as synchronous methods without callbacks. Can you recommend a technique for accomplishing this?

**Comment by sluchznak** [comment]
Hi, i have the same problem. Please, notify me, when you find solution

**Comment by lorenz** [comment]
+1

**Comment by jp1987** [comment]
This would be great! Really need a way to integrate mongo in the validation.

**Comment by rustybailey** [comment]
This feature should now be available in 2.17.0. Please check the documentation for [async validation](https://github.com/ctavan/express-validator#asynchronous-validation) and open a new issue if that functionality doesn't work properly.
