### ISSUE TITLE
express-validator and unit test

### ISSUE THREAD

**Issue by carlosmcp** [ctavan/express-validator#123]
Hi!

How can i use the express-validator to do unit tests with module like mocha?

Example:
```javascript
//file.js
req = {} //My custom req
exports.test = function (req, callback) {
    req.checkQuery('field', 'Invalid.').notEmpty().isNumeric().isLength(4,4);
};

//Main file that require  file.js
var validationTest = rewire('file.js');
validationTest.test(req, res);  //Problem here!  -> has no method 'checkQuery'
```

**Comment by codebien** [comment]
@carlosmcp look here: http://jaketrent.com/post/testing-express-validator/

**Comment by carlosmcp** [comment]
Thanks!

**Comment by danielpinna** [comment]
Hi

This code not work for me, exists somethin wrong in the sintax.
Somebody can help me?

thanks

**Comment by gustavohenke** [comment]
@danielpinna, if you could provide further details together with a reproducible snippet of code, it would be great.

**Comment by danielpinna** [comment]
@gustavohenke

The code that did not work for me was the code below:

expressValidator = require('express-validator')()

exports.stubForValidation = (done) ->
  req =
    query: {}
    body: {}
    params: {}
    param: (name) ->
      @params[name]

  expressValidator req, {}, ->
    done(req)


The problem is that I had not realized that it was in coffee script, after converting to js it worked perfectly.

Thanks

**Comment by sapansanu** [comment]
@danielpinna can you paste the js code here please?

**Comment by danielpinna** [comment]
@sapansanu 

Here the code in JS ES6:

let expressValidator = require('express-validator')();

export function stubForValidation(done) {
  let req = {
    query: {},
    body: {},
    params: {},
    param(name) {
      return this.params[name];
    }
  };

  return expressValidator(req, {}, () => done(req));
}

**Comment by WangHansen** [comment]
I tried to use jest with express-validator, but it doesn't seems to work.
Here is the code:
```javascript
// middleware validator.js
const emailValidator =
  body('email')
    .isString()
    .withMessage('Email should be string')
    .trim().not().isEmpty()
    .withMessage('Email cannot be empty')
    .isEmail()
    .withMessage('Email is invalid')
    .customSanitizer(toLowerCase)

module.exports = { emailValidator }

// test file
import validator from './validator'
test.only('email not string should fail', async () => {
  let mockReq = httpMocks.createRequest({
    method: 'post',
    body: { email: 123 }
  })
  // console.log(mockReq)
  validator.emailValidator(mockReq, mockRes, mockNext)
  validator.checkValidationResult(mockReq, mockRes, mockNext)
  // console.log(mockReq)
  let error = mockNext.mock.calls[0][0]
  expect(mockNext).toBeCalledWith(error)
  expect(error.statusCode).toBe(400)
})
```

When I did the console log for mockReq before and after calling `emailValidator`, it doesn't seem to append the `_validationError` attribute in there.

**Comment by gustavohenke** [comment]
Hi @WangHansen,
You have 2 problems here:
1. The middleware runs asynchronously, so you need to replace `mockNext` with a callback that does the needed assertions;
2. `req.getValidationResult()` is a legacy API. It won't work when you use `check()`/`body()`/etc; [use `validationResult(req)` instead](https://express-validator.github.io/docs/check-api.html#validationresultreq).

For now, that's what is documented and will put your test in a green state.

**Comment by WangHansen** [comment]
Hi @gustavohenke, thanks for the response, for the second point, I actually used `validationResult(req)`, I forgot to change the code, which I did now. For the first point, I am not sure how to use a callback because I use mock function: `const mockNext = jest.fn()` and I can do tests this way: 
```
let error = mockNext.mock.calls[0][0]
expect(mockNext).toBeCalledWith(error)
expect(error).toBe('Email should be string')
```
How would i do it with a callback

**Comment by WangHansen** [comment]
I solved by adding the `await` in front of the function: `await validator.emailValidator(mockReq, mockRes, mockNext)`, thanks for the help!
