### ISSUE TITLE
Possible to validate array of objects?

### ISSUE THREAD

**Issue by gebrits** [ctavan/express-validator#125]
Say I've got an array of rooms, each room requires a room-number, nr of adults, nr of childs. 
It it currently possible to use dot-syntax to validate for rooms inside array?

`req.checkBody(rooms.roomNumber).isEmpty()` doesn't seem to work, which I understand because it probably checks for property `roomNumber` on the array-object itself. Is there any way to do it instead? 

I'm ok with iterating the separate rooms in a loop and checking, but I can't use `req.checkBody` for that I belive. I'd need something like `validator.checkParam(room)`. 

Any suggestions?

**Comment by Jakeii** [comment]
You could combine a custom validator with validator.js.

````javascript
expressValidator = require('express-validator');
validator = require('validator');

app.use(expressValidator({
 customValidators: {
    eachIsEmpty: function(values, prop) {
      return values.every(function(val) {
         return validator.isEmpty(val.prop);
      });
    }
 }   
}));
````
````javascript
req.checkBody('rooms').eachIsEmpty('roomNumber');
````
You could probably improve on this to add an array version for each method programmatically.

**Comment by rustybailey** [comment]
@gebrits Did this work for you? If so, please close.

**Comment by ektachawla** [comment]
Hi,
Is it possible to use this custom validator that works on json array to be used in validation schema. I need to  write validation schema but request body has a json array. Hence i have to write custom validator as above, but not able to use it in validation schema. Please help on the same.
Sample Json: { orders : [
                         {'interval': 
                            { 'startDateTime':'startDateTime'}
                         }
                     ]}

Many Thanks!

**Comment by bryanCoteChang** [comment]
Hi!  I had a similar problem writing a generic validator for all routes. This seems to be working so far, but please let me know if I'm leaving a gaping hole somewhere:
```
var escape = require('escape-html');

function validate(input) {
  if (Array.isArray(input)) {
    return input.map(validate);
  }
  
  const inputType = typeof input;
  if (inputType === 'string') {
    return escape(input);
  } else if (inputType !== 'object' || !input) {
    return input;
  }

  var output = {};
  Object.keys(input).forEach((key) => {
    output[key] = validate(input[key]);
  });
  return output;
};

module.exports = {
  validate: validate,
}
```
