### ISSUE TITLE
Custom Error Message For Chain Validation

### ISSUE THREAD

**Issue by slier81** [ctavan/express-validator#126]
```
req.checkBody('age', 'Invalid age').notEmpty().isInt();
var errors = req.validationErrors(true); 
```

This will always return `Invalid age`

How can I return `Age is empty`, when input does not pass `notEmpty()` method, and return `Age should be an integer` if it does not pass `isInt()` method?

Maybe something like this:
```
req.checkBody('age').notEmpty("Age is empty").isInt("Age should be an integer");
```

I dont want user always get `Invalid age` when he/she does not supply input for age

**Comment by rustybailey** [comment]
We can't necessarily do it like you're suggesting because those validator functions may or may not take inputs, so that would conflict. My first idea is that we could do an object in order to map messages to certain functions, like so:
``` js
req.assert('age', { notEmpty: 'Age is empty', isInt: 'Age should be an integer' }).notEmpty().isInt();
```
In the current state, I think we assume you're sending a string, but you could technically send anything in that second param, so giving objects a specific functionality could be potentially breaking if anyone is using something in that second param besides strings. So if we decided to implement it this way, it would 1) be a breaking change; 2) be limiting if someone wanted to send something other than a string for the error message.

Thoughts, @ctavan?

**Comment by ctavan** [comment]
We could make all arguments mandatory in case you want to supply an error message. For validation functions with optional arguments we would then require to pass optional arguments as explicit `undefined`.

So e.g. for `isISBN(str [, version])` the call signature with error message would be:

```js
req.checkBody('isbn').isISBN(undefined, 'Not a valid ISBN');
```

What do you think?

**Comment by slier81** [comment]
@rustybailey @ctavan maps work great but does not clean to me. as suggested by @ctavan supplying error message on the function itself look much cleaner.. i think the function itself should take a maps.

Something like this:

```
req.checkBody('isbn').isISBN({
  vesion : 'blah',
  message: 'not valid message'
});
```

**Comment by rustybailey** [comment]
Personally, I don't like the idea of putting an additional param or an object into the actual validation method. Part of me feels like if we're going to this much trouble to think of a way to shove in multiple error messages for chained validation, we should just recommend that people use two different functions if they want different error messages.

**Comment by chrissinclair** [comment]
Did anything much come of this? I've just started playing around with the library, and it's the first real issue I've hit. If you're still taking suggestions then what about something along the lines of 
```
req.check('postcode')
    .isLength(6, 8).withMessage('Invalid length for postcode')
    .matches(/^[A-Z]{1,2}[0-9]{1,2} ?[0-9][A-Z]{2}$/i).withMessage('Not a valid postcode format');
```

I've not dived through the internals of it at all yet, so couldn't comment on if that's easily achievable.

**Comment by rustybailey** [comment]
That may be one of the more viable solutions since it could potentially also be a non-breaking change. Open to a PR if you're willing to dive in.

**Comment by chrissinclair** [comment]
I'm a little busy at the moment but will see if I can't squeeze in a bit of time. Cheers :)

**Comment by rustybailey** [comment]
This was added by #159 and is in version 2.15.0
