### ISSUE TITLE
Validate array of properties with same rule

### ISSUE THREAD

**Issue by rustybailey** [ctavan/express-validator#128]
Let's say I have an object in the request body like this:

``` js
{
    a: "a",
    b: "b",
    c: "c",
    d: "d"
}
```

In this object, "a", "b", and "c" are required properties. Currently, I would write it like this:

``` js
    req.assert('a', 'Missing required field.').notEmpty();
    req.assert('b', 'Missing required field.').notEmpty();
    req.assert('c', 'Missing required field.').notEmpty();
```

I could not find a way to check an array of properties with the same rule. I thought I could maybe use an array instead of a string, but looks as though the array syntax is already taken for accessing deep object properties.

I realize that I could just do something like this...

``` js
    var required = ['a', 'b', 'c'];
    required.forEach(function(r) {
        req.assert(r, 'Missing required field.').notEmpty();
    });
```

...but I feel like it would be nice to have this functionality baked into the library.

Is there any interest in this? If so, any ideas on implementation? I thought of maybe instead of having an actual array, having a comma delimited string like below, but I'm not sure if it's the best solution:

``` js
    req.assert('a, b, c', 'Missing required field.').notEmpty();
```

Thoughts?

**Comment by codebien** [comment]
Why not like this?
req.assert(['a', 'b', 'c'], 'Missing required field.').notEmpty();

**Comment by rustybailey** [comment]
That was my first thought too, but that is the syntax currently used for validating nested data: https://github.com/ctavan/express-validator#nested-input-data

**Comment by codebien** [comment]
breaking change here is a big problem? IMHO the right way for nested data is:
req.assert('user.email', 'Missing required field.').notEmpty();

**Comment by rustybailey** [comment]
I think you're right and moving to only using a string with dot notation for nested access would allow us to use the array syntax to solve this issue's problem and we could mirror this new syntax in sanitization to solve issues #58 and #66.

Do you have any thoughts on this, @ctavan? This could be another piece of a road map towards a 3.0.0 release.

**Comment by codebien** [comment]
@rustybailey Also #125, no?

**Comment by rustybailey** [comment]
Not quite the same. #125 is talking about validating each item on a certain property that is an array. That is different than this issues where we want to validate multiple properties with the same validator.

**Comment by aristidesfl** [comment]
+1 for 'dot.notation' for validating nested properties

Would be also useful to have a way to validate all properties, and not have to specify each one in the array.

**Comment by gustavohenke** [comment]
Hello folks, [v4.0.0 has been released](https://github.com/ctavan/express-validator/releases/tag/v4.0.0), bringing with it support for validating multiple fields with the same rules!

Please check the README for complete docs, and also check the [upgrade guide](https://github.com/ctavan/express-validator/blob/v4.0.0/UPGRADE_GUIDE.md).
