### ISSUE TITLE
validate.js 3.39.0

### ISSUE THREAD

**Issue by joachimroeleveld** [ctavan/express-validator#136]
The newer version of validate.js has some handy enhancements, such as min/max options for numeric validators. Would be nice if express-validator is upgraded to use the latest version of validator (3.39.0).

**Comment by rustybailey** [comment]
Newest validator version is included in PR #135. I was just leaving it there to see if there was any feedback, but it should be merged in the next couple days.

**Comment by rustybailey** [comment]
Github and npm now have the latest version of validate.js
