### ISSUE TITLE
2.12.1

### ISSUE THREAD

**Issue by jsuiker** [ctavan/express-validator#148]
This newest version breaks something but I have no idea what it is :)

My code in production looks like this:

req.sanitize('item').toString();

the value 'item' is an integer - when 0 the sanitize function returns undefined.  any other integer seems fine.  Downgrading my express-validator version in my package.json file to 2.11.0 restores functionality.

**Comment by rustybailey** [comment]
Thanks for reporting this! Should have a fix out shortly.

**Comment by rustybailey** [comment]
This fix is now on npm as 2.12.2.

**Comment by jsuiker** [comment]
Verified working, thanks Rusty!
