### ISSUE TITLE
Undefined value in custom validator

### ISSUE THREAD

**Issue by ikokostya** [ctavan/express-validator#156]
In [node-validator](https://github.com/chriso/validator.js) first argument in custom validation function always has `string` type, because value converts to string in [validator.extend](https://github.com/chriso/validator.js#extensions).

In `express-validator` first argument in custom validation function maybe `undefined` if parameter isn't provided. 

I suggest to support same behavior like `node-validator`: use `validator.extend()` or call `validator.toString()`  before passing value in custom validator.

**Comment by rustybailey** [comment]
Can show an example as to where we're doing things inconsistently with node-validator?

I would be open to a PR for this (with tests).

**Comment by ikokostya** [comment]
Example for [express-validator](https://github.com/ctavan/express-validator)

```js
var express = require('express');
var expressValidator = require('express-validator');

var app = express();

app.use(expressValidator({
    customValidators: {
        isFoo: function (value) {
            return value.split(',').length === 2;
        }
    }
}));

app.get('/', function (req, res) {
    req.checkQuery('x').isFoo();
});

app.listen(8000);
```

Request to `http://localhost:8000/` failed with traceback

```
TypeError: Cannot read property 'split' of undefined
    at Object.app.use.expressValidator.customValidators.isFoo (/home/kostya/test/app.js:11:25)
    at ValidatorChain.isFoo (/home/kostya/test/node_modules/express-validator/lib/express_validator.js:186:41)
    at /home/kostya/test/app.js:17:25
    at Layer.handle [as handle_request] (/home/kostya/test/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/kostya/test/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/home/kostya/test/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/kostya/test/node_modules/express/lib/router/layer.js:95:5)
    at /home/kostya/test/node_modules/express/lib/router/index.js:277:22
    at Function.process_params (/home/kostya/test/node_modules/express/lib/router/index.js:330:12)
    at next (/home/kostya/test/node_modules/express/lib/router/index.js:271:10)
```

Example for [validator.js](https://github.com/chriso/validator.js)

```js
var validator = require('validator');

validator.extend('isFoo', function (value) {
    return value.split(',').length === 2;
});

var query = {};
console.log(validator.isFoo(query.x));
```

```
[kostya@arch test]$ node validator-test.js 
false
```

**Comment by rustybailey** [comment]
I was thinking of changing this line (https://github.com/ctavan/express-validator/blob/master/lib/express_validator.js#L183) to `args.push(validator.toString(this.value));` which would use `validator.toString()` on the first argument regardless of whether it was a custom validator or not. Can you think of any drawbacks to this? Do we need to only do this for custom ones?

**Comment by ikokostya** [comment]
> Can you think of any drawbacks to this?

Only one: 2 calls of `validator.toString()` for builtin validators https://github.com/chriso/validator.js/blob/master/validator.js#L104-L106

**Comment by rustybailey** [comment]
Good find. I guess if it's too much of a concern, we could pass a third param into `makeValidator()` called `isCustom` and based on whether it is custom, we will use `validator.toString()` on it. So it's calling a function twice vs adding a param to a function. As much as I hate it, the latter is probably the more responsible way to do it. Thoughts?

**Comment by rustybailey** [comment]
When I was just about to fix it, I ran into another issue (which may or may not be an actual issue). If we went ahead and stringified custom validator arguments, we may break people's assumptions that these will not be strings. For example, these two tests (https://github.com/ctavan/express-validator/blob/master/test/checkBodyTest.js#L95-L97 & https://github.com/ctavan/express-validator/blob/master/test/checkBodyTest.js#L111-L113) for checkBody will fail because in our test suite we are setting up a custom validator called `isArray` which simply uses the native `Array.isArray()` which would fail on strings.

So I guess the question is this: **Is this actually an issue? Are all requests stringified through express?**
1. If this is not an issue, we should we just fix our test suite.
2. If this is an issue:
  1. Do we leave it the way it is so we do not break people's assumptions on what the value will be?
  2. Do we make the change so that the undefined bug doesn't occur and bump the major version?

**Comment by ikokostya** [comment]
I missed that value can be array or object after query string or body parser. In this case I think this is not an issue.

**Comment by rustybailey** [comment]
Are you thinking that the original "bug" reported is not an issue? If so, I kind of agree since users can just account for the existence of the value in their custom validator.

**Comment by ikokostya** [comment]
> Are you thinking that the original "bug" reported is not an issue?

Yes.
