### ISSUE TITLE
Docs: Clarify that validationErrors(true) only gives the last error in a chain of validations

### ISSUE THREAD

**Issue by superclarkk** [ctavan/express-validator#161]
As per #102, clarify in the docs that mappedErrors only provides the last error in a chain of validation errors. On the other hand, the benefit of mappedErrors is that it makes the view template simpler.

Thus, the [Validation Errors](https://github.com/ctavan/express-validator#validation-errors) code won't work for mappedErrors:

~~~
var mappedErrors = req.validationErrors(true);
req.assert('email', 'Invalid email')
    .notEmpty().withMessage('Email is required')
    .isEmail();
~~~
This is because, if the field is left blank, only the default message of "Invalid email" rather than "Email is required" will be stored.Thus, `.notEmpty()` should be called last.

A cleaner way of coding this anyway would be:
~~~
var mappedErrors = req.validationErrors(true);
req.assert('email')
    .isEmail().withMessage('Invalid email format')
    .notEmpty().withMessage('Email is required');
~~~

**Comment by rustybailey** [comment]
Good suggestion. I would be up for a PR for this.
