### ISSUE TITLE
Custom Validator always fails

### ISSUE THREAD

**Issue by superclarkk** [ctavan/express-validator#162]
I'm having a problem with a custom validator. I can't fix it, but I'm not sure if it's a bug. Apologies in advance if it isn't.

This is the code:
~~~
app.use(expressValidator({
	customValidators: {
		isUserExistsByUsername: function(value){
			db.user.findOne({ where: { username: value } })
				.then(function (user){
					var test = false;
					if(!user) {
						test = true; // validation paases - there is no user with this username
					} else {
						test = false;
					}
					console.log('test = ' + test); // this always outputs the correct value
					return test;
				})
				.error(function(err){
					next(err);
				});
		}
	}
}));
~~~
~~~
req.check('username')
	.isUserExistsByUsername().withMessage('Username already exists. Try something different')
	.notEmpty().withMessage('Required field. Please enter your username');
~~~

Regardless of whether the value should pass the validator or not, `isValid` of the library's `makeValidator` function in `express_validator.js` is always set to undefined for my custom validator:

~~~
var isValid = container[methodName].apply(container, args);
~~~

**Comment by rustybailey** [comment]
Right now there is not a great way to do asynchronous custom validators. Duplicate of https://github.com/ctavan/express-validator/issues/122

**Comment by superclarkk** [comment]
Thanks for the response.
The solution to this was to catch the duplicate key/index exception generated when inserting to the database.
