### ISSUE TITLE
errorFormatter is not working after upgrading to the latest version. 

### ISSUE THREAD

**Issue by vivekg342** [ctavan/express-validator#167]
The following code was working fine with 0.14.2. 
It is supposed to return the key of the last child. 
After upgrading to the latest version it is not working as expected.
Am I missing something ?

```
//app.js
var expressValidator = require('express-validator');
var expressValidator = require('express-validator');
app.use(expressValidator({
  errorFormatter: require('./lib/errorFormatter')
}));

// lib/errorFormatter.js
"use strict";

module.exports = function(param, msg, value) {
  param = param.length && typeof param !== 'string' ? param[param.length-1] : param;
  var json = {};
  json[param] = msg;
  return json;
};

```

**Comment by rustybailey** [comment]
Did you mean v2.14.2? I just want to make sure I'm investigating the right version.

**Comment by rustybailey** [comment]
Without digging into it, my guess it that you wrote that code while there was a bug in place, so you worked around that bug. Essentially, the param for an errorFormatter should always be a string. For a few versions (v2.12.0 - v2.17.0) it was returning an array if you used the array syntax to test nested parameters, which was a bug. It now returns your intended param so you should be able to just say:

```
module.exports = function(param, msg, value) {
  var json = {};
  json[param] = msg;
  return json;
};
```

Let me know if that helps.
