### ISSUE TITLE
Feature Request: Get subset of request data filtered by validation rules

### ISSUE THREAD

**Issue by slavafomin** [ctavan/express-validator#168]
Hello!

Thank you for this great module. However, I'm looking for a way to get a subset of request data filtered by validation rules.

I will give a small example:

``` javascript

/** Imagine that this is the request body.
{
  firstName: 'Slava',
  lastName: 'Fomin',
  email: 's.fomin@betsol.ru',
  password: 'some-pass-here',
  someExtra: 'foo'
}
*/

// I'm using this map to specify validation rules for the request.
req.checkBody({
  firstName: {},
  lastName: {},
  email: {
    notEmpty: {
      errorMessage: 'Missing E-Mail'
    },
    isEmail: {
      errorMessage: 'Incorrect E-Mail address'
    }
  }
});

var errors = req.validationErrors(true);
if (errors) {
  return res.json(400, {
    errors: errors
  });
}

var requestParams = req.getValidatedBody();

// We are getting only parameters specified during the validation phase,
// the extra request parameters, like "password", are ignored.
console.log(requestParams);

/**
{
  firstName: 'Slava',
  lastName: 'Fomin',
  email: 's.fomin@betsol.ru'
}
*/

```

That way I will be able to use the entire object without the fear of overwriting some protected property later on (e.g. when updating user entity).

**Comment by slavafomin** [comment]
In the example above I could use `lodash` to solve this problem pretty easily:

`var requestParams = _.pick(req.body, _.keys(validationMap));`

However, when validation rules are not defined via single validation map it gets complicated cause we need to dive into internals of the validation module.

**Comment by rustybailey** [comment]
Would you be able to give me a use-case where a user would provide a large body object, but you only need the items you validated? This seems very specific and I'm not sure it would be beneficial for everyone else. Seems like you could just explicitly grab those properties from the req object to form a new one.

**Comment by gustavohenke** [comment]
Closing this because, as @rustybailey stated, this is indeed very specific and nobody else upvoted this feature.

**Comment by slavafomin** [comment]
The problem is that it opens a door for security vulnerabilities.

If you naively do something like: `_.extend(user, req.body)` you could overwrite some properties you don't want to, e.g. password.

I don't think it's some specific rare use case, on contrary I think that every user of the validator should use this functionality. It will make code much cleaner and secure and will force you to validate all request parameters explicitly. It's a good thing.

**Comment by parmap** [comment]
Agree, it's simple, but common attack.

https://www.owasp.org/index.php/Mass_Assignment_Cheat_Sheet#NodeJS_.2B_Mongoose

Here is one solution, but I would rather have it inside express-validator.

**Comment by slavafomin** [comment]
@gustavohenke reopen?

**Comment by gustavohenke** [comment]
I understand this problem.
But take as example GitHub's new issue form:
![](http://i.imgur.com/4lakHZB.png)

The following fields are always available:
- Title: required
- Comment: no validation. Anything is accepted and will be stored.

When the validation passes, then you'll receive in the issue data the title, okay. But what about the comment? You'll need to resort to something else to pick the comment.

**Comment by parmap** [comment]
Ok, but Imagine, that you have request [POST] with 5 params for user registration. When you validate request, you need to pass it to model and store. What will you do, create manually (in code) object, where you put params from request? Or you will take only what you validated (via function) and get as object. 

It depends on context and usage, we don't say, that you will use it on every end-point, but it's nice functionality of nice library, which is handful.

**Comment by slavafomin** [comment]
@gustavohenke when validating by schema, we can add comment field without specifying any validation rules, so it can still be picked.

When validating using builder pattern, we can also omit the validators, e.g:

`req.checkBody('comment');` or even better: `req.checkBody('comment').optional();`

I think it pretty useful and clear API for the library.

**Comment by gustavohenke** [comment]
Well... then let's do it!

**Comment by gustavohenke** [comment]
Hello folks! [v4.0.0 has finally been released](https://github.com/ctavan/express-validator/releases/tag/v4.0.0)!

You can now get the subset of data matched by any validations by using the new APIs `check` and `filter`:

```js
const { check, validationResult } = require('express-validator/check');
const { matchedData } = require('express-validator/filter');

app.post('/', [
  check('username').isLength({ min: 1 }).isEmail(),
  check('password').isLength({ min: 1 })
], (req, res, next) => {
  // data will only contain valid validated data by default
  const data = matchedData(req);

  // you can also get all validated data, even the invalid ones:
  const data = matchedData(req, { onlyValidData: false });
});
```

Please check the README for complete docs, and also check the [upgrade guide](https://github.com/ctavan/express-validator/blob/v4.0.0/UPGRADE_GUIDE.md).
