### ISSUE TITLE
Feature Request: Specify default error message for custom validator/sanitizer

### ISSUE THREAD

**Issue by slavafomin** [ctavan/express-validator#169]
Hello!

I would like to be able to specify a default error message for custom validators and sanitizers. For example I would like to define a `password` custom validator in a single place of my application and use it later on in different places, e.g. when creating users, when changing password, when logging in, etc. It would be great if an error message could also be defined in a single place. If my error message looks like `"Password must contain at least 8 characters"` and I will decide to change validation rules from 8 chars to 12 I will have to change error message in every place of my app, which violates DRY principle.

# Suggested API:

```javascript
var validator = require('validator');
var minLength = 8;
expressValidator({
  customValidators: {
    password: {
      validator: function (value) {
        return validator.isLength(value, minLength);
      },
      errorMessage: 'Password must contain at least ' + minLength + ' characters'
    }
  }
});
```

Or maybe even like this:

```javascript
var validator = require('validator');
var minLength = 8;
expressValidator({
  customValidators: {
    password: function (value, cb) {
      var result = validator.isLength(value, minLength);
      if (result) {
        cb(null, true);
      } else {
        cb('Password must contain at least ' + minLength + ' characters', false);
      }
    } 
  }
});
```

That way we will be able to change error message dynamically according to validation logic. We can replace async callback with result object if required:

```javascript
// On success
return {
  result: true
};

// On failure
return {
  result: false,
  message: 'Password must contain at least ' + minLength + ' characters'
};
```

What do you think?

**Comment by rustybailey** [comment]
I'll leave this issue open in case anyone wants to tackle it, but this is not a critical feature, so I would prefer that any solutions do not break existing code.

In the short term, however, I would suggest having a file with your validation messages (or just a general "constants" file) and `require` that in, so that you only have to change the message in one place instead of every API method. This will help you attain your goal of keeping your code DRY.

**Comment by srkimir** [comment]
As @rustybailey suggested you can easily keep your code DRY with putting all your validation messages in single module such as

```
// constants.js
module.exports = {
  ...,
  ERROR_MESSAGES: {
    PASSWORD_MIN_LENGTH: 'Password must contain at least 8 characters'
    ...
  },
  ...
}
```
Will close this issue
