### ISSUE TITLE
Oh... I found small bug

### ISSUE THREAD

**Issue by boris-42** [ctavan/express-validator#17]
For example If you have form: 
````html
<form ...>
 <input type="text" name="email"/> 
 <input type="text" name="email"/>
 ... 
 <input type="submit"/>
</form>
````
And then try to make on server

req.assert("email", "Invalid email" ).notNull().isEmail();

throws error =)

Something like this:
TypeError: Object boris@pavlovic.me,test, has no method 'match'

So ten year old "hacker" with `curl` can easy drop my web site using such things=)

**Comment by rustybailey** [comment]
Closing as this conversation was going nowhere and no has responded since 2013.
