### ISSUE TITLE
Code error in "Validation by Schema" section

### ISSUE THREAD

**Issue by 0q0** [ctavan/express-validator#170]
It looks like missing an open brace after "isEmail:" ?

```javascript
req.checkBody({
 'email': {
  notEmpty: true,
    isEmail:
      errorMessage: 'Invalid Email'
    }
  },
  ...
});
```

And I have a question: if I don't want to pass any options (including 'errorMessage') to "isEmail" valdatior, does that should be set as "isEmail: true" in schema?

**Comment by rustybailey** [comment]
You are correct that there should be an open brace where you indicated. Also, yes, you should be able to just say isEmail: true. 

Unless someone else wants to fix this typo in the docs, I'll just throw it into the next update.

**Comment by 0q0** [comment]
Thanks for the response :)
