### ISSUE TITLE
Optional validation

### ISSUE THREAD

**Issue by MSTWNTD1** [ctavan/express-validator#171]
Hello, I have a question:

How do I validate an input that is not required but it does have to meet certain rule if a user actually fills the input?

Example:

An input type email that is not required but if you do type your email it has to be a valid one.

Doing something like:

req.checkBody('email').isEmail() is asking to provide a valid emaill address, but that's the thing, the input is optional.

I read in the documentation about the optional input that checks an input when it exists, and the thing is that when I submit the form the input type email does exist, but I want it to be optional.

Thanks in advance.

**Comment by rustybailey** [comment]
The optional() method should be what you're looking for. You can do req.checkBody('email').optional().isEmail() and if 'email' doesn't exist, it won't try to validate it. However, if the key does exist (even if it equals null), it will try to validate whether it isEmail. 

Let me know if that works for you.

**Comment by imShara** [comment]
But what if it in schema? There is no order as i know.

**Comment by gustavohenke** [comment]
Hi @imShara, rest assured that order is not important when using `optional` nowadays.
