### ISSUE TITLE
Async sanitizers

### ISSUE THREAD

**Issue by fogine** [ctavan/express-validator#175]
Hello,

thank you for very helpful package!
I would like to propose for asynchronous sanitizers support, would it be possible?

Thanks.

**Comment by rustybailey** [comment]
Can you outline the need for/benefit of sanitizing asynchronously?

**Comment by fogine** [comment]
I would use it for loading content from db for specific types of arguments.
Eg. if an argument user="1" is present in POST request, I would load the user from database and replace the user argument value with User model.

Although I see potential problem here with naming convention and such when an argument would be named like "user_id". I don't think I'd want to sanitize an user_id with user object.

**Comment by rustybailey** [comment]
If you're simply replacing a value, I don't know if sanitizers are what you need. Could you just do that with vanilla JS?

**Comment by fogine** [comment]
Of Course I could do it another way. I understand that sanitizers are not supposed to replace a value entirely. It's just an idea on a possible feature...

**Comment by rustybailey** [comment]
I appreciate the suggestion, but I think this is simply doesn't fit within the feature set of express-validator. Thanks.
