### ISSUE TITLE
Validate length match of 2 properties of the request

### ISSUE THREAD

**Issue by tuananh** [ctavan/express-validator#176]
i have a request like this

    request = {
        arrayOne: [...],
        arrayTwo: [...]
    }

Is it possible to validate that `arrayOne` and `arrayTwo` are of same length?

**Comment by rustybailey** [comment]
You could try a custom validator:
``` js
  app.use(expressValidator({
    customValidators: {
      isSameLength: function(value, comparisonVal) {
        return JSON.parse(value).length === JSON.parse(comparisonVal).length;
      }
    }
  }));
```

and then in your route:
``` js
req.checkBody('arrayOne').isSameLength(req.body.arrayTwo);
```

Let me know if that works. If not, post what errors you're getting.

**Comment by tuananh** [comment]
@rustybailey thanks. it works.
