### ISSUE TITLE
Any way to do required with?

### ISSUE THREAD

**Issue by jamesaspence** [ctavan/express-validator#179]
I'm looking for a way to require an input if another input has been required.

i.e., a `followUpNeeded` parameter that is optional. However, if it's selected, they need to specify a `followUpAt` parameter.

Does such functionality exist?

**Comment by rustybailey** [comment]
Not really, but you could wrap it in an existence check or do a custom validator.
Easy way:
``` js
if (req.body.followUpNeeded) { // or req.query/req.params
  req.assert('followUpAt').notEmpty();
}
```

**Comment by jamesaspence** [comment]
I will do that. Thanks!
