### ISSUE TITLE
optional parameter validating on empty string

### ISSUE THREAD

**Issue by jamesaspence** [ctavan/express-validator#181]
I have some validation that looks like this:

    req.checkBody('orderNum', 'An Order ID needs to be an integer.')
        .isInt().withMessage('Order ID must be an integer.')
        .optional();

The problem is, my form submits orderNum as an empty string when it's not filled (due to using serialize). That triggers the validation error of `Order ID must be an integer`.

Not sure if this is a bug or if I'm doing something wrong.

**Comment by rustybailey** [comment]
Right now the `optional()` check only skips validation if the key does not exist at all. Related to https://github.com/ctavan/express-validator/issues/120
