### ISSUE TITLE
How to call sanitizers with extra arguments?

### ISSUE THREAD

**Issue by slavafomin** [ctavan/express-validator#182]
Hello!

There are no examples of using sanitizers with extra parameters in the docs, e.g.: `blacklist`.

Question: What is the proper way to call them?
Feature Request: Please update the docs accordingly.

Thank you!

**Comment by rustybailey** [comment]
You should be able to just call `req.sanitize('postparam').blacklist(options);` (same as you would with the validators). Let me know if this doesn't work.

I'll make a note in the docs.

**Comment by rustybailey** [comment]
These docs are added in v2.18.0.

**Comment by slavafomin** [comment]
That's cool, thank you!

However, are you sure `blacklist` accepts array of characters and not a string, e.g. `'abc'`?

**Comment by rustybailey** [comment]
It takes whatever is specified in the node validator's documentation: https://github.com/chriso/validator.js/blob/master/README.md

Thanks,
Rusty Bailey
