### ISSUE TITLE
Better name would have been connect-validator

### ISSUE THREAD

**Issue by ksachdeva** [ctavan/express-validator#184]
Hi ctavan,

Thanks for this great effort. I am using restify for my project and after looking at your code I can not see any dependency on express framework.

Just for the semantics of things it would have been great if your repository / module would have been called connect-validator as including it in my restify project would look odd.

Regards
Kapil

**Comment by rustybailey** [comment]
I appreciate the feedback, but this module is 4+ years old, so we don't plan on changing the name.
