### ISSUE TITLE
Include param type in the error object

### ISSUE THREAD

**Issue by jstayton** [ctavan/express-validator#185]
Hey there,

I can think of a few cases where having access to the type of param in the error object would be useful. For example, I'm dynamically building an error message using the existing error object values:

``` javascript
'`' + error.param + '` ' + error.msg + ' (received `' + error.value + '`)'
```

Which produces something like:

```
`person_id` must be an ID (v4 UUID) (received `12345`)
```

By including the type of param, the error message could be even more helpful:

```
`person_id` (query) must be an ID (v4 UUID) (received `12345`)
```

So the types would be something like `body`, `params`, `query`, `headers`.

Obviously not too critical, but I do think it would be a useful improvement. Thanks!

**Comment by rustybailey** [comment]
Thanks for the suggestion! We're always open for PRs.

**Comment by gustavohenke** [comment]
Hello folks! [v4.0.0 has finally been released](https://github.com/ctavan/express-validator/releases/tag/v4.0.0)!

All errors generated by the `check` APIs will include a `location` key, which will be one of `body`, `params`, `query`, `cookies` or `headers` 😉 

Please check the README for complete docs, and also check the [upgrade guide](https://github.com/ctavan/express-validator/blob/v4.0.0/UPGRADE_GUIDE.md).
