### ISSUE TITLE
Options do not work in isInt

### ISSUE THREAD

**Issue by kolima** [ctavan/express-validator#187]
Options do not work in isInt

from validation.js:
isInt(str [, options]) - check if the string is an integer. options is an object which can contain the keys min and/or max to check the integer is within boundaries (e.g. { min: 10, max: 99 }).

**Comment by kolima** [comment]
Need to pass options how array

**Comment by marcoasp** [comment]
Could you provide an example, facing the same problem here?

**Comment by IOAyman** [comment]
@marcoasp `.isInt( [ {min: 1} ] )`

**Comment by marcoasp** [comment]
I am trying to use 

```
req.check('amountOfWork', 'Invalid Amount of Work')
      .isInt([{gt:0, lt:remainingAmountOfWork + 1}]).withMessage('Amount of Work must be between 0 and ' + remainingAmountOfWork)
      .notEmpty().withMessage('Amount of Work is required');
```

But when I pass -1 or a value greater than the validation it returns no errors

**Comment by IOAyman** [comment]
@marcoasp Sorry, my bad! I was mistaken. You should not pass the `options` in an array. I've just tested it.
```js
.isInt({ gt: 0, lt: 10 })
```

**Comment by gustavohenke** [comment]
> You should not pass the options in an array.

Yeah, you probably confused with schema validation 😉

**Comment by marcoasp** [comment]
Sorry, but the problem persists in both ways.

This is the link of the complete file: 
https://github.com/marcoasp/trackyourself/blob/master/app/app_server/controllers/progress.js

**Comment by gustavohenke** [comment]
According to validator.js docs, you should be using `min` and `max` instead of `lt`/`gt`

**Comment by marcoasp** [comment]
@gustavohenke min and max works like less than or equals and greater than or equals. I need something that doesn't consider the equals part

**Comment by IOAyman** [comment]
> you probably confused with schema validation

@gustavohenke Exactly I use schema validation most of the times, it got me confused 😉 

@marcoasp Your code looks normal. Just remove the array surrounding `options`. Maybe you've got something wrong with the logic 😕 
If you want to use min/max, you could do `{ min: 1, max: remainingAmountOfWork }`

**Comment by marcoasp** [comment]
@IOAyman I am trying to use schema validation, the same occurs. No error validation for the input.
```

req.checkBody({
    'amountOfWork': {
      isInt: {
        options: [{gt: 0, lt: 50}],
        errorMessage: "Amount of work must be between 0 and 50"
      }
    }
  });
```

**Comment by IOAyman** [comment]
@marcoasp I think the issue might be in your code, so try to debug that 😕 (I've just tested a similar example with the latest version, it runs perfectly).

And keep in mind:

If you want to _**chain your validations**_ then you should **_pass the options object to `.isInt()` directly_**.

But if you want to use the _**schema validation**_, you should **_wrap the options object in an array_**.

You could also do `{ gt: 0, max: remainingAmountOfWork }`, which I think is a little more intuitive.

**Comment by Fundebug** [comment]
@marcoasp @IOAyman According to my test, both methods are OK, the array is not necessary

```js
 isInt: {
        options: [{
            min: 60,
            max: 3600
        }]
    }
```

```js
 isInt: {
         options: {
             min: 60,
             max: 3600
         }
     }
```

I'm using express-validator 5.3.1
