### ISSUE TITLE
withMessage is not a function

### ISSUE THREAD

**Issue by tuananh** [ctavan/express-validator#189]
req.checkBody('param','default message')
	    .optional().notEmpty().withMessage('blah blah blah')
	    .isInt().withMessage('blah blah')

I'm getting 

    req.checkBody(...).notEmpty(...).withMessage is not a function

Can someone help me figure this out?

**Comment by rustybailey** [comment]
What version of `express-validator` are you using?

**Comment by tuananh** [comment]
@rustybailey sorry. my bad. i was using an old version of `express-validator`
