### ISSUE TITLE
Schema with isIn validation

### ISSUE THREAD

**Issue by JaniszM** [ctavan/express-validator#192]
How to validate query/body/header using isIn() in the schema? I tried something like this:

    'digit': {
        notEmpty: true,
        isIn: {
            options: ['one', 'two', 'zero'],
            errorMessage: 'no enum.'
        },
        errorMessage: 'Missing digit.'
    }

**Comment by rustybailey** [comment]
Try `options: [['one', 'two', 'zero']],`

The options array is for passing each param. Since `isIn()` expects an array as its parameter, you need to put that array in an array. Confusing, I know, but that should work.

**Comment by JaniszM** [comment]
Looks it works, thanks :)

**Comment by dmwelch** [comment]
Could the README/docs be updated, @JaniszM ?
