### ISSUE TITLE
optional({ default: 'defaultValue' })

### ISSUE THREAD

**Issue by aristidesfl** [ctavan/express-validator#195]
Add an option to optional() which allows a default value to be specified in case the key does not exist.

**Comment by rustybailey** [comment]
Can you be more specific?

**Comment by aristidesfl** [comment]
Set a field as optional, and if the field doesn't exist, replace it with a default value. Maybe this should be implemented in a separate sanitizer instead?

**Comment by rustybailey** [comment]
Yeah, I'm thinking a sanitizer is the solution here. Don't want optional to do more than what's intended.

Can this be closed?
