### ISSUE TITLE
oneOf/anyOf

### ISSUE THREAD

**Issue by JaniszM** [ctavan/express-validator#200]
Is it possible to check somehow the group of params? E.g.: I have three query params on input: one, two, three, and I want to check if one of them is present. Im using schema validation.

It looks like a problem because schemas are referencing always to the specific fields :~

```
    'limit': {
        optional: true,
        isInt: {
            errorMessage: 'Invalid argument type.'
        }
    },
    'offset': {
        optional: true,
        isInt: {
            errorMessage: 'Invalid argument type.'
        }
    }
```

**Comment by gustavohenke** [comment]
Can you clarify your issue, please?

**Comment by JaniszM** [comment]
It was so long ago I don't remember exact example. But as I wrote, I want to check few fields at once like 'oneOf' or 'anyOf' property in the json schema.

**Comment by agauniyal** [comment]
probably wanted something like if out of 4 parameters, 3 must always be present while 4th is optional. If user sends only 2 or a 3rd one that was optional, it's an error.

**Comment by gustavohenke** [comment]
@agauniyal you can already do this.
These 3 fields are always required, and make the 4th one optional. If one of these 3 fields are not sent, then the request should fail.

**Comment by maZahaca** [comment]
Is there an option to check several fields of request, the whole request?
For example, my api receive a request from transfer money tool, which has parameters:
```js
{
   "fromAccount":"100001",
   "toAccount":"100001",
   "amount":2344.23,
}
```
So we validated each parameter in separate way, but we also need to check that fromAccount !== toAccount somehow.

**Comment by gustavohenke** [comment]
> we also need to check that fromAccount !== toAccount somehow.

For now, this is only possible if you create a custom validator that checks the values directly, eg `req.checkBody('toAccount').notEquals(req.fromAccount)`.

We even have the `equals` validation built-in, but not its negation.
See also #294

**Comment by maZahaca** [comment]
@gustavohenke this is just a common example, but usually I need to do a bit complicated validation of the whole request. It would be perfect to have this feature

**Comment by maZahaca** [comment]
Btw, is it possible to do what you suggested but in a schema validation: to have an access to the different request paean to compare with it

**Comment by gustavohenke** [comment]
@maZahaca like #298 intends to do?

**Comment by gustavohenke** [comment]
Hello folks! [v4.0.0 has finally been released](https://github.com/ctavan/express-validator/releases/tag/v4.0.0)!

You can now check if at least one of the validator chains is valid by using the new `oneOf` function in the `check` API collection:

```js
const { check, oneOf, validationResult } = require('express-validator/check');
app.get('/', oneOf([
  check('a').exists(),
  check('b').exists(),
  check('c').exists()
], 'you must provide at least a, b or c'), (req, res, next) => {
  const result = validationResult(req);
  // do something with the validation result!
});
```

Please check the README for complete docs, and also check the [upgrade guide](https://github.com/ctavan/express-validator/blob/v4.0.0/UPGRADE_GUIDE.md).
