### ISSUE TITLE
Write a CONTRIBUTING.md

### ISSUE THREAD

**Issue by rustybailey** [ctavan/express-validator#207]

**Comment by gustavohenke** [comment]
What are your ideas?
I usually see around people contemplating mainly PRs with tests and clear docs.

**Comment by rustybailey** [comment]
I dunno. Just a general thing like:
* Here's a general link on how to contribute on Github
* If don't any have ideas, but would like to improve the repo, feel free to browse the issues for bugs/feature ideas.
* Whenever you submit a new PR, it must have tests, and if it's a new feature or functionality has changed, the README must reflect that.
* Make sure your build passes. If it doesn't, click through, find out why, and fix it.
