### ISSUE TITLE
escape additions

### ISSUE THREAD

**Issue by bilbolovespotter** [ctavan/express-validator#211]
Hi guys,

I think we should escape a few more dangerous characters for SQL and Javascript.

These two:

'
\

' is dangerous in sql and javascript and \ is too.
```

express-validator/node_modules/validator/lib/filter.js
@@ -64,6 +64,7 @@ Filter.prototype.trim = function(chars) {
 Filter.prototype.escape = function() {
     this.modify(this.str.replace(/&/g, '&amp;')
                         .replace(/"/g, '&quot;')
+                        .replace(/'/g, '&#39;')
+                        .replace(/\\/g, '&#5C;')

```

**Comment by rustybailey** [comment]
This has to do with the validator library that we are built on top of. You'll need to open an issue there: https://github.com/chriso/validator.js

**Comment by bilbolovespotter** [comment]
Thanks!
