### ISSUE TITLE
throw custom error in asyncValidationErrors

### ISSUE THREAD

**Issue by Maxim-Chugaev** [ctavan/express-validator#213]
Bluebird api 

> This is an extension to .catch to work more like catch-clauses in languages like Java or C#. Instead of manually checking instanceof or .name === "SomeError"

example

```
 req.asyncValidationErrors()
      .then -> User.create req.body
      .then -> res.redirect '/users'
      .catch expressValidator.ValidationError, (e)->
         res.render 'users/create', errors: e.errors, values: req.body

```

Please, add this trick into package :)

**Comment by cbovis** [comment]
This will be somewhat unnecessary once PR #169 has been released since errors will be returned as part of the promise resolution instead of the promise rejection.

**Comment by gustavohenke** [comment]
As we changed the API a lot in v3.0.0, this is probably doable now.

**Comment by gustavohenke** [comment]
@cbovis was right anyway. This feels unnecessary since you can just get the validation result, both v3 API and the new v4 APIs.
