### ISSUE TITLE
Outdated dependencies

### ISSUE THREAD

**Issue by AuspeXeu** [ctavan/express-validator#214]
https://david-dm.org/ctavan/express-validator

**Comment by rustybailey** [comment]
I went ahead and updated lodash. However Bluebird and validator will need some code changes and a major version upgrade.

* For Bluebird we'll be upgrading from v2 to v3.
    * I think only change that affects us is that `settle()` is deprecated: http://bluebirdjs.com/docs/new-in-bluebird-3.html#deprecations
    * We're using settle here: https://github.com/ctavan/express-validator/blob/master/lib/express_validator.js#L177
* Validator is the big one. When they upgraded to v5, they removed automatic non-string coercion: https://github.com/chriso/validator.js/pull/496
    * This breaks a large majority of our tests: https://travis-ci.org/ctavan/express-validator/jobs/115613461
    * This likely breaks code in the wild too, so upgrading this module will also require a major version upgrade on our end.

I'm always up for PRs. :smile:

**Comment by rustybailey** [comment]
Bluebird has been upgraded to v3.3.x in express-validator v2.20.2.

**Comment by rustybailey** [comment]
Our current version of validator (4.9.x) will cause the code to output this error:

`validator deprecated you tried to validate a undefined but this library (validator.js) validates strings only. Please update your code as this will be an error soon. node_modules/express-validator/lib/express_validator.js:335:41`

You can also see various instances of this error when you run our tests (`npm test`).

While it doesn't break anything, it is annoying to users, and makes this upgrade to v5 a little higher priority.

**Comment by rustybailey** [comment]
Validator updated to v5 here: https://github.com/ctavan/express-validator/pull/231
Now in 2.20.4
