### ISSUE TITLE
Question: Format of errorFormatter

### ISSUE THREAD

**Issue by ath88** [ctavan/express-validator#218]
On the custom errorFormatter, the documentation writes;

>  It should return an Object that has param, msg, and value keys defined.

I don't see why this is a requirement. Can anyone elaborate? # # @

**Comment by rustybailey** [comment]
I've poked around in the code and I'm honestly not sure. Maybe it was just to keep the Object consistent with the default output... but it seems that would defeat the purpose of having control over the format of the error. In any case, it doesn't seem like there is any code-related reason to require returning the error in that format unless I missed something.

@ctavan Can you weigh in on this?

**Comment by gustavohenke** [comment]
I checked the code, and `param` and `value` are indeed used, but `msg` is not.

They are mainly used to keep track of what the last error was (so you can configure its message via `.withMessage()`.
`param` is specially important to make mapped errors work properly, even more after #285.

**Comment by gustavohenke** [comment]
I'll close here, but in case anyone has doubts regarding the format of errorFormatter, feel free to comment!

**Comment by Jakkc** [comment]
I would like to be able to have the errorFormatter return an Object with keys referring to the form element and a value of an object with the message and other information.

This would allow me to individually access the error information in my view template without having to output all the items in a loop.

Currently having to drop all the errors at the foot of the form, would look much more visually appeasing if the errors were in proximity of the input they reference.

**Comment by gustavohenke** [comment]
Use [`result.mapped()`](https://github.com/ctavan/express-validator#resultmapped).
