### ISSUE TITLE
Additional check required if the field is missing

### ISSUE THREAD

**Issue by m-garg** [ctavan/express-validator#219]
When the req does not contain the required field parameter. 'validator' module shows the following warning:
`validator deprecated you tried to validate a undefined but this library (validator.js) validates strings only. Please update your code as this will be an error soon. node_modules/express-validator/lib/express_validator.js:335:41` 

For eg. if I write 
`req.checkBody('name', 'Invalid project name').notEmpty();`
and the 'name' field is not passed in the req body, the above warning will appear.
I think express-validator should first check whether the field is available or not, and only then pass it for further verification.

**Comment by rustybailey** [comment]
Is anything breaking or are you just getting an annoying warning? If everything still works right now, we plan on upgrading to validator v5 at some point (https://github.com/ctavan/express-validator/issues/214) and fixing this error in that ticket.

**Comment by m-garg** [comment]
Only warning, nothing breaking as of now.

**Comment by rustybailey** [comment]
Sounds good. Closing this ticket then in favor of the upgrade ticket.
