### ISSUE TITLE
Optional validate method may not be applied when using a schema.

### ISSUE THREAD

**Issue by meddy** [ctavan/express-validator#222]
The validateSchema function iterates over a param object's keys when using a schema. If you have rules that come before optional they will be used before it can be determined that validation should be skipped because you specified optional in your schema.

This will only work if you make sure to specify optional first in your schema object literal, but because JavaScript does not guarantee object property order, this only happens to work because of the behavior of V8 where properties tend to come out in the same order they were put in.

I think it might make sense to check for optional before iterating through a param config's properties.

**Comment by rustybailey** [comment]
Thanks for pointing this out! Not sure how soon I can get to this, but we are always open to PRs.

**Comment by srkimir** [comment]
@meddy @rustybailey 
The very first idea how it can be solved is that we could check for `schema[param].optional` before running other validation methods, something like:

```
function validateSchema(schema, req, loc, options) {
  ...
  var validator = new ValidatorChain(param, null, req, currentLoc, options);
  var paramErrorMessage = schema[param].errorMessage;
    
  if (schema[param].optional) {
    validator.optional(schema[param].optional.options)

    if (validator.skipValidating) {
      continue; // continue with next param in schema
    }
  }

  for (var methodName in schema[param]) {
    if (methodName === 'optional') {
      continue; // because it is already checked
    }
  }
}
```
Will see for other, maybe cleaner ways to do it
