### ISSUE TITLE
No method for validating existence of property in req.params, req.body, or req.query

### ISSUE THREAD

**Issue by fvgs** [ctavan/express-validator#227]
Suppose I have a route expecting to receive the parameter `req.body.heading`. If this parameter exists and was sent by the client, then my validation will run as expected. I will check `req.validationErrors()` and proceed accordingly. However, if `req.body.heading` was not sent by the client, its value will be `undefined`. Based on my limited testing, when this happens, the `undefined` value will be coerced to an empty string and validation will proceed on that empty string. A `validator deprecated` message also gets printed to the console, and I understand this is going to be addressed in the future. However, the problem here is that there is currently no way to check if a value is `undefined` and produce an error when it is `undefined`. Currently, the `undefined` value gets coerced to an empty string and validated as an empty string.

This is problematic because there is a big difference between not receiving a value from the client and receiving an empty string. These constitute independent cases that one may wish to handle differently. In my case, I consider receiving no value (i.e. `undefined`) as an error, whereas receiving an empty string may or may not be valid depending on the context.

My solution has been to create a custom validator to check if the value exists:

``` javascript
customValidators: {
  exists: value => value !== undefined,
}
```

This achieves the desired behavior whereby if the value is `undefined`, an error will be produced in `req.validationErrors()`. In practice, I also use the `optional()` method immediately after `exists()` to stop any further validation when the value is `undefined`.

Typical usage would look something like this:

``` javascript
req.checkBody('heading').exists().optional()...;
```

With that in mind, I'd appreciate some feedback on whether or not this is the best way to address this issue. Likewise, if this makes sense and doesn't conflict with any upgrade plans, I'd like to make a PR to add an `exists()` method. In this PR I would go ahead and bundle the `optional()` behavior into the `exists()` method since using it without that behavior doesn't really make sense. Though I would add an option to allow `exists()` to be used without the `optional()` behavior.

**Comment by srkimir** [comment]
@fvgs thank you on very nice explanation of the problem. Can you please confirm do you still have described problem. As you said: 
> However, the problem here is that there is currently no way to check if a value is undefined and produce an error when it is undefined

So lets say that you want to check `email` field was sent by client, so your validation may look like
```
req.checkBody('email', 'valid email address is required').isEmail()
```
And lets say that request body is empty `{}` so email value is `undefined`, this will produce error like
```
{
  "email": {
    "param": "email",
    "msg": "valid email address is required"
  }
}
```
So it will produce an error if value is `undefined`

**Comment by fvgs** [comment]
@srkimir Based on the commits that have been made since opening this issue, I believe the issue remains as described originally.

The behavior you describe for the `isEmail()` method is consistent with the issue. An `undefined` value will be coerced to an empty string. Thus, `isEmail()` will validate an empty string. Given the nature of its validation, an empty string as its input will produce an error since an empty string is not a valid email address.

The issue I describe is that of `undefined` values (i.e. values not submitted by the user) being coerced to empty strings and validated as such. This canonicalizes an `undefined` value to an empty string even though a user of this package may wish for `undefined` values and empty strings to have different validation behavior.

For instance, one may have a field that, if not submitted, should produce an error, but, if submitted as an empty string, should validate.

**Comment by srkimir** [comment]
@fvgs 
i see your point, we are talking about something like this, right?
```
const EMPTY_STRING = ''
req.checkBody('a', '...').equals(EMPTY_STRING)
```
validation will be successful for empty request body `{}`

**Comment by fvgs** [comment]
@srkimir That's correct.

The reason it's implemented this way in express-validator is, originally, validator.js accepted any input and would coerce a non-string input to a string according to its own guidelines. This changed when the API for validator.js switched to accepting only string inputs. In order to not introduce breaking changes to express-validator, those same guidelines from validator.js were introduced to express-validator so express-validator would comply with the new API for validator.js.

**Comment by gustavohenke** [comment]
Hello folks, [v4.0.0 has finally been released](https://github.com/ctavan/express-validator/releases/tag/v4.0.0).

It brings support for a new validator called `.exists()`, which you can see some example of how to use here: https://github.com/ctavan/express-validator/issues/382#issuecomment-325174919

Don't forget to check [the README for complete docs](https://github.com/ctavan/express-validator/tree/v4.0.0) and the [upgrade guide for version 3 users](https://github.com/ctavan/express-validator/blob/v4.0.0/UPGRADE_GUIDE.md).
