### ISSUE TITLE
How to check if the value is a decimal

### ISSUE THREAD

**Issue by rakesh1988** [ctavan/express-validator#228]
Can you please help me to know if it is possible to check if the value is a decimal or float. 

Also does the validation check accepts regex?

**Comment by rustybailey** [comment]
This middleware uses [node-validator](https://github.com/chriso/validator.js), so you should check there first for existing methods. Looks like there is an `isDecimal()` and `isFloat()` that you could use. Let me know if this helps.

**Comment by srkimir** [comment]
@rakesh1988 as @rustybailey suggested, please check https://github.com/chriso/validator.js
if you can't find what are you looking for there you can always create your custom validator
i will close an issue, please comment if you need any further help with this
