### ISSUE TITLE
README example outdated: bodyParser no longer bundled with express

### ISSUE THREAD

**Issue by olalonde** [ctavan/express-validator#230]
```javascript
> express.bodyParser()
Error: Most middleware (like bodyParser) is no longer bundled with Express and must be installed separately. Please see https://github.com/senchalabs/connect#middleware.
```

**Comment by ugolas** [comment]
install bodyParser:
npm install body-parser

add:
var = bodyParser = require('body-parser');

and use:
app.use(bodyParser.urlencoded({ extended: false }));

instead of:
app.use(express.bodyParser());

**Comment by olalonde** [comment]
I know, thanks... was just pointing out the bug.
