### ISSUE TITLE
Object can escape from being validated

### ISSUE THREAD

**Issue by lovanwubing** [ctavan/express-validator#240]
Hi, I got a case: 

I want to check my body parameter name which should be a string, the code is: 
`req.checkBody({name: {
    notEmpty: true,
    isLength: {
        max: 16
    }
}})`

My data for req.body.name is actually an object like: {test: '111111111111111111111111111111'}.

The validator will use .toString() which equals '[object Object]', so there is no errors.

I think it should be a bug, or there should be a validator to check wheter it's a string or object.

**Comment by srkimir** [comment]
@lovanwubing 
You are not using it in right way, please check https://github.com/ctavan/express-validator#validation-by-schema and following example

```
const schema = {
  'name.test': {
    notEmpty: true,
    isLength: {
      options: [{ max: 16 }]
    },
    errorMessage: 'something up to 16 characters required'
  }
}

req.checkBody(schema)
```

**Comment by srkimir** [comment]
@lovanwubing i will close an issue, please comment if you need any further help
