### ISSUE TITLE
Need new maintainer(s)

### ISSUE THREAD

**Issue by rustybailey** [ctavan/express-validator#241]
A little over a year ago, there was an issue opened requesting a new maintainer for this repo (https://github.com/ctavan/express-validator/issues/124). Since we had just started using this library at the company I was at, I offered to take over. After taking over, I ported the unit tests to Mocha, fixed some bugs, and triaged a ton of issues.

Since then, I've gotten a new job where:
1) I don't have as much time to maintain this.
2) I don't use Node/Express much, if at all, so I don't keep up with changes in Express.js and it takes a lot more time to debug issues.

If anyone to help maintain this repo, it would be much appreciated. There are lots of issues that need looking at and several PRs that need review. If you're interested, feel free to email me at rustylbailey@gmail.com.

cc: @ctavan

**Comment by gustavohenke** [comment]
Hey, so I'm helping out here for over a week, and it seems like I'm the only one who stepped up in months!
Therefore I'll close here if you don't mind, @rustybailey.

**Comment by rustybailey** [comment]
Thanks for everything you've done so far!

**Comment by Hongbo-Miao** [comment]
Glad to see this package be alive again : )
