### ISSUE TITLE
paramErrorMessage will be deleted permanently from schema after first validation if schema is not recreated on every new request

### ISSUE THREAD

**Issue by srkimir** [ctavan/express-validator#242]
In scenario where schema is not recreated on every request `paramErrorMessage` will be permanently deleted from schema. To me it seems perfectly valid scenario to use predefined schemas instead of recreating schemas over and over again on each request. In following example only first ever request will have expected param error message `"msg": "a must be integer greater or equal to 1",` all following requests will return `"msg": "Invalid param"`. This is caused by line number: `343` in https://github.com/ctavan/express-validator/blob/master/lib/express_validator.js. Please check end of answer for proposal how this can easily be solved. **Example:**

_// schemas/index.js_
```
'use strict'

exports.somethingSchema = {
  a: {
    isInt: {
      options: [{ min: 1}]
    },
    errorMessage: 'a must be integer greater or equal to 1'
  }
}
```

_// test.js_
```
const test = (req, res, next) => {
  req.checkBody(schemas.somethingSchema)
  const errors = req.validationErrors()
  
  if (errors) {
    return res.status(422).json({
      type: 'validation-error',
      message: 'Constraint violation',
      errors
    })
  }
  return next()
}

app.post('/something', test, (req, res, next) => {
  res.send('ok')
})
```

_How it can be solved:_ Clearly intention with using `delete` is that `errorMessage` not ends like `methodName` in `for (var methodName in schema[param]) {...}`. Instead `delete` this can be solved in more safer way with `if (methodName === 'in' || methodName === 'errorMessage') { ... continue; }`
One more reason why i would vote against `delete` is that you never know how schema will be used after validation, what if application that is using your library later in request is using `paramErrorMessage`...

**Comment by rustybailey** [comment]
Should be fixed in 2.20.8
