### ISSUE TITLE
Validate data inside array

### ISSUE THREAD

**Issue by Fraccaman** [ctavan/express-validator#245]
Is there a way using a validation schema to validate the content of an array?

For example:
`
$.ajax({
    url: '/deleteIds',
    type: 'DELETE',
    data: JSON.stringify([1, 2, 3]),
    contentType: "application/json",
    processData: false,
    success: function(data){
        console.log(data);
    }
});
`
Is possible to validate the content of the array ( data ) to be sure that every element has a specific type ( integer in this case ) ?

**Comment by srkimir** [comment]
@Fraccaman 
this is not possible out of the box, express-validator use validation methods from https://github.com/chriso/validator.js/, but you can always define your custom validators for something specific https://github.com/ctavan/express-validator#customvalidators

**Comment by Fraccaman** [comment]
Yeah, thank @srkimir! 
I didn't think about it! In the end I solved with this snippet here:
```javascript
customValidators: {
    isDateArray: function(array) {
      if(array.constructor === Array){
        for (var i = 0; i < array.length; i++) {
          if(!moment(array[i], "YYYY-MM-DDTHH:mm:ss", true).isValid())
            return false;
        }
      }
      return true;
    }
```
