### ISSUE TITLE
Custom Validation is failing if the parameter to check is empty

### ISSUE THREAD

**Issue by asaryasv** [ctavan/express-validator#246]
I have written a custom validation like 

//custom validator
checkValue:function(input){
return true;
}

req.assert('inputVal','test custom validation').checkValue();

when inputVal has a value it is working fine
when inputVal is an empty string custom validation is failing 

Please help me to sort it out

Thanks & Regards
ARYA S A

**Comment by srkimir** [comment]
hy @asaryasv can you please provide what you are sending as request body or whatever you are using

**Comment by asaryasv** [comment]
Hi Srkimir,

case 1
           req.body={
               inputVal :'a string'
}

in this case custom validation is working fine 

case 2
   req.body={
               inputVal :""
}

in this case custom validation is not get calling it is going to an error condition like inputVal is undefined

**Comment by fvgs** [comment]
@asaryasv Could you provide the entire error you're seeing? What version of express-validator are you using?

**Comment by gustavohenke** [comment]
This code, by itself, works: https://runkit.com/gustavohenke/581798f90d1f91001355dc7b

I'm closing this issue; however, if you could provide us a full sample of your issue, I'll be happy to reopen it and fix it.
