### ISSUE TITLE
Lodash issue

### ISSUE THREAD

**Issue by aziflaj** [ctavan/express-validator#251]
`express-validator` is included in a [megaboilerplate](https://github.com/sahat/megaboilerplate) application and it throws this error when `npm start` is executed. 

```
/node_modules/express-validator/node_modules/lodash/lodash.js:276
  cloneableTags[argsTag] = cloneabl
                                   

SyntaxError: Unexpected token ILLEGAL
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/vagrant/ondemand-delivery/node_modules/express-validator/lib/express_validator.js:2:9)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
```

**Comment by ArmendGashi** [comment]
That error is not helpful, did you install dependencies provided for megaboilerplate! also make sure you are running on Node 6.0.

**Comment by lbrtsaperium** [comment]
Same issue here, was this ever resolve?

**Comment by gustavohenke** [comment]
@aziflaj, where exactly is this issue?

I downloaded a simple Megaboilerplate package with Express and Jade only (no other library/framework selected), and got no problems.
Even tried to submit the contact form, which was validated just fine.

**Comment by gustavohenke** [comment]
If anyone is able to provide me a reproducible example of megaboilerplate issues with express-validator, I'll be more than happy to give a look at it.

**Comment by Verdao90** [comment]
Hi i dont know this is the right place but...

I would like to know if in the new version of express-validator (4.2.1) bluebird is not a dependecy anymore

I ask that because i was with a error in this version and i only make it work downloading the version 2.20.8 and when and downloaded it, bluebird cames together.

Anyway if can answer me i appreciate that.

Tks

**Comment by gustavohenke** [comment]
Hi @Verdao90, yes, that's correct, bluebird is no longer a dependency starting with v4.0.0.
Your issue must be something else, though.

**Comment by Verdao90** [comment]
First tks for the answer...

Now i realize somes tests to try to reproduce The error and if i get it i will open the issue with proper information 

Tks again
