### ISSUE TITLE
Formatting/string replacement in error messages

### ISSUE THREAD

**Issue by dpolivy** [ctavan/express-validator#252]
I'm currently using v0.7.0 of this library and am looking to update to the latest version. It seems there's been a LOT of change here that impacts me, but one of the big features that seems to be missing is the string replacement/formatting of error messages.

For example, in 0.7.0, I could do this:

		req.check(name, {
			notEmpty: 'Please specify a date.',
			isDate: 'The date %0 is not a valid date.',
			isAfter: (afterDate === undefined) ?
				'Please specify a date after today.' :
				'Please specify a date after %1.',
			isBefore: (beforeDate === undefined) ?
				'You cannot specify a date in the future.' :
				'Please specify a date before %1.'
		}).notEmpty().isDate().isAfter(afterDate).isBefore(beforeDateAdjusted);

In the above, `%0` would be replaced with the param value, and `%1` (etc) would be replaced with the argument values.

I guess this must have been done by validator.js in the past, and so got lost when validator.js refactored. It'd be great to have this back!

(It'd also be great to have the error message syntax back like this, too.)

**Comment by dpolivy** [comment]
PR for this in #253

**Comment by hem1980** [comment]
app.get('/PolicyConfig/:name', (req, res) => {
            req.checkBody("leader_email", "Enter a valid email address.").isEmail();
});

when I try to write req.check or req.checkBody I get following error: 
Property 'checkBody' does not exist on type 'Request'. Do I need to update anything else?

**Comment by dpolivy** [comment]
@hem1980 Is this related to the PR? Have you added the expressValidator middleware to the route stack as described in the instructions?

**Comment by hem1980** [comment]
Yes I added
import * as bodyParser from "body-parser";
var validator = require('express-validator');

app.use(bodyParser());
app.use(validator());
app.use(bodyParser.urlencoded({ extended: true }));
app.use(bodyParser.json());

**Comment by rustybailey** [comment]
This is now in 2.20.10.
