### ISSUE TITLE
How to use sanitize?

### ISSUE THREAD

**Issue by jopcode** [ctavan/express-validator#258]
I need sanitize a email a username field. 
in email have "xjmkasd{2jkads@asd}.com" and i want "xjmkasd2jkads@asd.com".
username, I have "  'asda'sd'  " and i want "asdasd".

I don't know how to use that function, Help me please
Sorry for my bad english, very thanks.

**Comment by IOAyman** [comment]
The list of sanitizers available can be found at [chriso/validator.js](https://github.com/chriso/validator.js#sanitizers).  
For instance, there are multiple ways to achieve what you're looking for. One would be to utilise the `blacklist` sanitizer:
```js
req.sanitize('email')
    .blacklist('{}')    // this removes any '{' or '}' characters found in 'email'
    .normalizeEmail({lowercase: true}) // optionally, you can use this to normalize the email format (read the docs)
```
Same goes for `username`.

**Comment by jopcode** [comment]
Now I have this 
`req.sanitize('email').whitelist(['abcdefghijklmnñopqrstuvwxyz','@']);` 
and works correctly, but there any way to simplify this using whitelist method?(i mean **abcdefghijklmnñopqrstuvwxyz**)

**Comment by gustavohenke** [comment]
@jopcode, can you check whether `normalizeEmail` suffices, as suggested above by @IOAyman?

**Comment by gustavohenke** [comment]
Closing due to lack of response.
