### ISSUE TITLE
"optional" property is counter-intuitive

### ISSUE THREAD

**Issue by slavafomin** [ctavan/express-validator#263]
Hello!

Thank you for this great library!

However, the `optional` property is counter-intuitive when using schema validation.

I've set `optional` property to `false` and expected this field to be required, but it was still optional. I've spent hour to find the cause of this.

When looking at the code you think that this flag is actually a flag, but when digging deeper it's actually a validator of it's own and it doesn't matter what value are passed to it.

I suggest either to change this API to more intuitive one, e.g. treat it as a flag, or at least update the documentation to reflect this more clearly, e.g. change examples from `optional: true` to `optional: {}` or something.

Thanks!

**Comment by gustavohenke** [comment]
You're right, the behavior for schema validation treats every key as something that *will be done*, no matter what options are passed. The same will happen for any other validation, like `isEmail`, `isInt`, etc.

I think this could definitely be changed to ignore the validations if their values are falsy.

**Comment by lukeramsden** [comment]
Is this going to happen? The current behaviour is quite annoying.
