### ISSUE TITLE
return a modified value from the validator

### ISSUE THREAD

**Issue by bogomips** [ctavan/express-validator#264]
Sometime it could be very useful to verify and modify a value in the same operation.
For instance, through the api I expose, I get and ID that I use to get data by a remote api, depending on the return value I can understand if the id was valid but then i want to return the more complex object i got from the remote api and save it on my db.
I know i can read from req._asyncValidationErrors but it is not so clean...
Some ideas:
-  to return value on the resolve() and get it like req.asyncValidationErrors().then(function(data <---this) {})
-  to set an option. if this option is true, we could directly modify the soruce req.body.originalParam in order to get the final value after the validation.
-  to use  a customanitizer inside the custom validator

What do you guys think about it?

**Comment by gustavohenke** [comment]
Sorry, but I had some trouble trying to understand you.

So let me know how much I understood:
You fetched some object from a remote API, which was used for running your validation.
And later, without extra network calls, you want to perhaps save the same object into your DB.

Correct?

**Comment by bogomips** [comment]
Sorry if I was not clear, I try again.
In some cases, it can happen to receive a value that one doesn't want to save directly.
For instance, I receive in my backend (from the app), an ID that I use to query a remote api and get some data back. 
In this case I basically verify the ID and get data in the same operation (querying the remote api).
What I want to save on db it's that data and not the original ID.
So What I need is to return the whole object I received and have it available after a req.asyncValidationErrors().then(function() {  so I can write it into db if everything is ok.
Is it possible? 
Right now I was forced to bypass express-validator, do my own checks and then use it for the remaining values.

**Comment by gustavohenke** [comment]
Closing as this doesn't seem to be a problem with express-validator.
