### ISSUE TITLE
Best practices regarding unknown properties

### ISSUE THREAD

**Issue by Maddoc42** [ctavan/express-validator#266]
Requests can be validated via a custom schema, e.g.

``` javascript
req.checkBody({
  email: { ...
});
```

which is great. Are there any guidelines what to do, if the request should only contain the `email` property and nothing else? For example the following request body should cause validation to fail

``` json
{
  "email": "example@example.org",
  "extra": "I should not be here!"
}
```

with an error message along the lines of `Unknown property "extra"`.

Any thoughts / hints appreciated! :)

**Comment by gustavohenke** [comment]
There's no such thing yet.
Do you have any suggestion on how to implement this?

**Comment by Maddoc42** [comment]
Ideally this "no extras" flag should be set on a per schema basis. There does not seem to be an options object for this yet, so that's a starting point.

From there a naive implementation could firstly get all keys (in dot notation where necessary) from `req.body`, and then compare those to the keys in the validator schema. Am I missing something important?

**Comment by gustavohenke** [comment]
> Am I missing something important?

No, that pretty much nailed it.

I can see the beauty in using such feature when your schema is based entirely in `req.body`.
However, if your schema takes into account something from eg query string, it's probably going to give you more headaches than benefits.

Here's a related requested enhancement: #168
It's probably a little bit more useful when mixing various sources in the same schema.

**Comment by Maddoc42** [comment]
Nice, thanks for the reference! :+1: that's pretty much my use case actually, the solution with lodash 

```javascript
var requestParams = _.pick(req.body, _.keys(validationMap));
```
pretty much solves my problem! :tada:

Primary difference to this issue is that, rejecting unknown properties in a request could help potential client API developers. I'll keep this open as a reference :blue_book:

**Comment by gustavohenke** [comment]
So I would like to add this to the v4+ APIs, not to the legacy APIs as they are difficult to implement, modularise and type.

My API suggestion for now is:

```js
app.get('/some/path', [
  check('something').not().isEmpty(),
  checkNoUnknown()
], (req, res, next) => {});
```

Any better names? 🤔

**Comment by gustavohenke** [comment]
Due to the inherent difficulty of rejecting unknown properties combined with wildcards (`*`), I'll close this issue for now.
If anyone wants to implement this, feel free to do so.
