### ISSUE TITLE
Example occur TypeError "express.createServer is not a function".

### ISSUE THREAD

**Issue by xujiuhua** [ctavan/express-validator#268]
my package.json:

"devDependencies": {
    "body-parser": "^1.15.2",
    "express": "^4.14.0",
    "express-validator": "^2.21.0",
    "util": "^0.10.3"
  }

**Comment by xujiuhua** [comment]
I update code like this,so it can run normally.
```js
    const app = express();
    //app.use(express.bodyParser());
    app.use(bodyParser.json());
    app.use(bodyParser.urlencoded({ extended: true }));
```

**Comment by gustavohenke** [comment]
That example was probably from the Express v3 era. I updated it to match Express v4 API.

56a90a1
