### ISSUE TITLE
npm version bump

### ISSUE THREAD

**Issue by benrolfe** [ctavan/express-validator#275]
Looks like the last version bump was on [24th October](https://github.com/ctavan/express-validator/commit/a95211dd788687bc781cbe0d985a285918e57729), however the documentation has moved on.

Can you bump the version so I can pull the latest version through npm?

Ben

**Comment by gustavohenke** [comment]
There are some things I still want to do before the bump, to pack everything under a major version.
Mainly:
- #269/#249
- #270

You can read the current docs at [the npm site](https://www.npmjs.com/package/express-validator).
