### ISSUE TITLE
how to use express-validator for validation of input file?

### ISSUE THREAD

**Issue by waldemirflj** [ctavan/express-validator#276]

**Comment by gustavohenke** [comment]
Currently, express-validator only supports query string, request body and headers.
Cookies support is on the way with #232.

I don't see how file validation should take place.
Do you have any suggestion?

**Comment by arunkillu** [comment]
He might be asking for file extension and file size validation .

**Comment by cbovis** [comment]
I can definitely see some value in this, keeping all request validation in one place as opposed to falling back on multipart form parser middleware for file validation. Typical rules would be required, acceptable file types and file size.

@waldemirflj have you tried writing a custom validator to plug into express-validator for this already?

**Comment by Abhimanyu310** [comment]
@waldemirflj: I had a similar use case. I wanted to check if the submitted files have a .pdf extension. And I was able to achieve it by writing a custom validator.

**Comment by gustavohenke** [comment]
Hi @Abhimanyu310, are you okay in sharing such custom validator with us?

**Comment by Abhimanyu310** [comment]
@gustavohenke Sure.

Defined custom validator isPDF()
```javascript
app.use(validator({
  customValidators: {
    isPDF: function(value, filename) {
      var extension = (path.extname(filename)).toLowerCase();
      return extension == '.pdf';
    }
  }
}));
```

Validated as below. I am using [express-fileupload](https://github.com/richardgirges/express-fileupload) to parse the uploaded files, and you can access the filename as *req.files.myfile.name*, where myfile is the name of the file upload field in HTML.
```javascript
req.checkBody('myfile', 'Please upload your file in PDF').isPDF(req.files.myfile.name);
```

**Comment by nmajethiya** [comment]
@Abhimanyu310  What is path in above example ?

**Comment by gustavohenke** [comment]
@nmajethiya:
1. it's probably Node's native `path` module
2. that's just an example to work around the lack of a `req.checkFile()` method.

**Comment by funklos** [comment]
Are there any plans to incorporate the validation of req.files?
We are currently rolling our own wrapper method applying the solution from @Abhimanyu310 but it feels like a hack to abuse the defined api in such a way.

**Comment by gustavohenke** [comment]
@funklos you can surely suggest something feasible, or even implement it yourself.

Since I'm busy with other stuff, I don't have the time to come up with/implement any solution, so if one could do this for me it would be awesome 😄

**Comment by gustavohenke** [comment]
Due to the lack of standards around `req.files`, I'm postponing the implementation of this issue and closing it.
Ideas are welcome.

**Comment by sant123** [comment]
I have one:

``` js
photo: {
        in: "files", // even use files.file with dot-prop :)
        custom: { // a custom validation is required for these inputs
            options(value: Array<any>, { req, location, path }) {
                // stuff
                const hasFiles = !!value && value.length > 0;
                if (!hasFiles) {
                    return hasFiles;
                }
            },
            errorMessage: "Files are required to process the request."
        }
    },
```
What do you think @gustavohenke?

**Comment by beaclnd92** [comment]
I have a solution which works for me. I use multer to process multipart/form-data, then I assign req.files to req.body.files with the workaround:
```javascript
const upload = multer({ storage, limits }).array("files");

const uploadHandler = (req, res, next) => {
    upload(req, res, (err) => {
        if (err) {
            res.status(400)
                .json({ message: `Bad request, ${err.message}` })
                .end();
        } else {
            // special workaround for files validating with express-validator
            req.body.files = req.files; 
            next();
        }
    });
};
```
Following that, just use 
```javascript
check("files")
```
