### ISSUE TITLE
checkHeaders header name needs to be lower case

### ISSUE THREAD

**Issue by siboulet** [ctavan/express-validator#278]
Maybe README should be updated to note that header name needs to be lower case. For example X-Custom-Header won't work and needs to be x-custom-header.

```js
req.checkHeaders('x-custom-header').optional().isEmail();
if (req.validationErrors()) return res.status(400).end();
```

**Comment by gustavohenke** [comment]
Or, even better: make it case insensitive!

**Comment by siboulet** [comment]
@gustavohenke even better! Thanks :+1:

**Comment by gustavohenke** [comment]
I'm glad I've helped 😁 

I'll let you know as soon as a version is published with this fix.
