### ISSUE TITLE
getValidationErrors is not a function

### ISSUE THREAD

**Issue by EmixMaxime** [ctavan/express-validator#279]
Hello,
I do that :
```javascript
router.get('/', (request, response) => { 
  request.checkQuery('to', 'Invalid date').isDate()
  request.getValidationErrors()
})

```
and I have this error : 
`request.getValidationErrors is not a function` 
Why?
In my app.js I use the middleware after bodyParser.

**Comment by cbovis** [comment]
The README is out of sync with the current version on NPM.

Refer to v2.21 of the README at https://github.com/ctavan/express-validator/blob/v2.21.0/README.md for the correct API.

**Comment by EmixMaxime** [comment]
Thanks.
