### ISSUE TITLE
Question: When is the next version going to be pushed to NPM registry?

### ISSUE THREAD

**Issue by IOAyman** [ctavan/express-validator#283]
Is it any time soon? :)

It's been 4 weeks since the [last version](https://github.com/ctavan/express-validator/releases/tag/v2.21.0) was published, and there were some important [changes](https://github.com/ctavan/express-validator/compare/v2.21.0...4e0d126) ever since.

**Comment by gustavohenke** [comment]
Hi @IOAyman, thanks for asking.

There are some stuff which I still want to pack in the same major version.
I'm [assigning myself](https://github.com/ctavan/express-validator/issues/assigned/gustavohenke) to such issues. If you want to help in some of them, let's chat about the approach!

**Comment by IOAyman** [comment]
I see. I will join the discussion or send a PR if I can help on my free
time!
Thanks for your reply @gustavohenke :)

**Comment by gustavohenke** [comment]
Fine! Then I'll close here, but feel free to comment.
