### ISSUE TITLE
how to implement `.isIn()` via schema?

### ISSUE THREAD

**Issue by yentsun** [ctavan/express-validator#284]
I have this field in my schema:
```
...
service: {
        isIn: {
            options: ['a', 'b', 'c', 'd'],
            errorMessage: 'unknown service'
        }
    }
...
``` 
But only service `a` validates however. How do I apply `isIn()` correctly?

**Comment by yentsun** [comment]
to answer my own question - this works:
```
...
service: {
        isIn: {
            options: [['a', 'b', 'c', 'd']],
            errorMessage: 'unknown service'
        }
    }
...
```
there are probably some other arguments (apart from allowed values array) expected in options...

**Comment by gustavohenke** [comment]
Hi @yentsun, you can expect `options` to work just like `.apply` would for some function.  
Every item in the array is passed as an option to the underlying validator method.

If all you want is to pass a single option, then you don't need to wrap it in an array.
