### ISSUE TITLE
How  to control order of error messages ?

### ISSUE THREAD

**Issue by AleksandrChernyavenko** [ctavan/express-validator#287]
Example:

```javascript
expressValidator({
    customValidators: {
        uniqueEmail: function (val) {
            return new Promise(function (resolve, reject) {
                setTimeout(() => reject(), 5 *1000);
            });
        },
    }
});

req.checkBody({
    email: {
        notEmpty: true,
        isLength: {
            options: [8, 40],
            errorMessage: 'wrong length'
        },

        isEmail: {
            errorMessage:  'wrong email'
        },

        uniqueEmail: { //this is custom Async Validator
            errorMessage: 'duplicate email'
        },
    }
});
return req.asyncValidationErrors(true);;
```

I always have error "Duplicate error," but I want to get the first error message from wrong validator

- If I send email = "abc" -> need error  'wrong length'
- If I send email = "abc_gmail.com" -> need error  'wrong email'
- If I send email = "abc@gmail.com" and already have this email in DB -> need error  ''duplicate email'

Do you have any idea?

**Comment by gustavohenke** [comment]
If you're not yet using v3, please update it.  
We introduced the [result API](https://github.com/ctavan/express-validator#result-api) which solves this problem, very common until then.

```js
req.getValidationResult().then( result => {
  result.useFirstErrorOnly().mapped(); // same structure as before, but no surprises when inspecting the returned object
});
```

**Comment by gustavohenke** [comment]
Has this helped you, @AleksandrChernyavenko?

**Comment by AleksandrChernyavenko** [comment]
Yes, thanks
