### ISSUE TITLE
checkHeaders breaks when validating a schema

### ISSUE THREAD

**Issue by pascalopitz** [ctavan/express-validator#288]
`    TypeError: param.toLowerCase is not a function
        at IncomingMessage.req.checkHeaders (/home/pascal/Development/Sine/sinecloud-api/node_modules/express-validator/lib/express_validator.js:333:39)
`

I assume because the checkHeader method isn't doing the plainObject check?

**Comment by gustavohenke** [comment]
Yes. Schema validation is only supported for URL params, query string and body.

However, I don't know what is the reason of this choice. Do you have a clue, @rustybailey?

**Comment by pascalopitz** [comment]
Indeed, it says it in the fine print.
Hmm, strange, it worked in 2.x, or at least it didn't throw errors ... prevents me from upgrading now.

**Comment by pascalopitz** [comment]
Ok, just checked. It probably didn't work, but not error as the `toLowerCase` was just added in 3.x

**Comment by gustavohenke** [comment]
You're right, the commit that introduced this error is 17cb82e659197f9396fed537e4e190bff166e93c

Perhaps @rustybailey or @ctavan can give us a clue about the lack of schema validation behavior.
Depending on the answer, I can add support for it.

**Comment by rustybailey** [comment]
I'm honestly not sure. @Jakeii added the initial code for schema validation (https://github.com/ctavan/express-validator/pull/145/files) and @JaniszM added support for specifying the location to check (https://github.com/ctavan/express-validator/pull/208/files), so maybe one of them may know?

**Comment by JaniszM** [comment]
It was ages ago but as I remember location support has no support for headers :P This is the only location not supported, I really dont exactly remember why.

**Comment by pascalopitz** [comment]
Will this do? https://github.com/ctavan/express-validator/pull/290

**Comment by pascalopitz** [comment]
I had a bit more of a thorough look and added a couple of todo's to my pull request. Will get this in over the next couple of days when I have a spare moment.
