### ISSUE TITLE
Extend the error object with a code

### ISSUE THREAD

**Issue by bogomips** [ctavan/express-validator#291]
Hello,  sometimes it is confortable for the same parameter to distinguish between different possible errors.
The client could react in a different way depending on the error and is not pratical to compare the message string, so I had to write a customErrorFormatter to split('#') the message and in case return 

```
{
       code:code
	param : param,			
	value : value,			
	msg:message
}
```

This is how I had to write the error message

```
	'email': {
		in:'body',
		notEmpty: true,
		isEmail: {
			errorMessage: '1#Invalid email format',
		},
		_isValidEmailProvider: {
			errorMessage: '2#Invalid email domain',
		},
		_isEmailNotInDb:{
			errorMessage: '3#This email is already used from another user',
		}
	}
```

It would have been much easier and readable to have the opportunity to write

```
'email': {
		in:'body',
		notEmpty: true,
		isEmail: {
			errorMessage: 'Invalid email format',
                       code:1
		},
		_isValidEmailProvider: {
			errorMessage: 'Invalid email domain',
                       code:2
		},
		_isEmailNotInDb:{
			errorMessage: 'This email is already used by another user',	
                        code:3
		}
	
	}
```

**Comment by gustavohenke** [comment]
I kinda suggested the same thing you want in #201.

You could try using `message` as an object, but it's not really guaranteed that it'll work.
I'll perhaps add some tests and docs for this in case it works.

**Comment by gustavohenke** [comment]
This is quite possible now with the v4.1.0 release! But please also read [about v4.0.0](https://github.com/ctavan/express-validator/releases/tag/v4.0.0) before you start migrating away :)

In the new check APIs, you may define your error messages however you want, and things will still work properly.
You can even shape the errors however you want using `validatorResult(req).formatWith(formatter)`.

The legacy APIs have not received as much love as I gave to the new APIs.. so you *could* try passing objects as error messages. I don't know what the outcome is gonna be.

Let me know.
