### ISSUE TITLE
Cookies are not covered by schema validation

### ISSUE THREAD

**Issue by IOAyman** [ctavan/express-validator#292]
Similar to #288.

Looking at [`checkCookies`](https://github.com/ctavan/express-validator/blob/68242d92fba7c529727f55761a90f751862953b1/lib/express_validator.js#L341), it does not support schema validation as well.
Is there are particular reason for that?

**Comment by gustavohenke** [comment]
Not that I remember.

If I'm not mistaken, I just accepted that PR #232 because the implementation was almost a copy-and-paste of the headers implementation.
