### ISSUE TITLE
Request for adding a not() validator in validation chain

### ISSUE THREAD

**Issue by masumsoft** [ctavan/express-validator#294]
I wanted to do something like this:

```
req.checkBody('myParam', 'myParam cannot contain blacklisted items').not().isIn(myBlackList);
```

I think adding a generic not() validator would allow all the isSomething validations to be negated if necessary.

**Comment by gustavohenke** [comment]
Good idea.

For now you could try do this with regex:

```js
req.checkBody('myParam').matches(new RegExp('^(?!(' + blacklist.join('|') + ')).*$'))
```

Please note however that this regex will match stuff that start with the blacklisted string.
May not work on all conditions for you.

**Comment by gustavohenke** [comment]
Hello! [v4.0.0 has finally been released](https://github.com/ctavan/express-validator/releases/tag/v4.0.0), bringing with it the support for the `.not()` chain method! 🎉 🎊 

Please check the README for complete docs, and also check the [upgrade guide](https://github.com/ctavan/express-validator/blob/v4.0.0/UPGRADE_GUIDE.md).
