### ISSUE TITLE
express validator gives errors even on valid data

### ISSUE THREAD

**Issue by pouyajabbarisani** [ctavan/express-validator#296]
I have 2 route, in one of then checkBody works good but in other one gives error on valid data.
for more debugging I set some sample string for my vars but it still not working :(
 
this is my code:
router.post('/new-ad', function (req, res) {
    var addCity = 'london';
    var addAddress = 'watford';

            req.checkBody('addCity', 'City is empty').notEmpty();
            req.checkBody('addAddress', 'Address is empty').notEmpty();

            var errors = req.validationErrors();
            if (errors) {
                res.render('dashboard/new-ad', {
                    title: 'add new advertise',
                    add_advertise_errors: errors,
                });
                return;
            }
            res.redirect('/ads');
});

**Comment by IOAyman** [comment]
You are not overriding the data that comes with the request in this example code.
`req.checkBody('addCity'....)`  checks if `req.body.addCity` is not empty.  It does not verify the variables you declared in line 02.

PS:
`req.validationErrors()` is [deprecated](https://github.com/ctavan/express-validator#deprecated-api).  You should use the new result API instead, with [`req.getValidationResult()`](https://github.com/ctavan/express-validator#validation-result)

**Comment by gustavohenke** [comment]
@IOAyman is correct.
