### ISSUE TITLE
Array inline validation

### ISSUE THREAD

**Issue by maZahaca** [ctavan/express-validator#297]
I need to clarify how to do a validation of array values.

Two examples
**one**:
```js
{
  currencies: ["USD", "EUR", "GBP"]
}
```
**two**:
```js
{
  currencies: [{"code": "USD"}, {"code": "EUR"}, {"code": "GBP"}]
}
```

Is it any option to check values of array using validator?

**Comment by IOAyman** [comment]
Currently, that could be achieved using a custom validator.

```js
const expressValidator = require('express-validator')
const validator = expressValidator.validator
...
app.use(expressValidator({
  errorFormatter: (param, msg, value) =>  ({ [param] : msg }),
  customValidators: {
    isX: value =>
              Array.isArray(value) &&
              Array.length > 0 &&
              value.every(item => validator.isIn(item, ['USD', 'EUR', 'GBP']))
  }
}))

app.post('/', (req, res, next) => {
  req.check('test', 'Invalid').isX()

  req.getValidationResult()
     .then(r => !r.isEmpty() ? r.throw() : res.json({ code: 'OK' }))
     .catch(r => next(r.array()))
})
...
```

This would be much easier if #234 gets merged.

**Comment by gustavohenke** [comment]
#234 needs some love in order to be mergeable.
Remember that anyone can take over that branch... and send another PR 😉

**Comment by gustavohenke** [comment]
Hello folks, [v4.0.0 has been released](https://github.com/ctavan/express-validator/releases/tag/v4.0.0), bringing with it support for validating multiple fields with the same rules!

Please check the README for complete docs, and also check the [upgrade guide](https://github.com/ctavan/express-validator/blob/v4.0.0/UPGRADE_GUIDE.md).
