### ISSUE TITLE
How to use as validation middleware

### ISSUE THREAD

**Issue by iamchathu** [ctavan/express-validator#301]
I would like to check body and query parameters as middleware.

like

app.get("/someRoute",myValidationMiddleware,(req,res)=>{
   //Validated data
});

Can I use express validator like middleware and how to implement myValidationMiddleware?

Thank you.

**Comment by gustavohenke** [comment]
You've already done that in your example

**Comment by IOAyman** [comment]
@iamchathu Yes, that is doable.

Here's an example code
```js
...
// validation middleware
const validateRequest = schema => (req, res, next) => {
  req.check(schema)

  req.getValidationResult()
     .then(r => !r.isEmpty() ? r.throw() : next())
     .catch(r => next(r.mapped()))
}

// routes
app.all('*',
  validateRequest(mySchema),
  (req, res, next) => res.json({ code: 'OK' }))

// Woops!
app.use((err, req, res, next) => res.json(err))
...
```

**Comment by iamchathu** [comment]
Thank you @IOAyman I'll test it now and will close this issue

**Comment by IOAyman** [comment]
You're welcome 😄

**Comment by iamchathu** [comment]
I need to allow only defined url params only. Is there any way to do it using schema definition?

Thank you.

**Comment by IOAyman** [comment]
Yes, it can be done in various ways;

You can validate only the query using that schema
```js
...
req.checkQuery(schema)
...
```
Or use the `'in'` property when you define the schema
```js
...
const my schema = { param: { in: 'query', notEmpty: true } }
...
```

And if you prefer, you can use the chained validation approach as well. You would then declare you middleware like:
```js
...
// validation middleware
const validateRequest = (req, res, next) => {
  req.checkQuery('param').notEmpty().withMessage('required!')

  req.getValidationResult()
     .then(r => !r.isEmpty() ? r.throw() : next())
     .catch(r => next(r.mapped()))
}

// routes
app.all('*',
  validateRequest, // this is not a function call
  (req, res, next) => res.json({ code: 'OK' }))
```

**_Read the docs about using [validation schema](https://github.com/ctavan/express-validator#validation-by-schema)_**

**Comment by gustavohenke** [comment]
As @IOAyman already helped you a lot, I'll close for now :)

**Comment by iamchathu** [comment]
@IOAyman  Thanks a lot.

**Comment by IOAyman** [comment]
You're welcome! Glad to help 😉
