### ISSUE TITLE
Allow custom validator to return error message

### ISSUE THREAD

**Issue by maxsummers** [ctavan/express-validator#302]
I have a custom validator for passwords in my application. It encapsulates entire password validation policy and allows to validate passwords in any place of application without code duplication.

However, I want to return meaningful error messages from it, e.g. `Password must contain at least one number` or `Password must contain at least one uppercase letter` and such, according to the user input. Right now, `express-validator` only allows to return boolean result, which is limiting and forces us to use single message for all password problems.

I would suggest to allow returning complex value like this:

```js
return {
  result: false,
  message: 'Password must contain at least one number'
};
```

Thanks.

**Comment by gustavohenke** [comment]
Hi @maxsummers! Sorry for the delay.
What if you replaced your custom validator with a middleware?
Something like this:

```js
const validatePassword = field => {
  return ( req, res, next ) => {
    req.checkBody( field )
      .notEmpty().withMessage( "must be provided" )
      .len( 5 ).withMessage( "must have at least 5 characters" )
      .matches( /\d/ ).withMessage( "must contain at least one number" );

    next();
  };
}

// API for creating an user - with reusable password validation middleware!
app.post( "/users", validatePassword('password'), ( req, res, next ) => {
  // Handle your request, add more validations, etc
});

// Oh look ma, a wild API for patching the logged user appears!
app.patch( "/user", validatePassword( "password" ), ( req, res, next ) => { ... });
```

It's not a very portable solution though, but could help you get started for now.

**Comment by gustavohenke** [comment]
Hello @maxsummers, [v4.0.0 has finally been released](https://github.com/ctavan/express-validator/releases/tag/v4.0.0) 🎉 

You can now throw errors in your custom validators, but you must use the new `check` APIs for this to work.

Please check the README for complete docs, and also check the [upgrade guide](https://github.com/ctavan/express-validator/blob/v4.0.0/UPGRADE_GUIDE.md).
