### ISSUE TITLE
Value null

### ISSUE THREAD

**Issue by vishnureddy** [ctavan/express-validator#303]
Hi,
I am using express-validator for Validations. When i am doing validations with Matches it is not executing. I did not find any compile errors here but if i print Validation errors the following output is came.
```req.assert('Name', 'Please enter Valid Name', req.body.name).matches(/[a-zA-Z]/);```
```Output:
{ param: Name',
    msg: 'Please enter Name',
    value: undefined }```
I don't know why the value of req.body.name is undefined even though the body have the name.

Thanks.

**Comment by gustavohenke** [comment]
You're misunderstanding how `req.assert`/`req.check` works.

This is the signature for these methods:
```js
req.check( paramName[, validationMessage] );
```

Supposing it's `name`, then this method will search for `req.body.name`, `req.query.name`, `req.params.name`, etc. This will do what you want.

[Docs](https://github.com/ctavan/express-validator#reqcheck)
