### ISSUE TITLE
.equals validation not working to validate password

### ISSUE THREAD

**Issue by oqx** [ctavan/express-validator#311]
Hey all,

Since google wasn't on my side when I ran into this issue, I thought I'd post an issue here in the off chance that this happens to someone else.

When using `req.checkBody('password2', 'Password doesn't match').equals(req.body.password);`, it incorrectly throws an error. I logged `password` and `password2` to make sure they were the same. I was able to resolve this by using [schema](https://github.com/ctavan/express-validator#validation-by-schema):
https://github.com/ctavan/express-validator#validation-by-schema

I'm not quite sure what I did wrong, or if it's just some weird one-off thing with my build, but since I couldn't find a related issue on the web, chances are it's the latter. Feel free to close this issue or prod me with questions. Mainly, I'd just like to make this searchable if someone has a similar experience.

**Comment by gustavohenke** [comment]
Hi @oqx! Thanks for using express-validator.

You could check whether they are really equal by using plain JS:

```js
console.log(req.body.password === req.body.password2);
```

I also created a simple, live example [here](https://runkit.com/58a44c970ab7870013d42137/58ade4032f467c001575f3b0) in case you find a deterministic way to simulate your problem, so you have a starting point!

**Comment by Palaklive** [comment]
I  have the same problem. and I also check 
`console.log(req.body.password === req.body.password2);`
it's return true.

**Comment by gustavohenke** [comment]
Hi @Palaklive, can you provide a working example, please?
Otherwise I won't be able to help you with this simple information.

**Comment by Altair312** [comment]
Hello,

I've stumbled into the same problem. .equals() doesn't work properly for some odd reason, tried logging password with my passwordConf and returns true as well.

My post request validation looks like

` body('username').isLength({    min: 5  }).withMessage("Please enter a valid user name"),
  body('password').isLength({    min: 5  }).withMessage("Your password must be at least 5 digits"),
  body(body.passwordConf).equals(body.password).withMessage('fuck this shit again'),
  body('email').isEmail().withMessage('Enter a valid email address').trim(),
`
If I put a random string into equals(), then matching it in the password confirmation field will let me register a new account. 
Putting either body.password or body('password') or 'password' will simply return an error that the match is false.

What gives?

gustavo mentioned about a working example, what exactly do you need provided to have a look? i am currently very new in node and express so...

**Comment by gustavohenke** [comment]
Hello @Altair312, can you please see https://stackoverflow.com/a/46013025/2083599

**Comment by Altair312** [comment]
@gustavohenke Thanks, worked flawlessly!
