### ISSUE TITLE
How to ignore parameters not whitelisted or not specified in a schema?

### ISSUE THREAD

**Issue by julianosam** [ctavan/express-validator#312]
Hi. I'm using this API for the first time. Very interesting.
 
I'm struggling to find a way to only whitelist the query parameters specified in the schema. Is there a way yo do it?

More specifically, is there a way to filter out query params that are not in the schema?

smth like:

```javascript
// This should pass
// GET /myapi?allowedParam=1
req.sanitizeQuery().whitelist(['allowedParam']);
console.log(req.query); // {allowedParam : 1 }

// Unspecified param should be filtered out
// GET /myapi?allowedParam=1&disallowedParam=2
req.sanitizeQuery().whitelist(['allowedParam']);
console.log(req.query); // {allowedParam : 1 }

```

Thank you for your help.

**Comment by gustavohenke** [comment]
This seems to be the same as #168, so I'll close here in favor of that issue.
Thanks for using express-validator!
