### ISSUE TITLE
Errors in the documentation's example

### ISSUE THREAD

**Issue by gk0us** [ctavan/express-validator#316]
There are some mistakes in the documentation's example.

1. **Issue:**`app.use(bodyParser.json())` is used and therefore the `curl -d `commands mentioned in the documentation won't work. The post parameters will not be parsed, since the bodyparser plugin waits for a body with a json format. Moreover, `checkBody` will always produce a validation error since `postparam `is `undefined`.
**Solution:** Replace `app.use(bodyParser.json())` with `app.use(bodyParser.urlencoded({ extended: true }))`
2. **Issue:** `getparam` and `postparam` are not accessible from the `req.params` object.
**Solution:** Replace `req.params.getparam` with `req.query.getparam`
and `req.params.getparam` with `req.body.postparam` in the following part of the example:
```
...
res.json({
urlparam: req.params.urlparam,
getparam: req.params.getparam,
postparam: req.params.postparam
    });
...
```

**Comment by gustavohenke** [comment]
PRs are welcome!
