### ISSUE TITLE
Usage section of docs out of date due to deprecated getValidationResult usage

### ISSUE THREAD

**Issue by JordanTheriault** [ctavan/express-validator#317]
Due to the deprecation of `getValidationResult()`, the usage is out of date. This usage section should be using `validationErrors()` or `asyncValidationErrors()`.

**Comment by gustavohenke** [comment]
Actually, you misunderstood the docs. The opposite is true.

**Comment by JordanTheriault** [comment]
@gustavohenke Sorry, I checked and you're right. I misread. However `getValidationResult` does not work for me. `req.getValidationResult is not a function`

**Comment by JordanTheriault** [comment]
@gustavohenke Apologies, misread and assumed getValidationResult was wrong because it was failing for me. Turned out npm is installing version `2.21.0` and not the latest.
