### ISSUE TITLE
Allow Custom Validator to return Promise

### ISSUE THREAD

**Issue by souzavitor** [ctavan/express-validator#318]
I've been using this library with typescript. Then, I had found a semantic problem when I was trying to use **Promises** in the custom validators.

I have a custom validator to check if a username is already registered in the database. That's why I need to implement the custom validation returning **Promise**.

I'm trying to do something like that:
```node
router.use(validator({
  customValidators: {
    isUsernameTaken : (param, _id) => {
      return new Promise((resolve, reject) => {
        let conditions = {
          username: param
        };
        if (typeof _id !== 'undefined') {
          conditions['_id'] = {$ne: _id};
        }
        return UserService.findOne(conditions)
          .then(user => {
            if (user) {
              return reject(user);
            }
            return resolve(true);
          })
          .catch(err => {
            resolve(err)
        });
      });
    }
  }
}));
```

Thanks.

**Comment by emjaksa** [comment]
I can't see any issues with your code, I have an almost identical custom validator which works. What method are you calling to get the results?  Ensure you are using req.getValidationResult and not the synchronous req.validationErrors.

**Comment by souzavitor** [comment]
I did some testing and realized that this code really works. But, typescript is saying that I have a semantic error in my code: **error TS2345: Argument of type '{ customValidators: { isUsernameTaken: (param: any, _id: any) => Promise<{}>; }; }' is not assignable to parameter of type 'ExpressValidatorOptions'**.

Is there anything I can do to solve this problem?

**Comment by kacepe** [comment]
Why you don't return `true` or `false` from `UserService.findOne` promise? I think it should work.

**Comment by dirkcuys** [comment]
@kacepe didn't work for me - have a look at the [code](https://github.com/ctavan/express-validator/blob/master/lib/express_validator.js#L361), it specifically checks if the promises were rejected or not.
