### ISSUE TITLE
How to customise errors in a custom validator?

### ISSUE THREAD

**Issue by AmarPrabhu** [ctavan/express-validator#319]
I have a custom validator to validate a array of objects, say:
    
    eachIsInt: function(values, prop) {
        return values.every(function(val) {
           return validator.isInt(val[prop]);
         });
    }

This validates if a property is an integer in the array of objects. But I am unable to figure out how to customise the error object. I would like to pass on the value of the particular error object alone, not the entire array.

For instance:
    
    "inputarray": [
        {
            "blah": 5
        },
        {
            "blah": 5.3
        }
    ]

should yield an error:

    {
      "param": "blah",
      "msg": "Error Message",
      "value": [
        {
          "blah": 5.3
        }
      ]
    }

Instead of:

    {
        "param": "inputarray",
        "msg": "Error Message",
        "value": [
            {
                "blah": 5
            },
            {
                "blah": 5.3
            }
        ]
    }

**Comment by gustavohenke** [comment]
Hi @AmarPrabhu, [v4.0.0 was released](https://github.com/ctavan/express-validator/releases/tag/v4.0.0) with support for wildcards.

This means you can now do the following:

```js
app.get('/', check('array.*.blah').isInt(), (req, res, next) => { /* handle route */ });
```

You may also want to check [the README for complete docs](https://github.com/ctavan/express-validator/tree/v4.0.0) and the [upgrade guide for version 3 users](https://github.com/ctavan/express-validator/blob/v4.0.0/UPGRADE_GUIDE.md).
