### ISSUE TITLE
how to validate nested data in scheme 

### ISSUE THREAD

**Issue by Maxim-Chugaev** [ctavan/express-validator#321]
validate nested form like laravel

```

$rules = [
    'images' => 'array|min:1',
    'images.*.file' => 'image|max:5M',
    'images.*.alt' => 'max:255',
    'images.*.product_id' => 'required|exists:id,products',
];

```

**Comment by gustavohenke** [comment]
Not possible yet.
See #234/#313.

**Comment by gustavohenke** [comment]
I'll close this issue in favor of #347.

**Comment by gustavohenke** [comment]
Hi, [v4.0.0 has finally been released](https://github.com/ctavan/express-validator/releases/tag/v4.0.0), bringing with it the long awaited wildcard `*` support! 🎉 

Please check the README for complete docs, and also check the [upgrade guide](https://github.com/ctavan/express-validator/blob/v4.0.0/UPGRADE_GUIDE.md).
