### ISSUE TITLE
Possible Feature - Is after or equal to date

### ISSUE THREAD

**Issue by Jujunol** [ctavan/express-validator#323]
# The Issue
Having a chain such as `.isDate().isAfterOrEqual()` seems like it would be really useful. In truth, I'm surprised that it's not already there by default.

## Why not use CustomValidators?
Well the problem with that would be the fact that TypeScript has a hard time compiling as it doesn't exist on the `Validator`'s index.tsd

## How would one code this
Well in the custom Validator I would imagine it looking something like:
```
isEqualToOrAfter: (value, arg) => new Date(arg).getTime() >= new Date(value).getTime()
```
Not positive that would work as it's not tested.

**Comment by gustavohenke** [comment]
Thanks for the suggestion!
The opposite (`isEqualToOrBefore`) is also probably useful.

**Comment by gustavohenke** [comment]
While I do agree the examples you gave are useful, I'm closing this issue for now; I have no plans to extend the validation chain API with more validators outside the `validator` lib realm.
