### ISSUE TITLE
Why getValidationResult doesn't reject the Promise when it has an error?

### ISSUE THREAD

**Issue by rdsedmundo** [ctavan/express-validator#326]
I can't understand the purpose of doing:

```javascript
req.getValidationResult.then((results) => {
  if (!results.isEmpty()) {
    // Error
  }
});
```

Why this method exists (`.isEmpty`)? Isn't better to reject the promise, then I can get the error at the `.catch`? `.then` for me means that everything occurs okay.

**Comment by gustavohenke** [comment]
This was done this way to achieve consistency with the sync API `req.validationErrors()`, which doesn't throw if you have errors, but just return them.

Actually, the method name says "get validation result", so I would expect it to throw only if something wrong happened while retrieving the validation result... don't you?

I could definitely add another method to handle the scenario you detailed, if we can find a meaningful name.

**Comment by gustavohenke** [comment]
BTW, you could do something like the following, which will allow you to deal with the errors in the catch of the promise:

```js
req.getValidationResult().then( result => result.throw() ).then( () => {
  req.send( "success!" );
}, e => {
  req.status( 400 ).json( e.array() );
})

**Comment by rdsedmundo** [comment]
Well, that's my particular opinion. I'd like if we don't need this verification statement. That's very useful if we're using _async/await_ too.

A good name for a new method would be: 'isValid'. So: 'Is valid? _Then_ do this'.

**Comment by Vilintritenmert** [comment]
```
        .then((result) => {
            if (result.isEmpty())
                return '';
            else
                throw new Error(result.array().map((item) => item.msg).join('|'));
        })
       .catch((error)=>response.status(400).json({message:error.message.split('|')}));

```

**Comment by gustavohenke** [comment]
Hello folks, [v4.0.0 has finally been released](https://github.com/ctavan/express-validator/releases/tag/v4.0.0).

It brings a new API collection called the `check` API, which includes a function called `validationResult(req)`, which returns the same interface you were used to, but fully synchronous.
Its usage probably solves the discussion here :)

Don't forget to check [the README for complete docs](https://github.com/ctavan/express-validator/tree/v4.0.0) and the [upgrade guide for version 3 users](https://github.com/ctavan/express-validator/blob/v4.0.0/UPGRADE_GUIDE.md).
