### ISSUE TITLE
Is there an option to validate the whole body?

### ISSUE THREAD

**Issue by maZahaca** [ctavan/express-validator#327]
I have few field which depends on the value passed in the field "type",
For example,
* if type = "email" body should have an extra field containing email
* if type = "phone" body should have an extra field containing phone.

So basically, I need a custom validator but for the whole body, where you can access any field in it.

Is it possible somehow?

**Comment by gustavohenke** [comment]
Currently, this is only possible if you implement a custom validator that manually receives the req.body 😐 

```js
req.checkBody("type").hasExtraField(req.body);
```

**Comment by gustavohenke** [comment]
I'm thinking about a better way to do it, but no ideas for now; if you have one, let me know!

**Comment by maZahaca** [comment]
The problem is I'm using a JSON schema to define validator.
Do you have an idea how to apply req.body in that case?

**Comment by gustavohenke** [comment]
Hello @maZahaca, [v4.0.0 has been released](https://github.com/ctavan/express-validator/releases/tag/v4.0.0), and it brings some hotness that can help you get rid of the issues you described here.

You may combine `oneOf` + `.custom()` validators to do what you want.
Small example below:

```js
const { check, oneOf, validationResult } = require('express-validator/check');

app.post('/contact', oneOf([
  check('type').equals('phone').custom((value, { req }) => req.body.phone !== undefined),
  check('type').equals('email').custom((value, { req }) => req.body.email !== undefined)
], 'you must provide the destination for the type of contact you want!'), (req, res, next) => {
  const result = validationResult(req);
  // do something with the validation result!
});
```

I know this could be a lot better 😞 but until I can come up with something, it will fix your issues.

Also don't forget to check [the README for complete docs](https://github.com/ctavan/express-validator/tree/v4.0.0) and the [upgrade guide for version 3 users](https://github.com/ctavan/express-validator/blob/v4.0.0/UPGRADE_GUIDE.md).
