### ISSUE TITLE
Validation Bypass When Using req.check() Method

### ISSUE THREAD

**Issue by dbohannon** [ctavan/express-validator#331]
Validation routines can be bypassed when using the req.check() method on POST requests because this method automatically looks for the parameter name in the params and query objects first before checking the body. Consider the following example where the POST parameter 'name' is validated to only contain alphabetic characters.
```
app.post('/payment', function(req, res){
        //do validations
        req.check('name', 'Name can only contain alpha chars').notEmpty().isAlpha();
```
The following request allows the user to bypass the validation of the POST parameter 'name' by including a 'name' parameter in the query string.
```
POST /payment?name=bob HTTP/1.1
Host: localhost:9000
User-Agent: Mozilla/5.0 (Windows NT 6.3; rv:36.0) Gecko/20100101 Firefox/36.04
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en-US,en;q=0.5
Referer: http://localhost:9000/
Connection: close
Content-Type: application/x-www-form-urlencoded
Content-Length: 128

name=<script>alert('XSS_SUCCESS')</script>&address=123+Main+Street&email=bob%40dentist.com&ccn=4532743563764137&phone=2739171937
```
Developers should use the req.checkBody() method, or another method specific to the object containing the parameters being validated rather than the generic req.check() method. Project maintainers should consider modifying the req.check() method to validate any matching parameters in the query, params, and body object rather than just the first matching parameter.

**Comment by gustavohenke** [comment]
Hi @dbohannon, thanks for your report, and sorry for taking this long to review it.
It's really a problem, and your solution is likely a breaking change, so it would only fit in v4...

**Comment by gustavohenke** [comment]
Hello! [v4.0.0 has finally been released](https://github.com/ctavan/express-validator/releases/tag/v4.0.0).

The new `check` API collection will always validate all occurrences of a field the same way.
The old, legacy APIs (kept in v4 because backwards compatibility) will not work this way, unfortunately.

Please check the README for complete docs, and also check the [upgrade guide](https://github.com/ctavan/express-validator/blob/v4.0.0/UPGRADE_GUIDE.md).
