### ISSUE TITLE
Validate if value matches to any one member in an Array

### ISSUE THREAD

**Issue by rohitshetty** [ctavan/express-validator#332]
Assume I have req.body.currency results in USD. Is there a way I can verify if the currency belongs to one of the prespecified lists of currencies say ['INR', 'USD', 'AUD'] etc. ?

Currently, I am using RegExp to do this. I have many similar use cases and it would tedious and inefficient to repeat code just to get RegExp. Is there a way in which this can be done using this library? Am i missing something in the docs? 
If not I would be happy to make a PR.

Thanks!

**Comment by rohitshetty** [comment]
Okay, I have solved this using a customValidator. But I think it's a common use case and library should have an API to do this.

**Comment by gustavohenke** [comment]
Native validators are provided from the base lib [validator](https://github.com/chriso/validator.js).
If it's available there, it's available here (well, depends on the dependency version actually).

So you can use `.isIn()` for this:

```js
req.checkBody( "currency" ).isIn([ "USD", "AUD", "INR" ]);
```

**Comment by rohitshetty** [comment]
Thank You!
