### ISSUE TITLE
'not' options to oppose the validation

### ISSUE THREAD

**Issue by posquit0** [ctavan/express-validator#333]
Hello,
I noticed that 'notEquals' validator was removed. Is there any way to perform this except using `.match()` validator?
By the way, I think it could be very useful if there is an option `not: true | false` in every validator.

```
password: {
  equals: {
    not: true
  } // => is equals to notEquals
}
```

#294

**Comment by gustavohenke** [comment]
> Is there any way to perform this except using .match() validator?

At the moment, not that I'm aware of 😐 

I will close here, as it's a duplicate of that one.

**Comment by gustavohenke** [comment]
Hello! [v4.0.0 has finally been released](https://github.com/ctavan/express-validator/releases/tag/v4.0.0), bringing with it the support for the `.not()` chain method! 🎉 🎊 

Please check the README for complete docs, and also check the [upgrade guide](https://github.com/ctavan/express-validator/blob/v4.0.0/UPGRADE_GUIDE.md).
