### ISSUE TITLE
isEmpty() not working properly

### ISSUE THREAD

**Issue by nestorherre** [ctavan/express-validator#336]
Hi, I'm trying to use the isEmpty() method but it always returns error, implying that the validated param is empty, even when it isn't. I've used isEmail() and isLength() methods without any issues. However, Using isEmpty() with the 'validator' npm module directly works properly, so it is an issue in express-validator. 

Here's my config:

//
var expressValidator = require('express-validator');
.
.
.
app.use(bodyParser.urlencoded({extended: false}));
app.use(bodyParser.json());
app.use(expressValidator());
.
.
.
req.checkBody('name', 'Error: name is empty').isEmpty();

There's an open question by someone else in StackOverflow with the same issue: http://stackoverflow.com/questions/43417664/express-validator-isempty-not-working

Please check.

**Comment by nestorherre** [comment]
Just found out that with express-validator, the function to be used is notEmpty(). 

This should be explicitly displayed in the readme.md to avoid further confussions.

**Comment by gustavohenke** [comment]
Feel free to send us a PR to handle this.

**Comment by WCLab** [comment]
If you send a post variable, this pass if is an empty string ''

**Comment by gustavohenke** [comment]
I believe the docs are now a lot better since the [v4.0.0 release](https://github.com/ctavan/express-validator/releases/tag/v4.0.0), and such clarifications will no longer be required.
