### ISSUE TITLE
Cannot read property 'apply' of undefined

### ISSUE THREAD

**Issue by naran3434** [ctavan/express-validator#338]
Suddenly after re installed npm dependency.  Using custom validator throws the "Cannot read property 'apply' of undefined"

Custom validation rule :
```js
app.use(expressValidator({
    customValidators: {
        isObject: function (value) {
            return ObjectId.isValid(value);
        }
    }
}));
```

Schema for validation
```js
var schema = {
    '_vehicle': {
        notEmpty: true,
        isObject: {
          errorMessage: 'Vehicle type is should object'
        },
        errorMessage: 'Vehicle type is required'
    },
    '_maker': {
        notEmpty: true,
        isObject: {
            errorMessage: 'Maker is should object'
        },
        errorMessage: 'Maker type is required'
    },
    'status': {
        notEmpty: true,
        errorMessage: 'Status is required'
    }
};
```

kindly help me
Thanks

**Comment by gustavohenke** [comment]
Hello @naran3434!
If you could do at least one of these, it would be great:
- Where is `ObjectId` coming from?
- Clone [this runkit notebook](https://runkit.com/gustavohenke/5904894cfa724700129a25c3) and try to reproduce your issue

I was unable to have an idea of the problem just by reading your issue text.

**Comment by naran3434** [comment]
`ObjectId` coming from custom validator. 
`app.use(expressValidator({
    customValidators: {
        isObject: function (value) {
            return ObjectId.isValid(value);
        }
    }
}));`

I can't use any kind of custom validation

**Comment by gustavohenke** [comment]
> ObjectId coming from custom validator

This isn't really telling me anything. What npm it points to? Or is it something you built yourself?

**Comment by gustavohenke** [comment]
Also other thing that will help, just to clear things: what express-validator version are you using?

**Comment by naran3434** [comment]
"express-validator": "^3.1.1",
Version i am using. 

I have extended the customValidator function & written my own rule for custom validation.

when i try to use the customValidator function which i wrote in validation schema and run it in `req.check()`
it throws me error. but previously same code was working last month

**Comment by gustavohenke** [comment]
If you can't show me some code that reproduces the problem, I won't be able to help you!
What if you share a repository that has this problem?

**Comment by naran3434** [comment]
Here this new REPO : https://github.com/naran3434/express-validator-test.git

install this repo : 
test url : http://localhost:3000/users

if i remove custom validator function from schema it's working fyn.

kindly look on it

Thanks

**Comment by gustavohenke** [comment]
Ah, cool, I checked it out 😃 

You're [setting the custom validator to an unused express app](https://github.com/naran3434/express-validator-test/blob/e898e4e/routes/users.js#L5-L14), but the routes [that use the custom validator are set in the exported express router](https://github.com/naran3434/express-validator-test/blob/e898e4e/routes/users.js#L34-L48).

**Comment by naran3434** [comment]
Hey Thanks for your support. i could understand what i did wrong. :)
