### ISSUE TITLE
isEmail validation fails for strings which contain common unicode symbols

### ISSUE THREAD

**Issue by mtziyo** [ctavan/express-validator#339]
The scenario I checked was this.

1. Use flag isEmail:true for field
2. Use email addresses with the following strings:   Ω≈ç√∫˜µ≤≥÷@email.com or åß∂ƒ©˙∆˚¬…æ@email.com
3. Validation fails

I checked as reference on gmail create an account and both the above mentioned strings, they are marked as invalid as I expected (e.g. message : Please use only letters (a-z), numbers, and periods.).

Should the approach be that we should write a custom validation to handle this scenario? Or is this the expected behavior on express-validator?

**Comment by gustavohenke** [comment]
I unfortunately don't have the time to check this at the moment, but you should check the behavior of our underlying dependencies for validation, [validator](https://github.com/chriso/validator.js/).

**Comment by mtziyo** [comment]
@gustavohenke yep confirmed the dependency  [validator](https://github.com/chriso/validator.js/) has the similar issue.
