### ISSUE TITLE
asyncValidationErrors and getValidationResult are inconsistent

### ISSUE THREAD

**Issue by replicat0r** [ctavan/express-validator#343]
asyncValidationErrors will resolve if there is no error, and the error will show up in the error fn or a catch block of the promise, 

where as getValidationResult will return the error in the then() block, not in the error fn or the catch block of the promise. 

I assume that getValidationResult will return results, other than errors? if this is the case, wouldnt it make more sense to resolve the promise if validation passes, and reject the error in the error handler or the catch block? 

also asyncValidationErrors will reject the errors into the error function or the catch block, which makes sense, but it should also resolve passed in data successfully, instead of returning nothing. 

alot of time these validation are used in a functional pipelines, where you would need to validate the params/body/query, and see if its valid, then pass the data to another function in the pipeline, by not returning anything from the validator function, this would forces the program to wrap the entire execting block inside the then resolve block, since you can use the param value until it passes the validation function.

**Comment by gustavohenke** [comment]
Hi @replicat0r, thanks for using express-validator.
Please see duplicate issue #326 for related discussion on some of your points.
