### ISSUE TITLE
Customvalidators doesn't work

### ISSUE THREAD

**Issue by medkhelifi** [ctavan/express-validator#346]
I use express-validator customValidators to add some specific validtors:
**middlewares.js**

```
module.exports = function (app) {
     console.log('to be sure that Im called');
     return function (request, response, next) {
         app.use(expressValidator({
            customValidators: {
                checkObjectId: function(name) {
                    return /^[0-9a-fA-F]{24}$/.test(name);
                }
            }
         }));
         next();
     }
};
```

**route.js**

```
const middleware = require(__path + '/middlewares');
module.exports = function (app, passport) {
    router.use(baseUrl, middleware(app));
    // some codes
    router.put(baseUrl + '/invoice/:invoiceId', api.invoices.invoices.update);
}
```

**invoices.js**

 ```
update: (request, response) => {
        // some codes
        request.checkBody('from', 'invalid Supplier Id').checkObjectId();
        // some codes
    },
```
My problem is checkObjectId is not recognized and I have this error:

`TypeError: request.checkBody(...).checkObjectId is not a function
`

**Comment by gustavohenke** [comment]
The problem lies in your `middlewares.js` file.
The returned function is only adding more express-validator middlewares *whenever a request comes in*. This means the 1st request will always fail, and more and more express-validator middlewares will be made available.

You could do simply the following instead:

```js
module.exports = app => expressValidator(...)
```
