### ISSUE TITLE
Express-Validator Check array of Subdocuments

### ISSUE THREAD

**Issue by medkhelifi** [ctavan/express-validator#347]
This is my Schema:
```
const InvoiceSchema = new Schema({
name: { type: String, required: true },
description: { type: String },

items: [{
    name: { type: String, required: true },
    rate: { type: Number, required: true },
    quantity: { type: Number, required:true, default: 1 },
    amount: { type: Number }
}]});
```
I want to know if there is a way to use Express-validator to check items elements?

**Comment by gustavohenke** [comment]
Unfortunately, not yet 😞 
See #234 and #313.

**Comment by medkhelifi** [comment]
Is this feature scheduled on next releases??

**Comment by gustavohenke** [comment]
If someone implements it properly before I have a chance, then yes.

**Comment by gustavohenke** [comment]
Hello folks, [v4.0.0 has finally been released](https://github.com/ctavan/express-validator/releases/tag/v4.0.0), bringing with it the long awaited wildcard `*` support! 🎉 

Please check the README for complete docs, and also check the [upgrade guide](https://github.com/ctavan/express-validator/blob/v4.0.0/UPGRADE_GUIDE.md).
