### ISSUE TITLE
Sequential execution of chained validators? 

### ISSUE THREAD

**Issue by newhouse** [ctavan/express-validator#349]
Hi there,

My issue is similar/related to [Execute Validator Sequential](https://github.com/ctavan/express-validator/issues/322) and [Allow custom validator to return error message](https://github.com/ctavan/express-validator/issues/302).

I'm trying something like this:
```
// Custom validators:
function doThisFirst(value, res) {
  return asyncCall(value)
    .then(something => { 
      res.locals.something = something; 
      return Promise.resolve(); 
    })
    .catch(err => {
      // would be nice if I could influence withMessage here somehow. Can I?
      // But I'll just reject
      return Promise.reject(err);
    });
}

function doThisSecond(value, res) {
  return res.locals.something.someProp === 'mustBeLikeMe';
}

// Actual validation code:
req.assert('some_param', 'default failure message')
    .doThisFirst(res).withMessage('first thing failed')
    // This may get called first, and seems to always get called, but I don't want it to be called if doThisFirst fails
    .doThisSecond(res).withMessage('second thing failed');
```

But I am not getting any consistent or particular ordering/firing of the validations in the chain. Am I missing something? Do they go in order? Backwards order? They all go no matter what?

I would expect (and, in my case, need) the first validation in the chain to be executed first, as the 2nd validation in the chain relies on the first successfully adding something to `res.locals`. That's how it's related to https://github.com/ctavan/express-validator/issues/322. I could skip this is there was a way for a validation to somehow influence the `withMessage` from within the validation itself, which is how it's related to https://github.com/ctavan/express-validator/issues/302.

Any suggestions other than a middleware-based solution?

**Comment by gustavohenke** [comment]
Hi @newhouse, I'm sorry that I took this long to reply.

For now, the only suggestion I can make is to pass a context object which will hold a promise to the `doThisFirst` validation process. Then you simply do `context.promise.then(...)` in `doThisSecond`.

```js
function doThisFirst ( value, context ) {
  context.promise = asyncCall( value ).then( ... );
  return context.promise;
}

function doThisSecond ( value, context ) {
  return context.promise.then( () => asyncCall( value ) );
}
```

I'm adding your idea to the bag of v4 ideas I already have 👍

**Comment by gustavohenke** [comment]
Hi @newhouse, [v4.0.0 has been released](https://github.com/ctavan/express-validator/releases/tag/v4.0.0).
The new `check` APIs will run validators in sequence within a given validation chain.

Please check the README for complete docs, and also check the [upgrade guide](https://github.com/ctavan/express-validator/blob/v4.0.0/UPGRADE_GUIDE.md).

**Comment by newhouse** [comment]
thanks!
