### ISSUE TITLE
req.assert(').isBoolean() not validating properly

### ISSUE THREAD

**Issue by alexchuvand** [ctavan/express-validator#353]
req.assert(param, 'error message').isBoolean() not working

I am passing a boolean parameter to req.body but the validator is not going through and returns the error message. 

req.body.is_for_full_users: false
req.assert('is_for_full_users', 'is_for_full_users does not have a valid boolean value').isBoolean();
Using Node 7.10 and express-validator 3.2.10.

**Comment by gustavohenke** [comment]
Can you provide any further examples of your code?
I tried it locally and it worked.
