### ISSUE TITLE
isJSON should be called with a string

### ISSUE THREAD

**Issue by JoaoGiao** [ctavan/express-validator#355]
express-validator is not calling isJSON validator with a correct data type. It seems it is calling isJSON with a JSON object instead of a string. Take this example:

```javascript
req.checkBody({
    'foo': {
      isJSON: {
        errorMessage: 'Invalid Foo. It must be a JSON object.'
      }
    }
  });
```

The following request should validate correctly, but fails:
```shell
curl -s localhost:3000/qux -H \
	"Content-Type: application/json" -H "Accept: application/json" -X POST -d \
	'{"foo": {"bar": "baz"}}'
```

This one validates:
```shell
curl -s localhost:3000/qux -H \
	"Content-Type: application/json" -H "Accept: application/json" -X POST -d \
	'{"foo": "{\"bar\": \"baz\"}"}'
```

[isJSON](https://github.com/chriso/validator.js/blob/master/src/lib/isJSON.js) is implemented with `JSON.parse`, therefore it is expect a string.

**Comment by gustavohenke** [comment]
The first case fails because what you actually receive is an object, and not a JSON string, which is the second case.
And because validator works only with strings, the likely output of converting that object to string is `[object Object]` - clearly not a JSON.

**Comment by JoaoGiao** [comment]
Exactly, I need to support the first case. I would like my service's clients to send in a proper object  as value for the `foo` key, like so:

```json
{"foo": {"bar": "baz"}}
```
As it stands, they are forced to use escaping in order to pass the JSON Object as a string:

```json
{"foo": "{\"bar\": \"baz\"}"}
```

All the APIs I've consumed so far expect the first case, no need for manual escaping on the client side.

I can see two ways out:
- (hackish) JSON stringify the Object before sending it to [validator.js isJSON](https://github.com/chriso/validator.js/blob/master/src/lib/isJSON.js).
- (better) Implement a custom validation function that does not rely upon `JSON.parse` but rather checks if the datatype is a JS Object (since it was already parsed by express).

**Comment by gustavohenke** [comment]
> I would like my service's clients to send in a proper object as value for the foo key

Then lay it out as various rules.

```js
req.checkBody('foo.bar').notEmpty();
req.checkBody('foo.baz').isAlpha();
```

And etc.
