### ISSUE TITLE
conflicts with @types/bluebird ~3.0.36

### ISSUE THREAD

**Issue by hansmaad** [ctavan/express-validator#357]
Is there a reason why you use older typings for bluebird? These do conflict with other packages, while bluebird itself (^3.4.0) can be resolved to 3.5.0.

```
  "dependencies": {
    "@types/bluebird": "~3.0.36",
    "@types/express": "~4.0.34",
    "bluebird": "^3.4.0",
  },
  "devDependencies": {
    "express": "4.12.3",
  },
```

Can we change to 
```
  "dependencies": {
    "@types/bluebird": "^3.4.0",
    "bluebird": "^3.4.0",
  }
```

**Comment by gustavohenke** [comment]
No reason, probably it was simply not available when the original typings were developed.
