### ISSUE TITLE
usage not updated from depreciated functions

### ISSUE THREAD

**Issue by hawleye** [ctavan/express-validator#359]
since I can not use req.getValidationResult() as it has been depreciated, how am I supposed to gather the error array to pass back to my html? this is the function you say to use in your documentation. 
yet, if I use req.validationErrors(), like the tutorial I am watching says to, it ignores all errors and your documentation names it as 'will be depreciated'.

using express 4.15.3, ejs 2.5.6, express-validatior 3.2.0  on linux mint 17.3

**Comment by gustavohenke** [comment]
I think you're making some confusion here.

[These are the deprecated methods](https://github.com/ctavan/express-validator#deprecated-api):
- `req.validationErrors`
- `req.asyncValidationErrors`

You should definitely be using `req.getValidationResult()`, which is way more stable, and less weird than the other two mentioned above.
