### ISSUE TITLE
Next release ?

### ISSUE THREAD

**Issue by nicolashenry** [ctavan/express-validator#362]
When will come the next release? I am waiting for the latest typing changes on the master branch. 
Thanks!

**Comment by gustavohenke** [comment]
Hi @nicolashenry! I just published v3.2.1 🚢.
I'm so sorry for taking this long to reply! Enjoy it!

**Comment by GitStorageOne** [comment]
@gustavohenke Hello! same question appear, when next version will be released?  
Current version can't pass compile with typescript, but issue was fixed, looking forward to see release!
