### ISSUE TITLE
TS2339:Property 'checkBody' does not exist on type 'Request'.

### ISSUE THREAD

**Issue by veerandev** [ctavan/express-validator#363]
Using v3.2.0 in typescript, getting TS2339:Property 'checkBody' does not exist on type 'Request'.
As of v3.1.0, the type definitions are shipped with the library. What else could cause this issue?

```
public add(req: express.Request, res: express.Response, next: express.NextFunction) {
    ...
     if(req.checkBody('name', 'Invalid name').isValidInput()){
       
        ...
     }

```

**Comment by veerandev** [comment]
public add(req: **any**, res: express.Response, next: express.NextFunction) {
    ...
     if(req.checkBody('name', 'Invalid name').isValidInput()){
       
        ...
     }

**Comment by gustavohenke** [comment]
Have you uninstalled old typings from DefinitelyTyped? If you have both you're likely to get conflicts.

**Comment by gustavohenke** [comment]
Also, try v3.2.1, as it ships with lots of typings improvements.

**Comment by chrstntdd** [comment]
I'm having this same issue. I uninstalled `@types/express-validator` and don't have any other type definitions in my project, but keep getting errors about many of the validator properties not existing on the `Request` type.
