### ISSUE TITLE
Pushing custom error message to req.getValidationResult() ?

### ISSUE THREAD

**Issue by d30jeff** [ctavan/express-validator#364]
I was wondering if there's a way to push a custom validation error in `req.getValidationResult()`

When I'm validating an **email** against the database, I would like to push my own custom error message somewhere to be used in `req.getValidationResult()`, so that I don't have to format it myself.

I understand that I could achieve this by importing the model and doing my custom validation in the middleware, but that's not an option, at least for me.

Please refer to the code snippet with the numbered comments below to have a better understanding of what I'm trying to achieve.

Sorry for bad English.

```
req.checkBody({
  // Validate email
  email: {
    isEmail: {
      errorMessage: 'invalid'
    },
    isLength: {
      options: [{ max: 150 }],
      errorMessage: 'too_long'
    },
  }
})

// 1. Check existence of email in database.
// 2. If already exists, push custom error message to req.getValidationResult() or something.

let errors = await req.getValidationResult()

if (errors.isEmpty() === false) {

  //3. Nicely formatted error here if validation passes but email exists in database.

  return res.status(400).json({
    type: 'validation'
    errors: errors.
  })
} else {
  // Validation passes
}

```

Thank you

**Comment by gustavohenke** [comment]
This is not possible *yet*, so for now your only option is to go with `customValidators` 😐

**Comment by d30jeff** [comment]
Thanks 👍

**Comment by gustavohenke** [comment]
I'm leaving it open because I have some ideas on how to implement this 😉

**Comment by gustavohenke** [comment]
While [version 4.0.0 was released](https://github.com/ctavan/express-validator/releases/tag/v4.0.0), it doesn't include any way to push external errors to the express-validator engine.

You must use one a custom validator to do this in a supported way:

```js
app.post('/route', check('email').isEmail(), (req, res, next => {
  req.myEmailPromise = doSomethingWithTheEmail(req.body.email);
  next();
}, check('email').custom(value, { req }) => {
  // do something with that promise
  return req.myEmailPromise;
}, (req, res, next) => {
  // do something with the validation result
});
```
