### ISSUE TITLE
TypeScript: (re)enable possibility for declaration merge

### ISSUE THREAD

**Issue by sGy1980de** [ctavan/express-validator#369]
Before version 3.2.1, it was possible to declare own validators and sanitizers via declaration merging, simply using something like this in a `.d.ts` file.
```typescript
/// <reference types="express-validator" />
declare namespace ExpressValidator {
    interface Validator {
        isArrayOfInt(): this;
    }

    interface Sanitizer {
        toArrayOfInt(): this;
    }
}
```

I could not find a way, to achieve this with v.3.2.1 and furthermore no hints from Microsoft or any other resource how to extend interfaces from packages, using the `export as namespace` syntax.

```typescript
// index.d.ts
// v.3.2.0 and before
declare module "express-validator" {
// snip...
}

// since v.3.2.1
export as namespace ExpressValidator;
```

If there is a way to declare custom handler, please provide some documentation, how to do so. Otherwise please consider to roll back to the old syntax as i can't see any advantages.

**Comment by gustavohenke** [comment]
Can you try something like this commit?
a8dde3138b5edabfe12c318404f14c1d78205e32

The advantages are that you can now use ES6 import syntax instead of typescript syntax :)

**Comment by sGy1980de** [comment]
Thanks for your help. Works like a charm.
