### ISSUE TITLE
Use custom validators in validation schema

### ISSUE THREAD

**Issue by ektachawla** [ctavan/express-validator#376]
Hi,

I have a json schema which is an array of nested json objects and need to do validations using validation schema. As i understand, need to define custom validators to parse array and do validations, but not able to use those custom validators in the schema that i want to define to be used in req.check(). Below is my sample json along with basic custom validator. Please suggest how to use it in schema.

Sample Json: 
```js
{ orders : [
{'interval':
{ 'startDateTime':'startDateTime'}
}
]}
```

Custom validator:

```js
this.app.use(expressValidator({customValidators: {
  eachIsEmpty: function (values, prop) {
    return values.every(function (val) {
      var propArr = prop.split('.');
      var propKey;
      return validator.isEmpty(val[propArr[0]][propArr[1]]);
    });
  }
}
}));
```

Many Thanks!

**Comment by thecamarada** [comment]
I've just had the same problem. Could not find any solution for custom validators on schemas.
I opted for linear validation (programmatically)

`
req.assert('name', 'Name is required').notEmpty();
req.assert('name', 'Name must be between 2 and 70 chars').isLength({min : 2, max : 70});

return req;
`
Using this at least i could manipulate better the error messages, also it works with custom validators, just change the **notEmpty().** or the **isLength()** to your custom method.

But a schema validator should accept custom validations. Think about it.

**Comment by gustavohenke** [comment]
Since none of you were kind to provide a failing test case, I added one that is what I expect to work, and it passes: d611aa32230dc45f9d9ff21b05f09952953635d1

**Comment by gustavohenke** [comment]
👆 if your code doesn't look like that, and you think that it should be supported, please open a new issue.
Otherwise is just a usage problem.
