### ISSUE TITLE
isAlpha() failing on AlphaNumerics

### ISSUE THREAD

**Issue by SamJWeissman** [ctavan/express-validator#377]
Not sure if isAlpha should be failing when numerics are included 
IE: req.checkBody('key', 'invalid message').isAlpha() //passes when 'key' refers to 'asdasd'
     req.checkBody('key', 'invalid message').isAlpha() //fails when 'key' refers to 'asdasd2'

--- couldn't find a separate isAlphaNum, or isAlphaNumeric. Is there a separate checkBody test I should be using to determine whether something is a combination of characters and numbers?

Thank you in advance!

**Comment by gustavohenke** [comment]
You were almost there, the correct name is `isAlphanumeric`.

For reference, look at [validator.js](https://github.com/chriso/validator.js)'s methods. 
All validators express-validator provides come from this module.

**Comment by SamJWeissman** [comment]
Ahh, sorry for the stupid question!

Thank you!
