### ISSUE TITLE
help needed: TypesScript and module/namespace augmentation for custom validator

### ISSUE THREAD

**Issue by eliprand** [ctavan/express-validator#378]
Hi,
I am really enjoying this library. But I finally got around to building a custom validator in my NodeJS + TypeScript project.
And I cannot figure out how to augment the `Validator` interface to support my `isPassword()` custom validator.
Any pointer appreciated.

**Comment by eliprand** [comment]
Alright,
It took me way more time than I really wanted to spend on this, but I think I have figured it out.

First, the declaration file (let's call it `augment.ts`):
```typescript
import 'express-validator';

declare module 'express-validator' {
    interface Validator {
        isPassword(): Validator;
    }
}
```
Next,  well, there is nothing else. As long as the file is compiled as part of the project, the declaration will be imported. This will work with the current version of the `index.d.ts` (_v3.2.1_).

Just beware that will let you use `isPassword()` even if you don't actually hook to the pipeline using `validator()`.

**Comment by gustavohenke** [comment]
> Just beware that will let you use isPassword() even if you don't actually hook to the pipeline using validator().

Yes, unfortunately there's no way around this so far because express-validator is decorating the request object 😞

**Comment by eliprand** [comment]
No worries. I just wanted to leave a note for others. I know this is a necessary evil in TS for now.
