### ISSUE TITLE
Update validator.js version to supports fa-IR locale

### ISSUE THREAD

**Issue by peZhmanP** [ctavan/express-validator#380]
Hi 
The latest version of validator.js (v8.0.0) supports _fa-IR_ locale, but current express-validator package depend on validator.js v6.2.0. 
Please update validator.js dependency so that we can use express-validator with fa-IR locale. Thanks

**Comment by jiayuzhang** [comment]
Upvote!
v6.2.0 doesn't support isMobilePhone({locale:'any'}) and many other things ;(

**Comment by gustavohenke** [comment]
Hi folks,
I'm planning to follow semver and bump major version whenever validator bumps as well.

That being said, version 4 is on the way, including a bunch of new beautiful features 😉

**Comment by gustavohenke** [comment]
[Version 4.0.0 released](https://github.com/ctavan/express-validator/releases/tag/v4.0.0)!

validator has been updated to v8.1.0 in this release.
Also make sure to check [the upgrade guide](https://github.com/ctavan/express-validator/blob/v4.0.0/UPGRADE_GUIDE.md) in case you're coming from v3.x.x.
