### ISSUE TITLE
Is it possible to check which combination of req.body properties has been sent by client?

### ISSUE THREAD

**Issue by codefactorydevelopment** [ctavan/express-validator#382]
How can we access `req.body` in validator?

We have a need to inspect the combination of properties (not their values, but properties) client has sent to an API endpoint. So, we don't want to validate any particular property value but we need to access `req.body` in validator and then do validation based on `Object.keys(req.body)`.

Is there an elegant way of doing something like that?

**Comment by gustavohenke** [comment]
You can use a custom validator like `isNotUndefined`:

```js
app.use(expressValidator({
  customValidators: {
    isNotUndefined: value => value !== undefined
  }
}));

app.get('/', (req, res, next) => {
  req.checkQuery('foo').isNotUndefined();
  req.checkQuery('bar').isNotUndefined();  
  // or...
  req.checkQuery({
    foo: {
      isNotUndefined: true
    },
    bar: {
      isNotUndefined: true
    }
  });
});
```

Let me know if it helps.

**Comment by codefactorydevelopment** [comment]
@gustavohenke 

Thanks for your reply!

We were actually thinking something more in lines like this:

1) we define an array of allowed properties that user can send in req.body. for example:

`var allowedParams = ['param1', 'param2', 'param3']`

2) in validator, we would like to have something like (pseudo code):

`req.checkBody().checkIfItContainsParamsOutOfAllowedArray(allowedParams)`

We do it now manually and throw custom exceptions appropriately, but we'd like to have it within usual validator workflow with custom messages and other checks.

Thanks!

**Comment by gustavohenke** [comment]
I see.
Unfortunately the most terrible way I could think of is to really use something like you mentioned:

```js
req.checkBody('foo').containsItAndAlsoOtherParams(req.body, otherParams);
```

And, just to generate some hype...
This is something I could bake into version 4, soon to be released. See #383 for some preview 😉

**Comment by codefactorydevelopment** [comment]
Thanks for your response!

Thats one possible way, but not for our case where all properties are nullable ;)

It would be awesome to have it. Actually, it would be perferctly enough to have body somehow exposed, so `req.checkBody()` without params on top of which we could then implement custom validators.

**Comment by gustavohenke** [comment]
Hi @codefactorydevelopment, this is now possible with the release of [v4.0.0](https://github.com/ctavan/express-validator/releases/tag/v4.0.0) 😃 

```js
const { checkBody, validationResult } = require('express-validator/check');

app.post('/your-route', checkBody(allowedParams).exists(), (req, res, next) => {
  const result = validationResult(req);
  // do something with the result object
});

// or, if you would like to keep a v3-style API..
app.post('/your-route', (req, res, next) => {
  req.checkBody('param1').exists();
  req.checkBody('param2').exists();
  req.checkBody('param3').exists();
});
```

In case this is not enough for you, you can also use more powerful custom validators (with `check` APIs only):

```js
const { checkBody, validationResult } = require('express-validator/check');

app.post('/your-route', checkBody(allowedParams).custom((value, { req, location, path }) => {
  // do your custom validation with the full request available to you!
}), (req, res, next) => {
  // ...
});
```

Thanks, and go check the README for the complete docs of v4!

**Comment by cavalos0086** [comment]
What is the equivalent when using schema validation? i.e 
```
checkSchema({
   param1: {
      // ? what should we put here to ensure that the param1 has been provided?
   }
})
```

**Comment by gustavohenke** [comment]
It should be `{ exists: true }` as well @cavalos0086!
