### ISSUE TITLE
Update declaration files for 4.0.0

### ISSUE THREAD

**Issue by Deilan** [ctavan/express-validator#390]
Please update declaration files for 4.0.0.

**Comment by gustavohenke** [comment]
Can you please describe what's your issue?

**Comment by Deilan** [comment]
For example:

![image](https://user-images.githubusercontent.com/4777512/29786846-610cb730-8c35-11e7-937e-1f083c487f34.png)

**Comment by gustavohenke** [comment]
v4.1.0 published with the fix. Please try it out and let me know of any problems.
