### ISSUE TITLE
What is the best way to customize returned errors?

### ISSUE THREAD

**Issue by williamdang1710** [ctavan/express-validator#392]
In legacy API (which is now deprecated), I can define an global `errorFormatter()`. How can I achieve
the same behavior in the new version?

**Comment by mitjarogl** [comment]
👍

**Comment by gustavohenke** [comment]
Please see #393 - Unfortunately error formatters were out of the v4.0.0 release 😊

**Comment by gustavohenke** [comment]
v4.1.0 published with the new `.formatWith(formatter)` method in the validation result API.

Please try it out and let me know of any problems.
