### ISSUE TITLE
Do I can to use schema validation in v4?

### ISSUE THREAD

**Issue by vitaliybilous** [ctavan/express-validator#394]
Before v4 I used this type validation:
```javascript
req.checkBody({
  email: {
    notEmpty: true,
    isEmail: true
  },
...
});
```
How I cat to use it now for v4?

**Comment by gustavohenke** [comment]
The check API don't have any way to specify a schema like that, using an object. At least for now...
You can, however, pile express middlewares; the effect should be the same:

```js
app.get('/route', [
  check('email').isEmail().custom(value => findInDB(email)),
  check('password').isLength({ min: 5 })
], (req, res, next) => {
  // :D
});
```

Please note that the legacy API still works if you use it like you used to use in v3.
You don't need to migrate your code.
