### ISSUE TITLE
@types/express-validator - Property MappedError.msg arrives as MappedError.message throwing an warning

### ISSUE THREAD

**Issue by tuliobraga** [ctavan/express-validator#395]
At the file shared-typings.d.ts, the MappedError interface is defined as follows:

export interface MappedError {
  param: string;
  msg: string;
  value: string;
  location: Location
}

Internally, a property called MappedError.message is set instead of MappedError.msg (that remain undefined). When using the package, devs must call MappedError.message. Doing so, it throws the following warning since the typings do not define any MappedError.message property:

error TS2339: Property 'message' does not exist on type 'MappedError'.

**Comment by gustavohenke** [comment]
Why did you close? Isn't this a problem anymore?

**Comment by tuliobraga** [comment]
I was about to comment what happened. It was an errorFormatter customization that changed the msg to message in the project I was working. Not a problem with the lib.

**Comment by gustavohenke** [comment]
Since v4.1.0, changing the shape of the error object is totally acceptable.
Therefore the `MappedError` interface should probably give way to... `any`? 😕
