### ISSUE TITLE
Invalid value error

### ISSUE THREAD

**Issue by faridkhooie** [ctavan/express-validator#400]
![screenshot_20170831_050446](https://user-images.githubusercontent.com/31448871/29900930-361b74ae-8e0a-11e7-8ea9-8302fdaf31a6.png)
I am using node.js 8.4 and express-validator 4.1
I try to use custom validator with .custom() for checking array . 
but I get invalid value error 
![screenshot_20170831_051138](https://user-images.githubusercontent.com/31448871/29901025-e4eaa32e-8e0a-11e7-957f-84f1f7f879e9.png)

**Comment by gustavohenke** [comment]
Please use `reject(new Error('workTime must be an array'))` for now.

I'll add support for rejecting with strings as well.

**Comment by gustavohenke** [comment]
Fix published in v4.1.1.

**Comment by TheShadowfax** [comment]
Hi Everyone,
I was tryingout this validation check, inspite of providing source as dApp
im getting the error saying **invalid value** for source.
here's my validation code
`body("source") .exists() .withMessage("Source field is mandatory") .isIn(["dApp", "stanAPI"]) .withMessage("Value for source type is unknown") .custom((value, { req }) => { if (value == "dApp") { console.log(value); body("deviceID") .exists() .withMessage("Device id is required to login") .not() .isEmpty() .withMessage("Device id cannot be empty"), body("loginType") .exists() .withMessage("Login type is mandatory") .isIn(["qr", "pwd"]) .withMessage("Login type is of unknown type") .custom((value, { req }) => { console.log(value); if (value === "qr") { body("qrCode") .exists() .withMessage("Qr-Code is required to login") .not() .isEmpty() .withMessage("Qr-Code is cannot be empty"); } else { body("ambID") .exists() .withMessage("AmbID is mandatory") .not() .isEmpty() .withMessage("AmbID is cannot be empty"), body("pwd") .exists() .withMessage("pwd is mandatory") .not() .isEmpty() .withMessage("pwd is cannot be empty"); } }); } else return true; })`

and here is my request

`curl -X POST \ http://localhost:5000/subscription \ -H 'cache-control: no-cache' \ -d 'source=dApp'`
