### ISSUE TITLE
Custom error formatter problem

### ISSUE THREAD

**Issue by mitjarogl** [ctavan/express-validator#401]
I've noticed that global errorFormatter is still available in v4. I use same code as I did in v3
but I get this error:

`msg.replace is not a function
at args.reduce (/vagrant/node_modules/express-validator/lib/utils.js:36:47)
`

Example check
`req.check('name', {msg: 'Name must be between 2 and 50 characters', code: 331});`

**Comment by gustavohenke** [comment]
Fix published in v4.1.1.

**Comment by andrey-hohlov** [comment]
@gustavohenke
```
.withMessage({ foo: 'bar' })
```
It works, but IDE signal about wrong argument type.
Maybe set 'any' too?

**Comment by gustavohenke** [comment]
Thanks for the heads up, @andrey-hohlov!
I'll be publishing the fix soon.
