### ISSUE TITLE
How to use sanitize with new API (v4)? Using req.sanitize() fails.

### ISSUE THREAD

**Issue by deepakduggirala** [ctavan/express-validator#402]

**Comment by ijohn** [comment]
I asked the same question in #397 

@gustavohenke gave example of accessing `validator` using `require('validator')`. However that will only work if you have `validator` as your dependency.

You can access the sanitizers like so:
```
const { trim } = require('express-validator').validator
```
Just change `trim` to whatever sanitizers you need.

**Comment by gustavohenke** [comment]
Hi folks!
Sanitization is available starting with v4.2.0  :)

Check the docs for details on how to use it!
