### ISSUE TITLE
check('cpassword').isEmpty().withMessage('ERROR_CANNOT_EMPTY')

### ISSUE THREAD

**Issue by JackDarth** [ctavan/express-validator#408]
I want to check if field is empty or cannot be empty. However the following did not work for me. 
check('cpassword').isEmpty().withMessage('ERROR_CANNOT_EMPTY')

**Comment by gustavohenke** [comment]
> I want to check if field is empty or cannot be empty

This is confusing, what exactly do you want?

The example you gave is for checking whether a field *is* empty. If it's not, then a validation error will be set.

**Comment by JackDarth** [comment]
the cpassword field is required, how can I check it?

**Comment by gustavohenke** [comment]
Use `check('cpassword').exists()` or `check('cpassword').not().isEmpty()`
