### ISSUE TITLE
TypeError: err.mapped is not a function

### ISSUE THREAD

**Issue by KayUOM** [ctavan/express-validator#411]
Hi,

Can someone explain to me why something like this is not working

POST: http://localhost:3000/api/account/

account.route.js
```
'use strict';

var express    = require('express');
var router     = express.Router();
var controller = require('../controllers/account.controller');
controller     = new controller();
var request    = require('../requests/account.request');
request        = new request();

router.get('/', controller.index.bind(controller));
router.get('/:id', controller.show.bind(controller));
router.post('/', request.store, controller.store.bind(controller));
router.put('/:id', controller.update.bind(controller));
router.delete('/:id', controller.destroy.bind(controller));

module.exports = router;

```

account.request.js
```
'use strict';

const {check, validationResult} = require('express-validator/check');

class AccountRequest {
    
    store(req, res, next) {
        
        check('username').exists();
        check('countryCode').exists();
        
        try {
            validationResult(req).throw();
            next();
        } catch (err) {
            res.status(422).json({errors: err.mapped()});
        }
    }
}

module.exports = AccountRequest;
```

account.controller.js

```
'use strict';
var User = require('../models/user.model');
var Token = require('../models/token.model');
var AccountRepository = require('../repositories/account.repository');

class AccountController {

    constructor() {
        this.accRepo = new AccountRepository();
    }

    index(req, res) {
    }

    show(req, res) {
    }

    update(req, res) {
    }

    store(req, res) {
      return res.json("sucess")
    }

    destroy(req, res) {
    }
}

module.exports = AccountController;
```

I get a message:

"TypeError: err.mapped is not a function"

**Comment by gustavohenke** [comment]
You're using the check API wrong.

`check()` methods return middlewares. Such middlewares must be passed to express routes.
When you call `validationResult(req).throw()`, **no validators ran**. What actually gets thrown is another error, `TypeError: Cannot read property 'length' of undefined`. 

And because you are catching it, that error doesn't show up, but then you try to call `.mapped()` on top of it, which actually doesn't exist in standard JS errors.

I'll fix the express-validator code to make sure this doesn't happen again, but please check the docs for the correct usage.

**Comment by KKHAN1991** [comment]
I know, so how can i use your new API with the classes ive made?

**Comment by gustavohenke** [comment]
You can make the methods return an array of middlewares:

```js
class MyController {
  someMethod () {
    return [
      check('username').exists(),
      check('password').exists(),
      (req, res, next) => {
        const errors = validationResult(req); // do something with the validation result
      }
    ];
  }
}
```

and, in the routes file:

```js
const ctrl = new MyController();
app.post('/login', ctrl.someMethod(), otherRouteHandlerPerhaps);
```

**Comment by KayUOM** [comment]
Hi i tried this.

'''
 return [
            check('username').exists(),
            check('password').exists(),
            (req, res, next) => {
                const errors = validationResult(req); // do something with the validation result
                console.log(errors);
                if (errors) {
                    return res.status(400).json({
                        
                        success: false,
                        status: 400,
                        data: errors,
                        message: "Validation Failed",
                        
                    });
                }
            }
        ];
'''

But postman request just constantly loading, it does not even console log those errors...

What am i doing wrong here? I want to be able to return a response with the errors.

**Comment by gustavohenke** [comment]
Can you please migrate your question to StackOverflow?
This is getting out of scope, since your problem is hanging to the express usage side of things.

**Comment by KayUOM** [comment]
It's okay i chose to use legacy api, it works the way i expected now.

This is just how i use to do it before the update, I imagine its to much of a change. if i need to create another post to get an answer...

**Comment by gustavohenke** [comment]
It's not "too much of a change", it just starts to get too nebulous, since we'll need to debug your code to find what's wrong.
