### ISSUE TITLE
How to use customvalidator

### ISSUE THREAD

**Issue by milinmestry** [ctavan/express-validator#413]
Hi,

Can you please explain with an example about **custom validator**. 
https://github.com/ctavan/express-validator#customvalidator.

**Comment by gustavohenke** [comment]
Yes.
Custom validators may be used for anything that's not available by default in [the validator library](https://github.com/chriso/validator.js).

A classic example is checking whether the password confirmation matches the given password:

```js
app.post('/create-user', [
  check('password').exists(),
  check('passwordConfirmation', 'passwordConfirmation field must have the same value as the password field')
    .exists()
    .custom((value, { req }) => value === req.body.password)
], loginHandler);
```

I added this same example to the docs.

**Comment by milinmestry** [comment]
Thanks, @gustavohenke for your reply. I will definitely try this, the way you have shown with the example. I have used another approach to validate unique data in the database and I have created a gist for this.
I would like you to please take a look and do let me know your valuable input about this-
https://gist.github.com/milinmestry/a62a7f41976cf7d4a051b35b916af685

**Comment by gustavohenke** [comment]
Hi @milinmestry! Your approach works fine.
I can also suggest you a full express-validator approach, using the legacy APIs like you are using:

```js
// In your express app definition
app.use(expressValidator({
  customValidators: {
    genreNotExists (value, genreId) {
      return Genre.find().isGenreExists(value, genreId).exec();
    }
  }
}));

// Within your route handler
req.checkBody('name')
  .notEmpty().withMessage('Genre name required')
  .genreNotExists(req.params.id).withMessage('Genre already exists');

// or you could also use req.getValidationResult() :)
req.asyncValidationErrors().then(() => {
  // validation passed
}, errors => {
  // validation failed
});
```

**Comment by veritimus** [comment]
Hi @gustavohenke!
Could you show an example with checking if email posted in form is already in db?
I am actually working on validation to forms in my app and everything works fine except my custom validations checking db and I don't know what am I doing wrong.

Let me show you some portion of my code:

```
router.post('/profile/edit', [
   check('email', 'Invalid email format.')
      .optional({ checkFalsy: true })
      .isEmail()
      .custom((value, { req }) => {
         return new Promise((resolve, reject) => {
            User.findOne({ 'email': value }, (err, user) => {
               if(user !== null) {
                  return reject();
               } else {
                  return resolve();
               }
            });
         });
      }).withMessage('This email is already in use'),
   check('password', 'Password must contains 8-25 signs (numbers and letters)')
      .optional({ checkFalsy: true })
      .isLength({ min: 8 })
      .matches(/^[0-9a-zA-Z]{8,}/),
   check('passwordConfirm', 'Passwords must be equal.')
      .exists()
      .custom((value, { req }) => value === req.body.password)
], (req, res, next) => {
   const errors = validationResult(req);
   
   if(!errors.isEmpty()) {
      return res.render('profile-edit', {
         errors: errors.mapped()
      });
   }

   const data = matchedData(req);
   console.log(data);

   res.redirect('/profile');
});
```

I receiv error about email already in use, no matter if it really exists in db or not.
i suppose it's because of async nature of what I want to achieve.
Thanks in advance!

**Comment by soubhikchatterjee** [comment]
@veritimus This is what you can do

    const _ = require("lodash");

    check("email")
      .custom(async (value, { req }) => {
        let user = await User.findOne({ email: value });

        if (!_.isEmpty(user)) {
          return false;
        }
      })
      .withMessage("Email already exists"),

**Comment by sameerjalnapurkar** [comment]
A custom validator may return a Promise. Now, if the promise is eventually rejected with a particular error string, is there a way to make that string show up in .withMessage()? Thanks for any suggestions.

**Comment by gustavohenke** [comment]
You have to omit `.withMessage()` if you wish the custom validator's rejection cause.

**Comment by sameerjalnapurkar** [comment]
Thanks for the helpful reply! So its seems that the error message for a custom validator is -
- the string given as an argument to `.withMessage()`, in the absence of which we get
- the error string with which the promise was rejected, in the absence of which we get
- the second argument to check()

**Comment by gustavohenke** [comment]
Yes, correct @sameerjalnapurkar! There's also the default of `Invalid value`.

**Comment by samirfor** [comment]
> @veritimus This is what you can do
> 
> ```
> const _ = require("lodash");
> 
> check("email")
>   .custom(async (value, { req }) => {
>     let user = await User.findOne({ email: value });
> 
>     if (!_.isEmpty(user)) {
>       return false;
>     }
>   })
>   .withMessage("Email already exists"),
> ```

`async` saves me
