### ISSUE TITLE
wildcards docs

### ISSUE THREAD

**Issue by shablenko** [ctavan/express-validator#414]
Where can i look at documentation for wildcards?
Is there some other shortcuts `*`, i need something that can check if array contains at least one item with property and value i need

**Comment by gustavohenke** [comment]
Wildcards replace a single level of the field path.
In this case, the field path must be written like you would for JS objects, using dot-notation:

```js
[
  // This makes sure the array was passed in the request
  check('array').exists(),
  // This makes sure every item of array has a key "key" whose value is "value"
  check('array.*.key').isEqual('value')
]
```

Thanks for asking -- your question made me see that further docs around field selection are needed.
