### ISSUE TITLE
How to use sanitize with V4 API?

### ISSUE THREAD

**Issue by SteveCorbett** [ctavan/express-validator#417]
I have spent way more time than I will admit attempting to overcome a very basic edit of a form field, how to make sure that an entry is not empty or just contains blanks using the recommended V4 style.  This issue has been raised previous issues, including #402 and #397.  It appears that using V4 the only options are: 
1. Including other libraries (which are already used in express-validator) to do this.
2. Use a combination of V3 and V4 validation.
3. Create a custom validation method for every input field.
4. Add sanitation to the check method. 
5. Just use validator without express-validator.

Which ever method is used should be clearly documented with a working example.

**Comment by gustavohenke** [comment]
Just adding a reference for the SO question you came from... https://stackoverflow.com/questions/46213401/trim-input-values-before-express-validator-in-node-js

Your question made clear to me the need for an embedded sanitization support.
Will implement it soon.

**Comment by SteveCorbett** [comment]
Thanks Gustavo, sorry that I'm not proficient enough in Js to help out on this. 

Regards 

Steve
Ps Thanks for your ongoing contributions to the open source community.

**Comment by gustavohenke** [comment]
This is now released with v4.2.0 🚢 

Full list of released features: https://github.com/ctavan/express-validator/releases/tag/v4.2.0

**Comment by tudor33sud** [comment]
Are there any plans to support custom sanitization also? I'm not able to do this in the new V4 API. 

Maybe something like you do with the check method, being able to use sanitize('field').custom(customFunction).

Thanks for your efforts
