### ISSUE TITLE
Sanitize an optional parameter

### ISSUE THREAD

**Issue by giacomocerquone** [ctavan/express-validator#425]
Hi everybody, thanks for your work! This is a great module :)

I have this check: `check('url').optional()` and I'd like to sanitize it escaping the string.
So I obviously did: `check('url').optional().escape()` but it returns TypeError from validator.js telling me that it isn't a string (when the value isnt't there right because it's optional)

How can I handle this?

**Comment by giacomocerquone** [comment]
Duplicate of the closed #205 apparently

**Comment by gustavohenke** [comment]
Not really; your issue is with express-validator v4, and #205 is from v2 age.

Anyway, I can see the bug in the code. Thanks for pointing it out.

**Comment by giacomocerquone** [comment]
I know #205 is from v2, but the user reported a behavior that is exacyly the same that I encountered.

Anyway I'd love to have time to make a PR... I'll see if it'll be possible!

**Comment by vne-trietdang** [comment]
Any update on this? Since `sanitize('notExistedField')` will throw the same error, too!

**Comment by gustavohenke** [comment]
Fix published in v4.2.1.
