### ISSUE TITLE
Converting from v3 to v4

### ISSUE THREAD

**Issue by fervaz** [ctavan/express-validator#426]
Hello folks!

I'm converting from v3 to v4 and I came across some doubts...

In my controller code I had the middleware in a router level, eg: `router.use(Model.validate);`

And then, in 'Model', I had the validation code where I can filter the method, eg:
```
exports.validate = function(req, res, next) {
    if (req.method === 'POST' || req.method === 'PUT') {
        req.check(...);
    }
    next();
}
```
How can I made similar approach in v4? It's wrong if I simple change the `req.check(...);` to `check(field)`? I understand that the new 'check' method creates a middleware in each call that automatically call's 'next()'. That's right?

Another issue I'm having during migration (which is leading me to keep the above model), is that in a given model I have a dynamic form according to a user's selection. So I did something like this:
```
exports.validate = function(req, res, next) {
    if (req.method === 'POST' || req.method === 'PUT') {
        usersChoice = req.body.selection;
        findNameById(usersChoice, function(err, name){
            if (err) { ... }
            UserChoice[name].validate(req, res, next); // For each possible selection, there was a validation logic with 'req.check (...)'
        })
    } else {
        next();
    }
}
```

It's possible to make something like this using the new v4 approach?

Thanks.

**Comment by gustavohenke** [comment]
Hi @fervaz!
I got a little confused on what is coming from in each case, but I assure you can safely migrate these function to the new check APIs.

In the first case, you can specify wildcard routes. Like this:
```js
// Works because express-validator will run on every POST or PUT request in this router,
// and it will never respond to your requests
router.post('/*', check(...));
router.put('/*', check(...));
```

In the second case, at the moment I can only suggest you to make `UserChoice[name].validate` look like this:

```js
Promise.all([
  check('foo').isBar(),
  check('foo').isBar()
].map(middleware => {
  return new Promise(resolve => middleware(req, res, resolve));
})).then(next);
```

Depending on what validations you are doing, it's possible to simplify this a lot.
Can you show some examples for them?
