### ISSUE TITLE
Global errorFormatter not used

### ISSUE THREAD

**Issue by jplusje** [ctavan/express-validator#427]
When I've provided an errorFormatter function during initialization, it's not always being used?

working example (the output is indeed being mapped by the provided errorFormatter function):
```
req.getValidationResult().then(result => {
  console.log(result.mapped());
});
```

not working example (the output is being formatted by the default errorFormatter function):
```
import * as expressValidatorCheck from "express-validator/check";

try {
  expressValidatorCheck.validationResult(req).throw();
} catch (err) {
  return res
    .status(422)
    .json({ errors: err.mapped() })
    .end();
}
```

Is this a bug or am I using this incorrectly?

**Comment by gustavohenke** [comment]
The check API doesn't have this concept of a default error formatter yet.
For now, you must call `.formatWith()` at every validation result.

Suggestions on how to implement this are welcome!

**Comment by insightcoder** [comment]
Would love to see this implemented as well.

**Comment by alrav** [comment]
Hello there @gustavohenke - I've created a proposal for default `validation-result` options - starting with error formatter: https://github.com/ctavan/express-validator/pull/474

Let me know if it's of interest to you 👍
