### ISSUE TITLE
Missing funcion isValidGPSLocation()

### ISSUE THREAD

**Issue by carlosen14** [ctavan/express-validator#430]
I would like to use that function. A simple Location, sometimes is Lat - Long separated by a comma, and sometimes has parenthesis, in a string "(12.123, 78.789)" , sometimes is an object { x: 12.123, y: 78.789 }.  

This would be very helpful to me.

**Comment by gustavohenke** [comment]
[validator](https://github.com/chriso/validator.js) provides this built-in with `isLatLong`, but you must pass a string in the format `-22.9132525,-43.7261763`.

For custom formats, you will need to use custom validators. Check the docs for reference on how to implement them.
