### ISSUE TITLE
how to format return

### ISSUE THREAD

**Issue by carvalhoviniciusluiz** [ctavan/express-validator#432]
Hello, how do i make for the validation response not return the msn parameter or location parameter ??

**Comment by gustavohenke** [comment]
**If you're using check API or legacy API with `req.getValidationResult()`:**
[Use `.formatWith()`](https://github.com/ctavan/express-validator#formatwithformatter)

**If you're using legacy API with `req.validationErrors()` or `req.asyncValidationErrors()`:**
[Pass the `errorFormatter` option when defining the middleware](https://github.com/ctavan/express-validator#middleware-options).

**Comment by carvalhoviniciusluiz** [comment]
how to create this global setting?
<pre>
  try {
    validationResult(req).throw()
  } catch (err) {
    err.formatWith(({param, msg, value, location}) => {
      return {
        param,
        msg,
        value
      }
    })
    return res.status(422).json({ err: err.mapped() })
  }
</pre>

**Comment by gustavohenke** [comment]
This is still not possible, unfortunately 😞 
You may want to track the related issue: #427
