### ISSUE TITLE
Custom validation with database

### ISSUE THREAD

**Issue by barrosfilipe** [ctavan/express-validator#435]
**It works:**

```
module.exports.postSignup = [
check('email', 'E-mail already in use').custom((value, { req }) => value !== 'barrosfilipe@test.com'),
...
```

**It doesn't:**
```
module.exports.postSignup = [
check('email', 'E-mail already in use').custom((value, { req }) => {
  value !== 'barrosfilipe@test.com'
}),
...
```

**The reason why I want to use the example that doesn't work is because I want to use MySQL query to validate if e-mail address is already in use. Something like this:**

```
module.exports.postSignup = [
check('email', 'E-mail already in use').custom((value, { req }) => {
  const db = require('../db');
  db.query('SELECT email FROM `users` WHERE email = ?'
      , [req.body.email], function(error, results, fields) {
        if (error) throw error;
        if (results.length > 0) {
          return value !== results[0].email;
        };
      });
}),
...
```
How should I do that? Any ideas?

Thanks!

**Comment by gustavohenke** [comment]
Eae @barrosfilipe 😉,

The example you gave as not working is because you're using an arrow function without a `return`.
`value => value` is the same as `value => { return value }`, but `value => { value }` is simply a function that evaluates `value`, without returning anything.

In the full example for DB validation, you are trying to return from within an async callback.
In this case, you should use promises instead.
For a detailed explanation, see [this popular StackOverflow question](https://stackoverflow.com/questions/14220321/how-do-i-return-the-response-from-an-asynchronous-call).

**Comment by littleindianboy** [comment]
Okay I get this.  But how do I go about throwing an error and have it maintain the same format that you would find if a 'check' command finds something wrong with a parameter/input?

**Comment by gustavohenke** [comment]
You should use promises for this. They must be rejected for the validation to be considered as failed.

**Comment by littleindianboy** [comment]
Here's my code.  I'm not sure what I'm suppose to put in the catch to properly throw the error.
```
		check('email', 'Please enter a valid email').isEmail().custom((value, { req }) => {
	      	new Promise(function(resolve, reject) {
		      	User.find({email: value}).exec((err, user) => {
					if (user) Promise.reject(new Error('This e-mail address is already in use'));
		      		else resolve();
				});
      		}).then(() => {
      			console.log('promise resolved')
	    	}).catch((e) => {
	    		// What do I put here to throw the error?
	    	})
	    }),
```

**Comment by barrosfilipe** [comment]
Hello @littleindianboy. It might not be the right way to that but here is how I did it.

@gustavohenke, do not "hit me" please! :worried:

```
module.exports.postSignup = [
check('username', 'Username must be between 4-15 chars long').isLength({ min: 4, max: 15 }),
check('username', 'Username already in use').custom((value, { req }) => {
  function getUsername() {
    return new Promise(function(resolve, reject) {
      const db = require('../db');
      db.query('SELECT username FROM `users` WHERE username = ?'
        , [req.body.username], function(error, results, fields) {
          if (error) return reject(error);
          resolve(results);
        });
    });
  }

  return getUsername().then(function(results) {
    if (results.length > 0)
      return value !== results[0].username;
    else
      return true;
  });
}),
check('email', 'E-mail cannot be blank').isEmail(),

. . .
```

**Comment by littleindianboy** [comment]
Okay I solved it.  Turns out I was missing... 🥇 
```
if (!errors.isEmpty()) {
	return res.status(422).json({ errors: errors.mapped() });
}
```
