### ISSUE TITLE
What am I doing wrong - I always get errors and req.body.password is undefined

### ISSUE THREAD

**Issue by jefflindholm** [ctavan/express-validator#436]
```
router.post('/register', [
    check('name', 'Name is required').exists(),
    check('email', 'Email is required, and must be an email')
        .isEmail()
        .custom((val) => {
            // find the user by email
            console.log(val);
            return true;
        }),
    check('username', 'Username is required').exists(),
    check('password', 'Passwords must be at least 5 characters and container one number')
        .isLength({ min: 5 })
        .matches(/\d/),
    check('password2', 'Passwords do not patch')
        .exists()
        .custom((val, { req }) => {
            console.log(val, req.body.password);
            return val === req.body.password;
        }),
], (req, res) => {
    const { name, username, email, password, password2 } = req.body;
    console.log({ name, username, email, password, password2 });
const errors = validationResult(req);
    if (!errors.isEmpty()) {
        console.log('we got errors');
        const obj = { errors: errors.mapped() };
        console.log(obj);
        return res.render('register', obj);
    }

    console.log('no errors');
    return res.status(200);
}
```

In the password 2 custom val and req.body.password are all empty, but when I console log the fields they are all there. Every value is coming back undefined.

All the examples show app.post(...) is that the problem? I am using express.Router()

**Comment by gustavohenke** [comment]
This doesn't seem right; how are you defining the body parser middleware?
Anywhere a middleware is accepted in express, express-validator should work just fine.

As a last resort, if we don't solve this quick enough, you could try migrating your code to the legacy API temporarily.

**Comment by gustavohenke** [comment]
ping @jefflindholm - are you still tracking this?

**Comment by gustavohenke** [comment]
Hi @jefflindholm, I went to your profile and saw you uploaded the app you're building with express-validator.

I checked the code where you are doing validations. Your example is different from the one in there!

Please see this SO question, as it must be pretty similar to what you're experiencing:
https://stackoverflow.com/questions/46046254/new-express-validator-syntax-validate-form-processed-by-multer

**Comment by jefflindholm** [comment]
I will take a look I had to travel this week unexpectedly so did not have
time to look
