### ISSUE TITLE
isMongoId return true in express-validator and false in validator.js

### ISSUE THREAD

**Issue by Younell** [ctavan/express-validator#438]
I think there is a conflict between express-validator and validator.js when I surround mongoid with spaces, here is the code to reproduce:

    const validator = require('validator');
    const { check, validationResult } = require('express-validator/check');

    app.get('/update/:id', [

        check('id').isMongoId()

    ], function(req, res) { 
    
        // validator.js check
        console.log( validator.isMongoId(req.params.id) );  // false

        // validation result
        var errors = validationResult(req); 

        // express-validator check
        console.log( errors.isEmpty() ); // true

        res.end();

    });

using valid mongoID as params: 
/update/59c1688c233ab748a1c220b8 => 

    true
    true

using invalid mongoID:
/update/foo =>

    false
    false

surround mongoID with spaces:
/update/%2059c1688c233ab748a1c220b8%20 =>

    false
    true

validator.js version 8.2.0
express-validator version 4.2.1

**Comment by gustavohenke** [comment]
Hm, I couldn't reproduce this. Can you set up a working example?

**Comment by Younell** [comment]
Sorry it's my mistake, I think I was starting 2 express process that's why I get that result, but now I have only one problem with trim function, it's not working at all, here is my example:

    validator = require('express-validator/check');

    app.get('/update/:id', [

        validator.check('id').isMongoId(),
        validator.check('name').isLength({ min: 1 }).withMessage('Required').trim()

    ], function(req, res) { 

        // show name length before validation
        console.log(req.body.name.length);

        // validation result
        var errors = validationResult(req); 

        // show name length before validation
        console.log(req.body.name.length);

        res.end();

    });

If I submit name=" foo " I get 5 as length, normally that should be 3 in the second console.log, do I miss something ?

**Comment by gustavohenke** [comment]
Ah, [the validation chain docs](https://github.com/ctavan/express-validator#validation-chain-api) probably need further enhancements in this area.

What happens is: **when you use sanitizers in the validation chain, they are only applied during validation time**.
If you would like to keep the sanitized value, then you should use the `sanitize` functions from `express-validator/filter`.

**Comment by Younell** [comment]
What does "applied during validation time" mean ?
If I do : 
`check('name').isLength({ min: 1 }).withMessage('Required').trim()`
This should check if name length is greater than 1 and then remove whitespace from the beginning and end. but the req.body.name still the same with whitespaces..
I can't understand the purpose of trim function

**Comment by gustavohenke** [comment]
As I said, it's applied *only* during validation time. If a user inputs ` `, then your `name` validator above will fail, because trimmed that value has a length of 0.
Outside the validator, `req.body.name` will still be ` `.

Perhaps this behaviour could be changed; [`matchedData`](https://github.com/ctavan/express-validator#matcheddatareq-options) is always returning the sanitized value 🤔 

Also remember that using it is an option to accessing each property `req.body`, `req.query`, etc.
