### ISSUE TITLE
How to validated req.params new api

### ISSUE THREAD

**Issue by carvalhoviniciusluiz** [ctavan/express-validator#442]
Hello,
How do I validate the req.params with the new api?

**Comment by gustavohenke** [comment]
Have a  look at the [check API](https://github.com/ctavan/express-validator#check-api) and the [usage section](https://github.com/ctavan/express-validator#usage).

**Comment by carvalhoviniciusluiz** [comment]
Sorry, I did not hit  how to validate

```
export const rules = [
  check('id').exists().custom((value, { req }) => {
    const { id } = req.body.params
    return id.match(/^[a-fA-F0-9]{24}$/)
  })
]

router.get('/:id', rules, controller.show)
```
my retorn _'Cannot read property \'id\' of undefined'_
Which is right?
