### ISSUE TITLE
Add notNull 

### ISSUE THREAD

**Issue by zatziky** [ctavan/express-validator#443]
I haven't found a simple option how to express `notNull` but using `custom()`. Is there another way? If not, I'd like to this issue a feature request.

**Comment by numa001** [comment]
try   .isLength({ min: 1 })

**Comment by zatziky** [comment]
@numa001 jup it could work but it's much nicer to read `.isNull()` or `.isNotNull()`, isn't it?

**Comment by gustavohenke** [comment]
Duplicate of #473

**Comment by gustavohenke** [comment]
Semantics of #473 sound better to me, so I'm closing here in favor of that one.

**Comment by sant123** [comment]
Also you can use `.not().isEmpty().withMessage("The field cannot be empty")`
