### ISSUE TITLE
Custom sanitizer support?

### ISSUE THREAD

**Issue by williamdang** [ctavan/express-validator#445]
Will there be a way to add custom sanitization function? Something likes this:
`sanitize('foo').custom(customSanitizer)`

**Comment by gustavohenke** [comment]
Why not? 😄

**Comment by zmw85** [comment]
why v3 style of setting up custom sanitizers could not be used in new v4 style middleware way? This seem to be a downgrade to me.

**Comment by Zakini** [comment]
Definitely need this. I'd like to protect against XSS by adding a custom sanitizer.

**Comment by newmanw** [comment]
Would love this feature as well.

**Comment by tranvansang** [comment]
This is my trick to convert date string to Date object

check('birthday')
.custom((value, {req, location, path}) => {
  req[location][path] = new Date(value)
})

**Comment by tranvansang** [comment]
I have made [pull request](https://github.com/ctavan/express-validator/pull/481) for custom sanitizer.

Currently, support only non-async sanitizer. Async sanitizer need more works.

While waiting for PR to be merged, you can check out [my fork](https://github.com/tranvansang/express-validator). This is being used for my in-house app

**Comment by tudor33sud** [comment]
any updates on this? currently, @tranvansang 's trick works, but I'd love to keep the code clean and don't sanitize with check methods.
