### ISSUE TITLE
Error in index.js line 75

### ISSUE THREAD

**Issue by abhinavtv** [ctavan/express-validator#448]
node_modules/express-validator/lib/express_validator.js:75
chain[name] = (...options) => {
SyntaxError: Unexpected token ...
getting this error when I'm running my js program.
any ideas?

**Comment by mika-s** [comment]
... is an ES6 feature. Are you running an old version of Node?

**Comment by abhinavtv** [comment]
Yeah, I'm running node v4.3.2 and express v2.14.12.
Will update and ping back

**Comment by abhinavtv** [comment]
Thank you lots, updated my node version to 8.6.0 and express version to 5.3.0 and now it's working properly.

**Comment by mabbasi09** [comment]
I'm getting the same error running v4.2.6, how did you update to the latest version?
