### ISSUE TITLE
Is it possible to expose validation key to errorFormatter?

### ISSUE THREAD

**Issue by hugw** [ctavan/express-validator#450]
Right now I'm working an API and wanted to know if it is possible to expose the `method` name as another argument to errorFormatter so I don't have to repeatedly set a validation message to each of my fields. e.g.

**Current scenario**
```
check('email').isEmail().withMessage('must be an email')
check('name').notEmpty().withMessage('isEmpty')
```
Will produce...
```
[{ location: 'body',
param: 'email',
msg: 'must be an email',
value: '...' },
{ location: 'body',
param: 'name',
msg: 'isEmpty',
value: '...' }]
```
In order to front end code identify exactly which field/validation type is getting return, I need to setup nice messages because the `Invalid value` can cause lot of ambiguity.

But...if we could get something like this:

**Proposed scenario**
```
check('email').isEmail()
check('name').notEmpty()
```
To return...
```
[{ location: 'body',
param: 'email',
msg: 'Invalid field',
validation: 'isEmail',
value: '...' },
{ location: 'body',
param: 'name',
validation: 'notEmpty'
msg: 'Invalid field',
value: '...' }]
```

It would be very easy to any API consumer to understand what kind of error is getting return and could translate the `validation` key to the right string without having to set a single `withMessage` on the backend side. What do you guys think?

**Comment by gustavohenke** [comment]
Hey @hugw, thanks for the idea!

Indeed, I like this style of sending errors to clients. But people may be using custom validators, and these don't have a name.
Do you have a suggestion on what we should do?

**Comment by hugw** [comment]
@gustavohenke Yeah, I've thought about custom validators and its constraints, I'll dig in the code to get a better context and see if there's any solution to propose.

**Comment by gustavohenke** [comment]
This can be worked around in user land by using messages. Won't be implemented in express-validator for now.
