### ISSUE TITLE
Question: Are object literal schema validations going to be deprecated?

### ISSUE THREAD

**Issue by mtpultz** [ctavan/express-validator#452]
It seems like schema validation via an object literal might be soon deprecated?  Though they aren't as declarative as chaining it does provide an easy way to pull out the validations from being directly in the routes definitions so they don't get overly verbose.  I wanted to check what the roadmap looks like in the future, and whether it is possible to maintain schemas or something similar in express-validator.

Using the new API it doesn't appear possible to extract the validations into a controller or middleware method to be invoked like it was using schema validations.  You could do something like the example below using the Legacy API where the controller's main method was only entered after all validation had already guaranteed to have passed so controllers didn't have to duplicate checking validations each time just start doing their business logic.

```js
router.post('/examples/:id',
  exampleController.validate,
  exampleController.create
);
```

Then add an abstract `Validator` class to a `BaseController` to run the schemas:

```js
export class ExampleController extends BaseController {

  protected abstract get validationSchema(): { [key: string]: any } {
    return { ... }
  }
 
  // ...
}
```

```js
export abstract class Validator {

  constructor() {
    this.validate = this.validate.bind(this);
  }

  protected abstract get validationSchema(): { [key: string]: any };

  public async validate(req: Request, res: Response, next: NextFunction) {
    const result = await this.validator(req, res);

    // Check for validation errors
    if (result.isEmpty()) {
      // Move to the next middleware in stack
      return next();
    }

    // Handle the validation error response
    this.validatorErrorResponse(res, result);
  }

  protected async validator(req: Request, res: Response): Promise<ExpressValidator.Result> {
    // Validate the request using the schema
    req.check(this.validationSchema);
    // Wait for the results of validation
    return await req.getValidationResult();
  }

  // ...
}
````

The closest I can see this getting to the above example is this example, but it bloats the route definitions with the validation chain

```js
router.post('/examples/:id',
  // Add validation chain since they can't be invoked within own middleware or returned
  [
    // validation chain, which could be quite large
  ],
  // Then invoke validationResult(req).throw(); or equivalent to handle response or pass 
  // to next() middleware to handle create
  exampleController.validate,
  // Now controller doesn't have to consider validations since they have been handled
  exampleController.create
);
```

**Comment by gustavohenke** [comment]
It's not that the schema validations will be deprecated. The whole legacy API will.

What I understood is that you're not exactly looking after the schema validations - you want a way to keep the whole validation logic contained in a single function (definition, execution, failures report).
Correct?

That could be do-able - we just need to come up with an API that integrates nicely with `check` and etc.

<sub>P.S.: You could have kept the discussion going on #433 😄 </sub>

**Comment by mtpultz** [comment]
Hi @gustavohenke, yeah exactly just a way to abstract the validation out of the route handler and into a bit of middleware that can run the validation chain and handle the error response or allow for the next bit middleware to run if validations pass.  

It was nice to have the JSON schema for validations as an option since the can get quite verbose.

I'll close this and move over to the discussion you mentioned.
