### ISSUE TITLE
Apply SanitizeBody to all routes and fields

### ISSUE THREAD

**Issue by microcipcip** [ctavan/express-validator#454]
Is there a way to apply SanitizeBody middleware to all express routes?
I mean something like `app.use(sanitizeBody(['*']).escape())`?

Also, what is the correct syntax to sanitize all nested objects? I tried `app.use(sanitizeBody(['*.*']).escape())` but doesn't work.

**Comment by gustavohenke** [comment]
No, there's no way to do this yet. Wildcards apply the sanitizers/validators shallowly only 😐

**Comment by microcipcip** [comment]
But can I apply the sanitizeBody globally to all express routes though?

**Comment by gustavohenke** [comment]
Yes, you can.

**Comment by microcipcip** [comment]
What is the correct syntax for that? Sorry may be something obvious but I am a noob.

**Comment by gustavohenke** [comment]
You showed it yourself in the first post: `app.use(sanitizeBody('*').escape())` 😉 
Just be sure to place it before any routes and before/after other relevant middlewares.

**Comment by microcipcip** [comment]
Maybe the problem is that I am using multer, if I add the sanitizeBody after multer, it works, otherwise it does nothing.
