### ISSUE TITLE
Question: Validating an array of objects

### ISSUE THREAD

**Issue by jensengar** [ctavan/express-validator#459]
Sorry for the noob question, but If I post up an array of objects, how can I validate the individual objects?

**Comment by mika-s** [comment]
You can write custom validators. For example:

```
module.exports.isObjectIdArray = function(value) {
  let isObjectIds = true;

  value.forEach(function (element) {
    if (!mongoose.Types.ObjectId.isValid(element)) {
      isObjectIds = false;
    }
  })

  return isObjectIds;
}
```

Schema:

```
var userSchema = {
  'courses': {
    isObjectIdArray: {
      errorMessage: 'Illegal ID(s)'
    }
  }
}
```

My code is for the legacy API but I assume it's similar with the new one.

**Comment by gustavohenke** [comment]
Thanks for answering, @mika-s!

**Comment by andhikamaheva** [comment]
Hmm, i'm using Wildcard for validation array of object but only work in the first array of object and the second array of object didn't validated.
