### ISSUE TITLE
Sanitizing fields works in a very weird way!

### ISSUE THREAD

**Issue by qkoots** [ctavan/express-validator#461]
Hello, 

I have a question about how sanitizer works in v4. This is what the API document says:

> Any of the validation and sanitization methods listed by validator.js are made available in all validation chains created by express-validator, as long as we're supporting the most up-to-date validator version.
If you use any of the sanitizers together with validators, the validated value is the sanitized one.

 if I've understood the documentation correctly, you should be able to chain like this: 

```
// Import module
const   {check, validationResult} = require('express-validator/check'),
             {matchedData, sanitize} = require('express-validator/filter');

 check("firstName").isAlpha().trim().withMessage("First name must only contain letters.") 
```

OR with the ```trim()``` chained to the sanitization chain like:

```  
check("firstName").isAlpha().withMessage("First name must only contain letters.")
sanitize("firstName").trim()      
 ```

However the ```trim()``` methode doesn't work in neither of the ways above. The only way it works is when the methode is chained to both chains like:  

```
check("firstName").isAlpha().trim().withMessage("First name must only contain letters."),
sanitize("firstName").trim()
```

My question: Why does this only works in as shown in the last example? What am I doing wrong?

Thanks.

**Comment by Badou90** [comment]
Also notised this bug

**Comment by gustavohenke** [comment]
Hey! Sorry for this delay in replying you folks.
So, it isn't really a bug. It is supposed to work this way. I no longer know why I decided to make them behave like that, but it's definitely an astonishment factor, so I'm opting to change this behaviour in an upcoming v5.
