### ISSUE TITLE
Support to validators group

### ISSUE THREAD

**Issue by edvaldoszy** [ctavan/express-validator#465]
Hi! I'd like to know the possibility to create something like:

```
...
const myValidatorGroup = {
    isInt: true,
    notEmpty: true
}
...
``` 

and after that use it as a validator:
```
...
'field': {
    in: 'body',
    myValidatorGroup: true,
    errorMessage: 'My error message'
}
...
```

Thanks everyone.

**Comment by gustavohenke** [comment]
Hello @edvaldoszy,
Validation grouping is not a feature nor we have plans on implementing it.

Do you have more context on how it should behave, and its API using [`check()`](https://github.com/ctavan/express-validator#check-api) would look like?

**Comment by gustavohenke** [comment]
Since I gave some thought on this idea and found no reason to add it, I'm discarding it for now.

Feel free to keep commenting to show your motivations (I'll give a look, 4realz!).
