### ISSUE TITLE
How to callback return rules

### ISSUE THREAD

**Issue by carvalhoviniciusluiz** [ctavan/express-validator#466]
hi,
is not available to return as a rule in a callback.

how do I do that

```
export const rules = () => {
  return [
    check('firstname', i18n.t('characters.2', { field: 'Firstname' })).isLength({ min: 2 }),
    check('lastname', i18n.t('characters.2', { field: 'Lastname' })).isLength({ min: 2 })
  ]
}

...

router.put('/:id', rules, controller.update)
```

**Comment by alexeyfrank** [comment]
@carvalhoviniciusluiz try to call it like that `router.put('/:id', rules(), controller.update)`

**Comment by carvalhoviniciusluiz** [comment]
That's it, it worked. :)
Only that did not solve my problem. :(

thks!

**Comment by gustavohenke** [comment]
And what is the error then, @carvalhoviniciusluiz?

**Comment by carvalhoviniciusluiz** [comment]
I need of i18n in project, because of this I mounted a validation callback
```
import { check } from 'express-validator/check'
...
export const rules = (req, res) => {
  check('data.firstname', t('characters.2', { field: 'Firstname' })).isLength({ min: 2 })
  check('data.lastname', t('characters.2', { field: 'Lastname' })).isLength({ min: 2 })
  check('data.email')
    .isEmail()
    .withMessage(t('invalid', { field: 'email' }))
    .custom(value => {
      return true
    })
}
...
router.put('/:id', [rules], controller.update)
```
but validation has stopped!  :(
returning only the array, it works, but I can not use i18n properly...

```
export const rules = [
  check('data.firstname', t('characters.2', { field: 'Firstname' }))
    .isLength({ min: 2 }),
  check('data.lastname', t('characters.2', { field: 'Lastname' }))
    .isLength({ min: 2 }),
  check('data.email')
    .isEmail()
    .withMessage(t('invalid', { field: 'email' }))
    .custom(value => {
      return true
    })
]
```

**Comment by mattandrews** [comment]
I'm having similar issues. We're using [i18n-2](https://github.com/jeresig/i18n-node-2) for internationalisation, which uses the `req` object to localise strings (eg. `req.i18n.__('some.path.here')` format). I can't find a way to localise my `withMessage()` calls here – even experimenting with a custom error handler (which has access to the `req` object) isn't working for me.

**Comment by gustavohenke** [comment]
Hello @mattandrews @carvalhoviniciusluiz this is now possible [express-validator v5.0.0](https://github.com/ctavan/express-validator/releases/tag/v5.0.0).
Check [this section of the docs](https://github.com/ctavan/express-validator#dynamic-messages) for more information on how to do it.
