### ISSUE TITLE
withMessage does not render i18next messages

### ISSUE THREAD

**Issue by tioschi** [ctavan/express-validator#469]
Hi,

When I start the express app I first initialize i18next and then I set the validators in the api routes.

The problem is that when the `.withMessage()` is run in the validation chain the i18next hasn't manage to load the translation resources before the `withMessage` is being called.

So when I attach something like `.withMessage(i18next.t('validation.Error'))` to a validation chain, the i18next.t() can't find the key `validation.Error`.

Is there a way to make i18next keys been rendered inside withMessage()?

Before I was using the legacy api and it was working as expected.

I use express v4.x.x, i18next v10.x.x and express-validator v4.3.0

**Comment by gustavohenke** [comment]
I think your use case is quite the same as #466; it seems like deferring `withMessage()` is something that needs to be done!

**Comment by gustavohenke** [comment]
Hello @tioschi this is now possible [express-validator v5.0.0](https://github.com/ctavan/express-validator/releases/tag/v5.0.0).
Check [this section of the docs](https://github.com/ctavan/express-validator#dynamic-messages) for more information on how to do it.
