### ISSUE TITLE
validationResult(req).throw() not throwing?

### ISSUE THREAD

**Issue by JeffMatthews2** [ctavan/express-validator#470]
I am learning express-validator.  realized I was using the legacy approach and would like to not bother with it.  As long as I have to learn, I might as well learn the newest.

I am not understanding why notEmpty() isn't causing validationResult() to throw an error when "name" is empty.  I have confirmed name.length == 0.  However, I also get the console message that "not empty passed."  Console also shows "errors is empty: true."

As far as I can tell, I have copied from the example in the Documentation for throw(), here: https://github.com/ctavan/express-validator#throw

```

        console.log("name: " + name + " (length: " + name.length + ")");
  	req.check('name').notEmpty().withMessage("Name is required."); //.

	try {
          let result = validationResult(req);
	  console.log("errors is empty: " + result.isEmpty());
	  
	  result.throw();
	  // Oh look at ma' success! All validations passed!

	  console.log("not empty passed.");
	} catch (err) {
	  console.log(err.mapped()); // Oh noes!
	}
```

**Comment by JeffMatthews2** [comment]
I just found this issue, where your explanation addresses the same type of misuse of the API:  https://github.com/ctavan/express-validator/issues/411

I will work on it some more and post again if I still can't figure it out.

**Comment by gustavohenke** [comment]
Hi @JeffMatthews2,
Your use case is a little different. You seem to be using the legacy API, which runs the validators immediately, but you're using `validationResult` function from v4's check API.

You must either:
- Migrate your validation logic to use check API
- Use one of the following methods to retrieve the validation errors/result on the `req` object:
  - [`req.getValidationResult()`](https://github.com/ctavan/express-validator#reqgetvalidationresult)
  - [`req.validationErrors`](https://github.com/ctavan/express-validator#reqvalidationerrorsmapped)
