### ISSUE TITLE
ability to set default value?

### ISSUE THREAD

**Issue by vajahath** [ctavan/express-validator#471]
Is there any point in adding an option to set a default value for a field?
like:
```js
body('limit').optional().defaultValue(10)
```
this would set `req.body.limit` to value `10` if it is not given.

**Comment by gustavohenke** [comment]
No. This request is quite out of scope for express-validator.

I tried searching for it, but I couldn't find related libs, though.
Should be easy to implement with [`_.defaults`](https://lodash.com/docs#defaults)/[`_.defaultsDeep`](https://lodash.com/docs#defaultsDeep) from Lodash, for example.
