### ISSUE TITLE
Throw error

### ISSUE THREAD

**Issue by JeffMatthews2** [ctavan/express-validator#472]
I am trying to copy your samples as closely as possible, but I am having some minor trouble.  I can't seem to get it to throw/handle errors properly.  

Here is your sample code:

```
 // ...or throw your own errors using validators created with .custom()
    .custom(value => {
      return findUserByEmail(value).then(user => {
        throw new Error('this email is already in use');
      })
```

I tried the above pattern, but it did not work.  I changed the code as shown next, and it works.  I think this has something to do with the way my getUserByName() is written, which I will show further below.  
```
        .custom(name => {
		return User.getUserByName(name).then( user => {
			return false;
		}).catch( err => {
			return true;
		});
	})
	.withMessage('A user by this name has already been registered.'),
```
Here is my getUserByName():

```
module.exports.getUserByName = function(name){
	return new Promise( (resolve, reject) => {

	         // Case-insensitive.
		// Still needs work.  Disallow search on empty or null.
		let query = { 'name': new RegExp( '^' + name + '$', 'i') };

		User.findOne(query, (err, user) => {
			if (err) throw err;

			if (user){
				resolve(user);
			}
			else {
				reject ('User: "' + name + '" could not be found.');
			}
		});
	});
}

```

My getUserByName() method returns a promise, which is **resolved()** if it finds the name.  Otherwise, either something went wrong (maybe can't access database) or the search returned no results.  In either of these 2 failure cases, the promise is **rejected()** .  This is the way I use the function for log-in purposes.

I want to use the **same** getUserByname() function for registration of new users.  Why didn't your code sample work out of the box for me?  I had to add a catch() handler, and I was unable to use throw like you did.  My concern is that a catch() will also catch errors from failing to access the server.  I don't want that scenario to pass validation.

**Comment by gustavohenke** [comment]
Hello @JeffMatthews2,
Sorry for the incredible delay on getting back to you.
Have you ever fixed this?

**Comment by JeffMatthews2** [comment]
Yes, I was all misguided in the way I was going about it.  Once I straightened myself out, I was able to do whatever I wanted.  Thanks for asking.
