### ISSUE TITLE
Compare two params

### ISSUE THREAD

**Issue by carasel** [ctavan/express-validator#475]
Is it possible to use this module to compare two query params in the same request?

I have an API which has the params `startDate` and `endDate`. I am trying to validate that the end date is after the start date, but haven't been able to work out how to access `startDate` from `check("endDate")`

**Comment by jaouadballat** [comment]
use equals()

**Comment by gustavohenke** [comment]
equals is for checking whether they are the same, @jaouadballat. It would also require the value to be static, which is not the case.

You can, however, use `.custom((value, { req }) => value > req.body.otherDate)`.
