### ISSUE TITLE
Validation chain `.in()` method

### ISSUE THREAD

**Issue by williamdang** [ctavan/express-validator#480]
The new validation chain reduces 50% of my validation code. However, there is something that I want to further enhance.

Let's take this situation, I have the exact same `validation chain` for the same `field` **BUT** it in different places (e.g. `body` vs `params`).

I can do this with 2 options with some cons:

1. 2 validation chains: this will lead to duplicate code
2. User `check` rather thang `checkBody` or `checkParams`: this will leads to some unexpected side effect. E.g. `foo` field is optional required in the body, but if the client send `foo` field in the `params` which, if not pass the test, will throw an validation error.

---

My proposal: 

Add a new method `.in(locations)` which override the location of this validation chain whether which `check` function is used.

It is somewhat like `optional()` function and the old v3 `in` field in `schema validation`.

---

For example:

    const checkFoo = check('foo').isInt().withMessage('Invalid');

And in the `router` I can do something like this:

    router.get('/',
      [
        checkFoo.optional().in(['query'])
      ], (req, res, next) => {
      // ...
    });

    router.post('/',
      [
        checkFoo.in(['body'])
      ], (req, res, next) => {
      // ...
    })

**Comment by gustavohenke** [comment]
Ah, yes. That's a good idea 👍

**Comment by gustavohenke** [comment]
Actually, I don't think this is really a good idea anymore...

You can use a function that extends an existing chain:

```js
const withFooValidations = chain => chain.isInt().withMessage('must be int');
app.get('/', withFooValidations(check('foo').optional()), handler);
app.post('/', withFooValidations(check('foo')), handler);
```

**Comment by gustavohenke** [comment]
Closing. Let me know of further motivation for this.
