### ISSUE TITLE
Locations in matchedData options accepts "params" not "param"

### ISSUE THREAD

**Issue by deepakduggirala** [ctavan/express-validator#483]
As per documentation, 

> locations: an array of locations to extract the data from. The acceptable values include body, cookies, headers, **param** and query. Defaults to undefined, which means all locations.

The value **params** is working instead of **param**

This works: paramData = matchedData(req, { locations: ['params'] });
This does not: paramData: matchedData(req, { locations: ['param'] }),

**Comment by gustavohenke** [comment]
Thanks for pointing it out!
