### ISSUE TITLE
How to call check inside the middleware instead of passing as middleware

### ISSUE THREAD

**Issue by sincerekamal** [ctavan/express-validator#485]
I already have middleware already, I don't like to use `check` as middlewares to this, is there anyway to use `check` inside `reqHandler` ? Like how we used with Legacy API ?

````
const reqHandler = (req, res, next) => {
// do something
};

router.post('/createTask', reqHandler);
````

**Comment by gustavohenke** [comment]
Yes, but it isn't very clean/intuitive:

```js
const reqHandler = (req, res, next) => {
  check('email').isEmail()(req, res, () => {
    check('password').isEmail()(req, res, next);
  });
}
```

**Comment by sincerekamal** [comment]
What if i have only one check inside `reqHandler` ?

**Comment by chrisdl** [comment]
I would think for one check something like this should work.

```
const reqHandler = (req, res, next) => {
    check('password').not().isEmpty()(req, res, next);
}
```

**Comment by gustavohenke** [comment]
Yes, @chrisdl is right. Sorry for the delay @sincerekamal 😞

**Comment by sincerekamal** [comment]
Great. Thanks much
