### ISSUE TITLE
[Feature Request] Let withMessage accept a callback

### ISSUE THREAD

**Issue by hrastnik** [ctavan/express-validator#489]
It would be great if `withMessage` could accept a callback function that would receive the field name as the argument.

For example, I have to check if some fields exist in the body of the incoming request. The field values are expected to be numbers and each field has different allowed ranges.

    body('field1')
      .exists().withMessage('Field required')
      .custom(val => 10 < val && val < 20).withMessage('Invalid range')

    body('field2')
      .exists().withMessage('Field required')
      .custom(val => 100 < val && val < 200).withMessage('Invalid range')

This works, however, it would be nice if I could define the messages in a function that receives some parameters like the name and value of the field as well as some other data if possible.

Then we could use it like this

    function messageCallback({field, value}) {
      return "Field" + field + " received invalid value: " + value;
    }
  
    body('field1')
      .exists().withMessage('Field required')
      .custom(val => 10 < val && val < 20).withMessage(messageCallback)

    body('field2')
      .exists().withMessage('Field required')
      .custom(val => 100 < val && val < 200).withMessage(messageCallback)

This would give extra flexibility to the users in terms of handling errors.

**Comment by gustavohenke** [comment]
Custom validators can throw errors with whatever messages they want.

Standard validators however are limited to the `.withMessage()` features, in which case having it accept a callback would be useful.

See also: #466 and #469

**Comment by gustavohenke** [comment]
Hello @hrastnik this is now possible [express-validator v5.0.0](https://github.com/ctavan/express-validator/releases/tag/v5.0.0).
Check [this section of the docs](https://github.com/ctavan/express-validator#dynamic-messages) for more information on how to do it.
