### ISSUE TITLE
Validate nested objects

### ISSUE THREAD

**Issue by elissaioskon** [ctavan/express-validator#494]
request object is:
{ 
 generalInfo: {brand: Audi, constructionYear: 2000", ... }, 
 engineInfo: { hp:500, gas: true },
}

check("generalInfo.brand","Brand required").isEmpty()  not work.
Is there any recommendation?

**Comment by gustavohenke** [comment]
`isEmpty()` is requesting `generalInfo.brand` to be empty instead of not empty.
Is it really what you mean?

**Comment by elissaioskon** [comment]
Yes i mean isNotEmpty().
but it only works if i use check("brand","brand is required").isNotEmpty() and the req object is not nested:
{brand: Audi, constructionYear:2000, hp:500, gas: true}.
 But how can it work with nested objects?
...Thanks for the reply

**Comment by AbdelrahmanHafez** [comment]
req.checkBody("generalInfo.brand", ""Brand info are required.").notEmpty();

Flatten the object and it works.

**Comment by gustavohenke** [comment]
Yes, go with what @AbdelrahmanHafez said. Or use `check(fieldName).not().isEmpty()` if using check API.
