### ISSUE TITLE
`buildCheckFunction()` is not defined

### ISSUE THREAD

**Issue by Underwaterr** [ctavan/express-validator#507]
Per the documentation,
```javascript
const { buildCheckFunction } = require('express-validator/check')
```
The `buildCheckFunction` is undefined 😢. Am I missing something here?

**Comment by gustavohenke** [comment]
This wasn't published yet!

**Comment by gustavohenke** [comment]
[v5.0.0 is out now](https://github.com/ctavan/express-validator/releases/tag/v5.0.0)
