### ISSUE TITLE
Docs inconsistency between npmjs.com and github.com

### ISSUE THREAD

**Issue by treble-snake** [ctavan/express-validator#508]
Hi there.

Docs differ between [npmjs page](https://www.npmjs.com/package/express-validator) and [github page](https://github.com/ctavan/express-validator). E.g., no wildcard mention on *npmjs page*, and there are other diffs. 
Was it done intentionally or it's a mistake? It's very confusing, actually.

**UPD.** As I get it, latest changes wasn't published to NPM yet, but package version is already 4.3.0 there, same here in master branch, so I kinda expect the code base to be the same as well. Really, really confusing. Or it's just me?

**Comment by gustavohenke** [comment]
You're not alone: #507

> As I get it, latest changes wasn't published to NPM yet, but package version is already 4.3.0 there, same here in master branch, so I kinda expect the code base to be the same as well.

We -- like many other package maintainers -- only change the version number when we're done adding features/fixing bugs.
This is the only way to tell if we're releasing a patch, a minor or a major version.

It's probably a common confusion source among npm package users 😃

**Comment by treble-snake** [comment]
@gustavohenke thanks for your response, I get it now.
I've just been confused by the workflow, I guess :)
Sorry for bothering.

**Comment by gustavohenke** [comment]
That's okay, thanks for considering express-validator! 🎉
