### ISSUE TITLE
Custom validator issue

### ISSUE THREAD

**Issue by vvaldersteins** [ctavan/express-validator#509]
Hi,

I'm trying to use custom validator to validate an array of items. 

The idea is that, I'm passing an array to the validator function, then I'm validating ids within this array against the database.

It works, when everything is correct, but it does not work, when not existing id is passed.

```
function validateIngredient(ingredients) {
  return new Promise((resolve, reject) => {
    for (const ingredient of ingredients) {
      if (ingredient && Number.isInteger(ingredient.measurement)) {
        // Try to retrieve measurement
        measurements_db.getMeasurement(ingredient.measurement)
          .then(data => {
            if (!data) {
              reject(false);
            }
          });
      }
    }

    resolve(true);
  });
}
```

And the custom validator -

`  .custom(item => validator_helper.validateIngredient(item)).withMessage('ingredients_measurement_must_be_valid_entries')`

The measurements_db.getMeasurement() returns first entry from the database based on the passed id.

**Comment by gustavohenke** [comment]
Your validator is theoretically synchronous, as `resolve` is being called immediately after your `for` loop.

My suggestion is to do this instead:

```js
check('ingredients.*.measurement')
    .isInt().withMessage('Invalid ID format')
    .custom(id => measurements_db.getMeasurement(id).then(data => {
        if (!data) {
            throw new Error('ID not found');
        }
    }))
```

- ✅ easy looping thru all given ingredients
- ✅ integer check previously in your custom validator is now its own validation
- ✅ DB call being awaited upon

**Comment by vvaldersteins** [comment]
Works like a charm! Thanks!
