### ISSUE TITLE
Email uniquesness check in mongo db using express-validator 4

### ISSUE THREAD

**Issue by N-W-Turash** [ctavan/express-validator#510]
Hi, I am using express-validator 4, how can I check the uniqueness of email in db?
I am using mongoose v4.8.5.

**Comment by gustavohenke** [comment]
There's this example in the README (trimmed for clarity):

```js
check('username')
    .isEmail().withMessage('must be an email')
    .normalizeEmail()
    .custom(value => {
      return findUserByEmail(value).then(user => {
        throw new Error('this email is already in use');
      })
    })
```

Please note that it's better if you ask this kind of question on StackOverflow. Thanks for using express-validator.
