### ISSUE TITLE
`checkSchema` is not a function.

### ISSUE THREAD

**Issue by ashersaupingomez** [ctavan/express-validator#514]
The `checkSchema` method from the check API simply isn't firing. Perhaps it was caused by this commit: https://github.com/ctavan/express-validator/commit/4254b787e94074cf8a3c101d59d0fb9ec10385a0.

Use:
```javascript
import { checkSchema } from 'express-validator/check';
const schema = checkSchema({ ... properties ...});
...
```

Error:
```batch
TypeError: checkSchema is not a function
```

System:
- Node: 6.11.5
- express-validator: 4.3.0

**Comment by lfernando-silva** [comment]
The schema validation will be nice one. I'm waiting for it!

**Comment by dknussmann** [comment]
Any info on when it will be released?

**Comment by gustavohenke** [comment]
Soon™

v5 wishlist includes #439, #461 and #500. Any help on this would be much appreciated.

**Comment by gustavohenke** [comment]
@sumitsaha because it reflects current `master` code changes. You can check npm for the docs of the published version.

**Comment by gustavohenke** [comment]
[v5.0.0 is out now](https://github.com/ctavan/express-validator/releases/tag/v5.0.0)
