### ISSUE TITLE
express-validator v4 minimalistic example not working

### ISSUE THREAD

**Issue by hamzafox** [ctavan/express-validator#518]
Hi ! 
I want to check request body but it always returns invalid. Here is my code 

`const express = require("express");
const bodyParser = require("body-parser");
const validator = require("express-validator");
const { check, validationResult } = require("express-validator/check");

const app = express();
app.use(bodyParser.json());
app.use(validator());

app.post('/',[ check("email").isEmail() ], (req, resp) => {
        const errors = validationResult(req);
        resp.send(errors.mapped());
});
app.listen(3000, () => { console.log('listening on port 3000'); });`

I send a post request with body containing : 
`{
	"email": "ha@gmail.com"
}`

The Response is ALWAYS an error even if the email I give is perfectly correct>>
`{
    "email": {
        "location": "body",
        "param": "email",
        "msg": "Invalid value"
    }
}`

 Am i missing something ?

**Comment by alejandrocesena** [comment]
Did you get this working? I'm having exactly the same issue

**Comment by gustavohenke** [comment]
Hi @hamzafox and @alejandrocesena, I didn't see this issue before.

Notice that the error for `email` doesn't contain the value the validator ran with, what tells me the `bodyParser.json()` middleware didn't do a thing.
Could you be missing the `Content-Type: application/json` header in your request?
