### ISSUE TITLE
Express validator 4.3.0 outdated on NPM

### ISSUE THREAD

**Issue by sant123** [ctavan/express-validator#519]
Hi, it seems since version above was released; new files and maybe features were included to it. For example `schema.d.ts`. ¿May you consider adding these changes into 4.3.1? 

Thank you.

**Comment by gustavohenke** [comment]
It is going to be a major version, eg v5.0.0. There's still some breaking changes to consider before publishing it.

**Comment by gustavohenke** [comment]
[v5.0.0 is out now](https://github.com/ctavan/express-validator/releases/tag/v5.0.0)
