### ISSUE TITLE
body() could consider the body an entire field

### ISSUE THREAD

**Issue by byte-artisan** [ctavan/express-validator#520]
It would enable validating an request body like this:
["item1","item2"]. Just an array. 
because there is no name, the api doens't allow the validation. body function requires always a field.
I explore other ways, like schema and seams there is no way.

It is a suggestion to improvement.

**Comment by gustavohenke** [comment]
You can already do this by using `body('*')`

**Comment by byte-artisan** [comment]
it works, but how can i validate the array length? 
     body('*') 
 .custom((item) =>
                //item is every item in the array but i can't see the array 
            )

**Comment by gustavohenke** [comment]
Well, thinking better about it, it could be desirable to do that if we consider all formats that a request body could have.

**Comment by gustavohenke** [comment]
🚢 v5.1.0 released with this
