### ISSUE TITLE
Express Validator with latest version not working (V ^4.3.0)

### ISSUE THREAD

**Issue by RaviDavda** [ctavan/express-validator#522]
I am facing error while doing latest express validator (V ^4.3.0) example. There is one basic example of login with post request. There are two parameters email and password. Below is my code.

**routes.js file:**

```js
var express = require('express');  
var router  = express.Router();  
var validator = require('./validator');

router.post('/login', [sanitize('email').trim(), 
 validator.publicRouteValidate('login')], (req, res, next) => {
  console.log(req);
}  
```

**validator.js file:**

```js
'use strict';  
const { check, validationResult } = require('express-validator/check');  
const { matchedData, sanitize } = require('express-validator/filter');

module.exports = {  
  publicRouteValidate: function (method) {  
    return (req, res, next) => {  
      switch (method) {  
        case 'login':  
          check('email').isEmail().withMessage('email must be an email')  
            .isLength({min: 109}).withMessage('minimum length should be 100 characters')  
        break;  
      }  
      var errors = validationResult(req)
      console.log(errors.mapped())
      if (!errors.isEmpty()) {
         res.status(422).json({ errors: errors.array()[0].msg })
      } else {
         res.send('login')
      }
}}}  
```

Now when I am doing POST request with only email and value of email is abc. So I should get the error like email must be an email. But I did not get any response. So What is the issue I do not know?

**Comment by nmajethiya** [comment]
same issue

**Comment by gustavohenke** [comment]
Replied to your question on StackOverflow.
https://stackoverflow.com/a/48764342/2083599

**Comment by nmajethiya** [comment]
Do we need to every time create a separate function of validation and function to catch their errors ?
The old one was better than this!

**Comment by gustavohenke** [comment]
@nmajethiya would adding a function that runs each of the validators make your life easier?

**Comment by nmajethiya** [comment]
@gustavohenke Yeah got you!
Seems, I was not actually understanding the benefit of this, but got you now!

**Comment by notflip** [comment]
Could anyone briefly explain why we need to do this in 2 separate functions? So with middleware instead of allowing it to be done in one function?
