### ISSUE TITLE
Provide isString validator

### ISSUE THREAD

**Issue by Deilan** [ctavan/express-validator#524]
A feature request to provide `isString` validator (not `boolean`, `number`, etc.). Currently there are `isAlpha` and `isAlphaNumeric`, which are in semantic subset of `isString` and may be too strict in some cases.

As per https://github.com/chriso/validator.js/issues/117#issuecomment-9066016 it's out of scope of [validator.js](https://github.com/chriso/validator.js) lib.

**Comment by gustavohenke** [comment]
Taking into account that all standard validators are converted to string and validator.js already implements `isBoolean`, `isDate`, `isInt`/`isDecimal` and `isJSON`, I think that could make sense.

If you're up for it, this could be an easy implementation 😃

**Comment by gustavohenke** [comment]
🚢 v5.1.0 released with this
