### ISSUE TITLE
Apply exists validator within schema

### ISSUE THREAD

**Issue by Deilan** [ctavan/express-validator#525]
Is there a way to apply `exists` validator within schema?

**Comment by gustavohenke** [comment]
Yes! Have you tried it?

![screen shot 2018-02-14 at 09 54 08](https://user-images.githubusercontent.com/826553/36178474-09a2b856-116d-11e8-8d98-de7be3cca06f.png)

**Comment by gustavohenke** [comment]
I see in your profile that you're a typescript user.
In this case I see we really forgot to add `exists` to the schema typings, what has been done now 🎉

**Comment by Deilan** [comment]
@gustavohenke You're right, the problem occurs when using typescript, sorry for not mentioning that ahead of time.

So could you kindly reopen the issue then?

**Comment by gustavohenke** [comment]
It was fixed.

**Comment by gustavohenke** [comment]
Fix pushed to v5.0.1.
