### ISSUE TITLE
UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by sukhdeepsingh123** [ctavan/express-validator#526]
I am facing this issue while using the validator as middleware.
DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

UnhandledPromiseRejectionWarning: TypeError: next is not a function
at runner.then.errors (/home/appinventiv/angular/RideSharing/node_modules/express-validator/check/check.js:18:7)

UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 5)

**Comment by gustavohenke** [comment]
You need to show your code.
