### ISSUE TITLE
how to check parameters in response?

### ISSUE THREAD

**Issue by nakshay** [ctavan/express-validator#529]
I want to check if the password and verify password fields matches but cannot access password fields since req object is not available.

router.post('/newUser', [
    //express validation starts here

    check('email').isEmail().withMessage('must be an email').trim().normalizeEmail(),
    check('password','password is must').exists(),
    check('password2','verify password must match  passsword').equals('password')

],(req, res) => {
.
.
.
});

**Comment by gustavohenke** [comment]
Use a custom validator

https://stackoverflow.com/a/46013025/2083599

**Comment by nakshay** [comment]
Thanks, custom validator worked.
