### ISSUE TITLE
How can I use "custom" validation with checkSchema ?

### ISSUE THREAD

**Issue by sumitsaha** [ctavan/express-validator#532]
I want to use the Schema Validation as it helps me to write all my validations in one place. But I am a bit confused about how can I use the "custom" validation with checkSchema?

My requirement is, I want to define a schema for a form field named "mobile_number" and I want to check from mongo db whether my mobile number is unique or not. Can someone help me with a Schema definition for this?

**Comment by lengk** [comment]
Duplicate of #527
