### ISSUE TITLE
MatchedData not returning all values after validating passed with oneOf

### ISSUE THREAD

**Issue by somppa** [ctavan/express-validator#533]
This problem started after upgrading from 4.3.0 to 5.0.x.
When sending json data for validation, matchedData does not return last value:

Example:
```
{ "body":"human", "version":"test" }
```

Validation:
```
router.post("/test", [
	oneOf([
		body("body").exists(),
		body("body").isEmpty()
	]),
	oneOf([
		body("version").exists(),
		body("version").isEmpty()
	])
], (req, res) => {
	const errors = validationResult(req);
	const bodyValues = matchedData(req);

	console.log(bodyValues);
```

Would return only:
```
{ "body":"human" }
```
It works perfectly fine with 4.3.0 returning:
```
{ "body":"human", "version":"test" }
```

Tried also the way as it was documented and matchedData returned empty object.

Hopefully oneOf is ment to work in array as it used to, since it covers 4 different options for body values in the first example. This second way I would need to write all 4 separately.

```
router.post("/testi",
	oneOf([
		[
			body("version").exists(),
			body("body").exists()
		],
		[
			body("body").isEmpty(),
			body("version").isEmpty()
		]
	]), (req, res) => {
		const errors = validationResult(req);
		const bodyValues = matchedData(req);

		console.log(bodyValues);
```

**Comment by somppa** [comment]
Tried also the way as it was documented and matchedData returned empty object.

Hopefully oneOf is ment to work in array as it used to, since it covers 4 different options for body values in the first example. This way I would need to write all 4 separately.

```
router.post("/testi",
	oneOf([
		[
			body("version").exists(),
			body("body").exists()
		],
		[
			body("body").isEmpty(),
			body("version").isEmpty()
		]
	]), (req, res) => {
		const errors = validationResult(req);
		const bodyValues = matchedData(req);

		console.log(bodyValues);
```

**Comment by gustavohenke** [comment]
Hi @somppa, thanks for finding this out!
This bug was introduced while making `matchedData` include only data from the passed fields in `oneOf` (see #482).

Unfortunately looks like multiple `oneOf`s in the same request break it.
If you want to go ahead and fix this issue, it should be pretty easy:

https://github.com/ctavan/express-validator/blob/1399d649f09f329708fed73732bfbe1745b1bc27/check/one-of.js#L20-L22

**Comment by gustavohenke** [comment]
🚢 v5.1.1 is out with the fix!
