### ISSUE TITLE
behaviour of .custom and .optional

### ISSUE THREAD

**Issue by roosh-t3** [ctavan/express-validator#534]
```js
 check('password').isLength({min: 6}).withMessage("Minimum Length must be at least 6").optional({ checkFalsy: true }),
    check('passwordConfirmation').custom((value, { req }) => {
        if(req.body.password === value)
            return true;
        else
            throw new Error("Password Doesn't match");
    })
```
above check password works as it should. as an example. If the field is empty it doesn't check for validation and passes. but when I apply the `.custom` with `.optional` optional takes the lead and custom is not even checked.

**Comment by gustavohenke** [comment]
Oh. It's not that `custom` isn't checked, what happens is that for some reason we're setting stuff in `req.body`, so `password` is undefined, just like `passwordConfirmation`!

Thanks for finding this one. Fix is on the way.

**Comment by roosh-t3** [comment]
You've misunderstood. I have 4 field form. `Name`, `Username`. `Password` and `Password Confirmation`.  If user wants to update his password He will enter on `password` and `password confirmation`. 
1. If password is present check for minimum length. 
2. if password is not present just ignore the validations
> Ref - See above code.

1. If I add an `.optional()` on passwordConfirmation It doesn't check against the `.custom()` and passes the validation.
2. if I just use .custom only I get the needed behavior but the passwordConfirmation field is present in the matchedData Object

**Comment by gustavohenke** [comment]
What request are you issuing? 
I tried your example and it works:

<img width="1492" alt="screen shot 2018-03-05 at 21 55 17" src="https://user-images.githubusercontent.com/826553/36971455-fdb25a62-20bf-11e8-83d1-0d43ae6fa0f0.png">

Although I must say that your code can be optimised.
You don't need to check `passwordConfirmation` at all, you can give the same custom validator to `password`, and everything should work as you expect.

**Comment by roosh-t3** [comment]
url-encoded. 
add an `.optional()` to passwordConfirmation and see the validation passes. even though it should validate against `.custom()`

thanks for the tip. I wanted to have Field wise error messages,
