### ISSUE TITLE
How to use trim with checkSchema in Typescript

### ISSUE THREAD

**Issue by josecolella** [ctavan/express-validator#542]
Hello,
first of all I want to thank you for an amazing library. I am currently using the checkSchema method, and I would like to use it with trim, but I receive the issue:
 

> Object literal may only specify known properties, and 'trim' does not exist in type 'ValidationParamSchema'.

This is what I am using in my code. 

```javascript
checkSchema({
  username: {
    exists: true,
    errorMessage: 'Invalid username name',
    in: ['params'],
    isLength: {
      errorMessage: 'username should not be longer than 30 characters',
      options: {
        min: MINIMUM_SEARCH_LENGTH,
        max: MAXIMUM_SEARCH_LENGTH
      }
    },
    trim: true
  }
})
```

Are you maybe missing trim as a property of checkSchema in types? or something on my end?

**Comment by josecolella** [comment]
@gustavohenke Any comments?

**Comment by gustavohenke** [comment]
Hi @josecolella, if you have the time to fix it, then yeah, please send your PR! 👍 
Sorry for the delay.

**Comment by sant123** [comment]
Please see https://github.com/ctavan/express-validator/pull/546

**Comment by gustavohenke** [comment]
🚢 v5.1.0 released with this
