### ISSUE TITLE
custom validation (Existing email)

### ISSUE THREAD

**Issue by ZiedChekir** [ctavan/express-validator#545]
Hello, 
I wanted to use express-validator to check if the username exists 
 here is my code 
```js
req.checkBody('username').len({
            min: 6,
            max: 20
        }).withMessage('Username must be between 6 and 20 characters including numbers')
        .hasNumAndChar().withMessage('userame must be between 6 and 20 characters including numbers, no spacing and no speacial characters')
        .usernameExists().withMessage('userfds alreadsqsqdqsdy exists')
```

and here is the verification code with async/await

```js
usernameExists: async (value)=>{
     var user = await Users.find({username:value})
console.log(user.length)
     return user.length == 0;
    }
``` 
           
the problem with async/await that the validation didnt execute at all even if the return is true or false 

so i tried with promises
```js
usernameExists:  (value)=>{
     Users.find({username:value})
                 .then(function(result){
                      console.log(result)
                      return result.length ==0
                  })
                 .catch(function(err){console.log(err)})
    }
```

the console.log was executed so i know that it s some node js asynchronous stuff. but i dont know how to solve this problem can you help me out ?

**Comment by gustavohenke** [comment]
The only difference between your 2 examples is that the second one isn't returning to express-validator.
Apart from that, there's nothing wrong with your code, so the problem must lie somewhere else -- eg a DB connection issue that made `Users.find` take too long in your initial attempts?

**Comment by ZiedChekir** [comment]
Thanks @gustavohenke for your answer. There was nothing wrong with the custom validation i used the only problem is the approach that i used (diffrent than what s in the documentation).
using the old methods like 
using  expressvalidator as a midleware  and including custom validation there
`app.use(expressValidator({
    customValidators:{
   usernameExistsAsync: async function(value){
            var user = await Users.find({username:value})
            return user.length == 0;
},
usernameExistsPromise:function(value){
  Users.find({username:value})
.then(function(result){
                return result.length ==0
            })
            .catch(function(err){console.log(err)})
}
   }
))`

and then 
`app.post('/register',function(req,res,next){
   req.checkbody('username').usernameExistsPromise().usernameExistsAsync()
}`
this didnt work for me (i think it s the old method )
and what worked for me is simply
`app.post('/register',[check('username').custom(async function(value){
			var user = await User.find({username:value})
			return user.length == 0;
		})
		.withMessage('username already exits')],function(req,res,next){
                   var Errors = validationResult(req)
}`
and thanks for your time :)  (maybe it s better to make a note in the documentation to use the new method )

**Comment by gustavohenke** [comment]
I'm glad you found an answer. The docs are already making heavy usage of the check APIs over the legacy ones though.

**Comment by losh11** [comment]
Facing a similar issue; how are we supposed to handle slow db connections? Using async/await + promises hasn't worked for me.

```javascript
  check('username')
    /* ... */
    .custom(async username => {
      await Users.getUser(username).then(user => {
        console.log(user)
        if (user === null) {
          return true
        } else {
          return false
        }
      })
    }).withMessage('Username already exists'),
```

Where `Users.getUser is just a mongoose promise`...

```javascript
module.exports.getUser = function(username) {
  const query = { username: username }
  return Users
    .findOne(query)
    .then(user => {
      return user
    })
    .catch(err => {
      throw (err);
    })
};
```

**Comment by gustavohenke** [comment]
@losh11 you aren't returning from your custom validator. Add `return` before `await Users.getUser(...)` and it should work.

**Comment by losh11** [comment]
Of course duh! sorry about that & thanks
