### ISSUE TITLE
Schema validations stopped working when used enctype="multipart/form-data"

### ISSUE THREAD

**Issue by mohsincynexis** [ctavan/express-validator#551]
Form validations were working fine until I added enctype="multipart/form-data" 
Once I added enctype the form validations always return error messages irrespective of the values we put in the fields.

I have used the following module in my app.js
```
var bodyParser    = require('body-parser');
const flash = require('express-flash-notification');
const cookieParser = require('cookie-parser');
const session = require('express-session');
```
then used them as 
```
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({ extended: false }));
app.use(cookieParser());
app.use(session({
    secret: 'xxx',
    name: 'xxxx',
    resave: false,
    saveUninitialized: true
}));
```

And I am fetching the validations result like this 
`var formValidationObject = validationResult(req);`

Please guide what could be the possible issue.

**Comment by gustavohenke** [comment]
body-parser doesn't handle multipart.
Use a package like multer for these content types, then pay attention to [some common gotchas when using it](https://stackoverflow.com/questions/46046254/new-express-validator-syntax-validate-form-processed-by-multer).
