### ISSUE TITLE
HTML entities being double-escaped

### ISSUE THREAD

**Issue by alexcolb** [ctavan/express-validator#554]
The escape() sanitizer is being called multiple times, leading to double-escaping. Ie:
- Consider the field value: ```->```
- This should escape to ```-&gt;``` which would, in HTML documents, show up as: ```->```
- Instead, we get ```-&amp;gt;``` which will show up in HTML as ```-&gt;```
- The escaped string no longer resembles the input value. The **validator** package seems to escape ampersands before anything else for this exact reason.

Reproduction:
```
app.get('/', check('q').escape(), (req, res, next) => {
  res.json(matchedData(req));
});
```
Firing **GET /?q=->**

**Comment by gustavohenke** [comment]
Fixed with v5.1.2!
