### ISSUE TITLE
Validations are being processed even for routes that are not being used

### ISSUE THREAD

**Issue by gascencao** [ctavan/express-validator#555]
I'm implementing login and registration forms with their corresponding validations.

This is my code (a simplified version to illustrate the issue). There are fields that exists in both forms (i.e. username and password). The problem is that both validations are being executed, nevertheless which form is being submitted (therefor, nevertheless the route).

```
let usernameValidator = body('username')
    .isLength({ 'min': 3 });

let registerValidator = [
  usernameValidator.custom(value => {
      if (usernameExists(value)) {
        return Promise.reject('User already exists');
      }
    })
];

let loginValidator = [
  usernameValidator.custom(value => {
      if (!usernameExists(value)) {
        return Promise.reject('User doesn't exist');
      }
    })
];

router.post('/register', registerValidator, (request, response) => {
  let errors = validationResult(request);
  if (!errors.isEmpty()) {
    response.status(422).json(errors.mapped());
  } else {
    // Save the new user
    response.send({ success: true });
  }
});

router.post('/login', loginValidator, (request, response) => {
  let errors = validationResult(request);
  if (!errors.isEmpty()) {
    response.status(422).json(errors.mapped());
  } else {
    // Init session
    response.send({ success: true });
  }
});

```
Just to be clear, the actual message that I'm getting is correct. I mean, if I send an existing username, I get the message saying that the user exists. If I send a new username, I get the message saying that the user doesn't exist. But I shouldn't receive the existing user error on login, nor the "user doesn't exist" error on registration.

What should be the correct solution for my issues? Am I doing something wrong?

I appreciate any help on this! Thank!

**Comment by gustavohenke** [comment]
The validator is currently mutable, so when you reuse `usernameValidator` and invokes `.custom()` on it, you're adding another validator on the same chain.
That's why you get these results.

**Comment by gascencao** [comment]
Thanks, @gustavohenke !

Now that you told me, It almost seems obvious... 

I changed my usernameValidator to be a function and now it works perfectly.

```
let usernameValidator = () => body('username')
    .isLength({ 'min': 3 });
```

Thanks again!

**Comment by gustavohenke** [comment]
No worries!
Improving docs on it should help future users so that they don't fall into this "trap" as well.
