### ISSUE TITLE
Assert Defaults?

### ISSUE THREAD

**Issue by d1b1** [ctavan/express-validator#56]
I have noticed that as I used the middleware I keep having to do the following:

    var offset = parseInt(req.urlparams.offset); 
    if (offset) req.assert("offset", "Invalid Offset. Minimum of 0 mins.").isNumeric().min(0);
    offset = offset || 0;

Basically I only want to validate the offset URL or Param value when it exists, otherwise I want to set the value to 0. This would dry out the code and let the middleware keep doing it job without the need for the if then statement.

Here is my proposed change to the same code:

    var offset = parseInt(req.urlparams.offset); 
    if (offset) req.assert("offset", "Invalid Offset. Minimum of 0 mins.", 0).isNumeric().min(0);
    offset = offset || 0;

**Comment by rustybailey** [comment]
You should be able to achieve this using the `optional()` method added in this PR: https://github.com/ctavan/express-validator/pull/95

See README for more details: https://github.com/ctavan/express-validator#optional-input
