### ISSUE TITLE
how use custom validator like old style?

### ISSUE THREAD

**Issue by stevenluoxiaohua** [ctavan/express-validator#562]
in my first project use express-validator, my code like this.
`req.checkBody('phone_number', 'phone number is invalid').phoneNumber();`

now, I use Schema Validation & legacy API, I don't konw how to use custom validate function.

PS: my English is poor, Don't know if you can understand?

**Comment by gustavohenke** [comment]
There are some examples in this project's README, and even some issues with extensive custom validators discussion: #413 #550

**Comment by stevenluoxiaohua** [comment]
thank you for your reply.
This practice will have a lot of duplicate code.
What I want is a definition, Use everywhere.

**Comment by stevenluoxiaohua** [comment]
Thank you for your reply. I've got your point
