### ISSUE TITLE
req.getvalidationresult() breaks nodejs app

### ISSUE THREAD

**Issue by TheFridgeMaster** [ctavan/express-validator#566]
Hi there,

I have been working on a small nodejs project and I am coming across a small issue, which is no doubt human error, but I am at a loss at this point and could use some pointers.

I currently have an express form with 5 fields and are using express-validator to validate various properties. 

I started by using req.validationErrors() to retrieve the errors and I am displaying them via express-toastr notifications, however there are many duplicate error messages as many of the fields have chained filters.

I did some googling and came across the below solution:

```
req.getValidationResult().then( result => {
  var errors = result.useFirstErrorOnly().array();
})
```

However, whenever I change to this method, I receive internal server error and the message:

`Cannot read property 'toastr' of undefined`

I really don't understand what is happening here as the toast notifications work perfectly when I am using the old validationErrors() method.

Cheers,
Kyle.

**Comment by TheFridgeMaster** [comment]
```
var express = require('express');
var bodyParser = require('body-parser');
var validator = require('express-validator');
var router = express.Router();
var path = require('path');
var fs = require('fs');

router.use(validator());

router.get('/', function(req, res, next) {
  res.render('index', { title: 'PiFlix', req: req });
});

router.post('/', function(req, res){
  req.checkBody('field1', 'message 1').isEmail()
  req.checkBody('field2', 'message 2').notEmpty();
  req.checkBody('field3', 'message 3').notEmpty().isAscii();
  req.checkBody('field4', 'message 4').notEmpty().isAscii().isLength({min:1, max:32});
  req.checkBody('field5', 'message 5').notEmpty().isLength({min:8, max:63}).isAscii();
  req.checkBody('field6', 'message 6').notEmpty().isIP();
  
  req.getValidationResult().then( result => {
    var errors = result.useFirstErrorOnly().array(); 
  })

  if (errors){
    console.log(errors)
    for (let error of errors){
      req.toastr.error(error.msg)
      console.log(error)
    }
    res.redirect(req.get('referer'));
  }
})

module.exports = router;

```

**Comment by gustavohenke** [comment]
Ah. As I said, you're using an asynchronous API now -- everything that depends on `errors` var must be nested in that `.then()` call.
Like this:

```js
req.getValidationResult().then( result => {
  var errors = result.useFirstErrorOnly().array();
  
  console.log(errors)
  for (let error of errors){
    req.toastr.error(error.msg)
    console.log(error)
  }
  res.redirect(req.get('referer'));
});
```

To better understand what's going on, I recommend you to research these matters:
- JS variables scope
- Asynchronous JS programming (eg callbacks, promises, async functions, etc)

These are quite extensive reads, but easy to find quality content.

**Comment by TheFridgeMaster** [comment]
thank you so much! :D
