### ISSUE TITLE
Hyperlink to #legacy-api on npmjs.com is broken

### ISSUE THREAD

**Issue by jen729w** [ctavan/express-validator#567]
The various links to "[the legacy API](https://www.npmjs.com/package/express-validator#legacy-api)" section at the npmjs.com documentation are broken.

There is no id/name defined at that section for this to link to.

**Comment by jen729w** [comment]
Oh, wait. Are they _all_ broken?

Just also found:
Hyperlinks point to: .../express-validator#sanitization-chain-api
id in HTML is actually: #user-content-sanitization-chain-api

I'd be happy to fix these up (it would be my first open-source contribution!) but I presume I need permissions to edit that npmjs.com page?

**Comment by gustavohenke** [comment]
Are you unable to navigate? I see the anchor IDs don't match the links, but they all work for me:

![kapture 2018-04-17 at 9 56 28](https://user-images.githubusercontent.com/826553/38841027-ab0b472e-4225-11e8-9688-f3d3fdc42ae5.gif)

Also we can't change them _only_ on npm, it generates that from the project's README.md file, which works just fine on GitHub.

**Comment by jen729w** [comment]
It seems that they work in Chrome but not Safari on macOS, my iPhone or iPad (all running latest versions).

**Comment by gustavohenke** [comment]
@jen729w it might make sense to report this on https://github.com/npm/www/issues.
