### ISSUE TITLE
TypeError: Cannot call method 'assert' of undefined

### ISSUE THREAD

**Issue by yfeng** [ctavan/express-validator#59]
Hi, I type  "app.use(expressValidator());" in my app.js, then I type "node app.js" it give me some error:
    req.assert("name", 'xxxx0-9，a-z，A-Z').isAlphanumeric();
        ^
TypeError: Cannot call method 'assert' of undefined

**Comment by rustybailey** [comment]
You need to make sure you're using `req.assert()` inside a route's callback. `req` is probably undefined because you're trying to use that line outside of the context of a route. See "Usage" in the README for more details.
