### ISSUE TITLE
Validate array of objects?

### ISSUE THREAD

**Issue by gh-naylor** [ctavan/express-validator#67]
When I submit a single object as my payload I can validate keys very easily with:

    req.checkBody('year', 'invalid year').len(4,4).isNumeric();

But I would like to submit an array of objects and loop through them with something like:

    _.each(self.req.body, function(element, index, list) {
        req.checkBody([index].year, 'invalid year').len(4,4).isNumeric();
    });

I've also tried using ```req.assert``` with ```element.year``` and even ```element.year.toString()``` with no luck. 

What am I doing wrong? Or is this type of functionality even possible?

**Comment by rustybailey** [comment]
Related issue here: #125. There is a solution offered in that issue. Please continue the conversation there.

**Comment by jyotman** [comment]
@rustybailey I don't think this is same issue as #125.

I think the OP was asking what if the `req.body` is an array of objects itself.

Example JSON - 

```
[
    {"name": "Abc"},
    {"name": "Def"}
]
```

How do I begin to validate this. What argument do I provide to `req.checkbody()` because I want to validate the body itself. I want to do something like `req.checkBody().isArray()`.

**Comment by base698** [comment]
```
          body('pages')
             .custom((item)=>_.isArray(item) && item.length > 0)
             .withMessage( "At least one page is required")
```

What about this?

**Comment by foodaka** [comment]
@jyotman did u find a workaround for this ? is there a way to validate the objects in the array iteself? pretend the post payload looks something like below. how to validate name is string and age is int in the array.
```
[
 { name: 'joe', age: 25},
 {name: 'alice', age: 30}
]

```

**Comment by gustavohenke** [comment]
@foodaka please have a look at [Wildcards](https://express-validator.github.io/docs/wildcards.html)

**Comment by jyotman** [comment]
@foodaka I did something like this - 

```javascript
for(let i = 0; i < req.body.length; i++)  {
    req.checkBody([i, 'name']).notEmpty();
    req.checkBody([i, 'age']).isInt();
}
```

**Comment by aabiskar** [comment]
This one works for me

"user_info ": [
  { name: 'john', age: 30},
  {name: 'rose', age: 25}
]

        // Validate the array of Objects
        req.checkBody('user_info.*.name', "User name is required").notEmpty();
        req.checkBody('user_info.*.age', "User age is required").notEmpty();

**Comment by ealexhaywood** [comment]
I was able to do it with wildcards like this:

```javascript
/* Raw alerts fired from Prometheus Server */
app.post('/api/v1/alerts', [
  body().isArray(),
  body('*.labels', 'labels field must be a JSON object').exists().isJSON(),
  body('*.annotations', 'annotations field must a JSON object').exists().isJSON(),
  body('*.startsAt', 'startsAt field must be a string').exists().isString(),
  body('*.endsAt', 'endsAt field must be a string').exists().isString(),
  body('*.generatorURL', 'generatorURL field must be a URL').exists().isURL({ require_tld: false })
], (req, res) => {
  // Finds the validation errors in this request and wraps them in an object with handy functions
  const errors = validationResult(req);
  if (!errors.isEmpty()) {
    return res.status(422).json({ errors: errors.array() });
  }

  alerts = req.body;
  console.log(req.body);
  return res.status(200).json(alerts);
});
```

**Comment by BertCatsburg** [comment]
For me the custom validation of express-validator was the simplest. 

```
check('myArray')
   .isArray()
   .custom ( a => {
       // a holds the full array
       return a.every( (e) => {
         // e is each element in the array
         if (e === "ok") {
            return true;
         } else {
            return false;
             // if you return false at least once, then the result of 'every' is false and 
             // the validator triggers an error
         }
      }
    .withMessage('Array must contains strings with the word "ok" ')
```

**Comment by ddemydenko** [comment]
So how can I validate array of instance based on schema?
I am looking for something like this:

checkSchema(schema, myArray);

Now I have not such possibility, cause checkSchema uses req.body, and when body is 
[
  { name: 'something', value: 'anything'},
  { name: 'something', value: 'anything'},
  { name: 'something', value: 'anything'}
]
It doesn't work properly

**Comment by ddemydenko** [comment]
I have a post method, that according to restfull api can accepts one instance or array of the same instances. So  I looking for a possibility using this approach [Schema Validation](https://express-validator.github.io/docs/schema-validation.html) to bulk create :

```
POST /plots/ HTTP/1.1
Host: localhost:5000
[
  { name: 'something', value: 'anything'},
  { name: 'something', value: 'anything'},
  { name: 'something', value: 'anything'}
]
```
I already have a schema, that works fine for one instance but I want apply it for many instances. How I can iterate array?

**Comment by ddemydenko** [comment]
> Hello @ddemydenko,
> I don't understand your question. According to [the docs](https://express-validator.github.io/docs/schema-validation.html) the checkSchema accepts 1 object with fields as keys with each an object (containing the validations) as values. Each value seems to have an 'options' which has 'req' available. (Although I haven't worked it myself, I'm more than happy to play around it for you)
> Your example shows 2 params to checkSchema. That I don't understand.

I have a post method, that according to restfull api can accepts one instance or array of the same instances. So  I looking for a possibility using this approach [Schema Validation](https://express-validator.github.io/docs/schema-validation.html) to bulk create :

```
POST /plots/ HTTP/1.1
Host: localhost:5000
[
  { name: 'something', value: 'anything'},
  { name: 'something', value: 'anything'},
  { name: 'something', value: 'anything'}
]
```
I already have a schema, that works fine for one instance but I want apply it for many instances. How I can iterate array?

**Comment by BertCatsburg** [comment]
Regardless of the checkSchema, I've put your request in my 'check' example. 
Is this what you require?

```
check('myField')
    .custom(a => {
        if (Array.isArray(myField)) {
            return a.every((e) => e.name === "something" && e.value === "anything")
        }
        return (a.name === "something" && a.value === "anything")
    })
    .withMessage('Either and Array or an Instance please');
```

**Comment by ddemydenko** [comment]
Here is my server:
```javascript
const express = require('express');
const expressValidator = require('express-validator');
const { checkSchema } =  require('express-validator/check');

const app = express();
const port = 3000;
const schema = require('./schema.json');

app.use(express.json());
app.use(expressValidator());
app.post('/users',checkSchema(schema), (req, res) => {
    const err = req.validationErrors();
    console.log(err);
    res.send(err)
});

app.listen(port);
```


Here is my schema.json
```javascript
{
  "guid": {
    "isEmpty": false
  },
  "url": {
    "isEmpty": false,
    "isURL": true
  },
  "amount": {
    "isEmpty": false,
    "isFloat": true
  }
}
```
And here is my single object request, validates as expected
```
POST /plots/ HTTP/1.1
Host: localhost:5000
{
    "url": "https://www.example.com/plots/7uJ3g62fqHhax3dLzmZGGn",
    "type": "Field",
    "amount": 25
}
```
Since I already have a defined schema, therefor to avoid code duplication I want to use this schema to validate multi objects creation, aka bulkCreate
```
POST /plots/ HTTP/1.1
Host: localhost:5000
[
    {
        "url": "https://www.example.com/plots/7uJ3g62fqHhax3dLzmZGGn",
        "type": "Field",
        "amount": 25
    },
    {
        "url": "https://www.example.com/plots/7uJ3g62fqHhax3dLzmZGGn",
        "type": "Field",
        "amount": 25
    }
]
```
But this case works wrong. Validation failed, Because checkSchema consider body like a single object.
I looking for a way to iterate array, or something else that allows me validete singlie object and array of object as well.

**Comment by ddemydenko** [comment]
Ok, folks, it is very unobvious, and this trick undocumented. I had to add asterisk
Here is solution
```
{
  "*.guid": {
    "isEmpty": false
  },
  "*.url": {
    "isEmpty": false,
    "isURL": true
  },
  "*.amount": {
    "isEmpty": false,
    "isFloat": true
  }
}
```

**Comment by gustavohenke** [comment]
> it is very unobvious, and this trick undocumented. I had to add asterisk

@ddemydenko it's documented under [wildcards](https://express-validator.github.io/docs/wildcards.html).
