### ISSUE TITLE
.matches() doesn't work

### ISSUE THREAD

**Issue by a265334** [ctavan/express-validator#81]
I tried using: ```req.assert('field', 'error').matches(/myregex/);```
Is this the right way to call the method 'matches'? Because chriso/validator.js uses ```matches(str, pattern [, modifiers])```.

**Comment by rustybailey** [comment]
This repo is currently using version 3.34.0 of node-validator, so the `matches` method should work now.

**Comment by smarkdurbin** [comment]
.matches() is not working.

**Comment by martinliptak** [comment]
This doesn't work: 

checkSchema({
  name: {
     matches: /\.(pdf)|(doc)|(docx)|(rtf)$/g
  }
})

This works:

checkSchema({
  name: {
    matches: {
      options: [/\.(pdf)|(doc)|(docx)|(rtf)$/, 'g']
    }
  }
})
