### ISSUE TITLE
Fails strict mode

### ISSUE THREAD

**Issue by killroy42** [ctavan/express-validator#88]
express_validator.js fails strict mode in two, easy to fix locations:
Line 47 and line 107;

Simply replace:
```
var arguments = Array.prototype.slice.call(arguments);
var args = [value].concat(arguments);
```

with:
```
var args = [value].concat(Array.prototype.slice.call(arguments));
```

**Comment by rustybailey** [comment]
Closing since you fixed this already: https://github.com/ctavan/express-validator/pull/89
