### ISSUE TITLE
validating multipart/form-data?

### ISSUE THREAD

**Issue by alsoicode** [ctavan/express-validator#90]
I'm very new to Express and Node, and am having an issue validating a form which contains text inputs and a file field.

If I set the enctype on my form to "application/x-www-form-urlencoded", express-validator will catch empty fields, etc. When I set the enctype to "multipart/form-data", all of the validators fail, even through data is present, and in the correct format.

What's the trick to validating an enctype of "multipart/form-data" ?

**Comment by Nikhil00712** [comment]
Why this is closed without answer??

**Comment by saikumarkunchaa** [comment]
please anyone give answer her

**Comment by saikumarkunchaa** [comment]
please anyone give answer here

**Comment by gustavohenke** [comment]
@Nikhil00712 that's an issue from 2014, express-validator changed a lot since then! 

So, #276 and my closing comment explain the situation a bit.
Basically, validating stuff that is not standard express is out of the plans for a while. And, as usual, ideas are welcome.
