### ISSUE TITLE
Nested objects with arrays 

### ISSUE THREAD

**Issue by riston** [ctavan/express-validator#98]
Does the current validation process include handling the arrays ? I have nested user input similar to this (request body):

```js
{ "person": { "name": "Mike", "emails": [ "aadsa@dsad", "a@a.com" ] } }

```
So using such validation rule should apply on the each array element, currently its not working such way:
```
req.checkBody('person.emails').isEmail()
```

**Comment by gebrits** [comment]
would be awesome if this worked :+1:

**Comment by rustybailey** [comment]
In the module's current state, in order to validate each item in an array, you would need to write a custom validator. See if you can adapt the solution offered here to your use case: https://github.com/ctavan/express-validator/issues/125

**Comment by LogansUA** [comment]
Hello. Is this now became possible with v4 or i still need to write custom validators?

**Comment by gustavohenke** [comment]
It's possible, @LogansUA. You just have to make use of wildcards.
As per the OP's example, this would be `person.emails.*`.

**Comment by nitin-jotwani** [comment]
@gustavohenke I'm confused that why it's validating only first element of an array when using a wildcard.
Ex. 
`{
	"param1": "212",
	"param2": ["55", "wrong89"]
}`

`param2.*: {
"in": "body",
      "isInt": {
        "errorMessage": "Please enter valid number"
      }
}`

**Comment by gustavohenke** [comment]
Hi @nitin-jotwani, v4.3.0 currently has a bug when you use wildcards with legacy API. See #477 for more info.
